
</div>
        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/form-elements.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/style.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/custom.css">
        <title>COCAI</title>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Top content -->
        <div class="row">
            <div class="col-sm-8">
                <img class="cabecera" hidden height="50px" src="<?php echo PUBLIC_URL;?>img\cabecera.jpg" alt="">
            </div>
            <div class="col-sm-4">
                <img style="float: right" class="cabecera" hidden height="65px" src="<?php echo PUBLIC_URL;?>img\IVSS.png" alt="">
            </div>
            
        </div>
        
<center>
    <div style="margin-top: 15%" id="cargando">
        <img width="200" height="100" class="img" src="<?php echo PUBLIC_URL; ?>img/LOGO-COCAI.png"><br>
        <img class="img" width="150px" src="<?php echo PUBLIC_URL; ?>img/loading.gif">
    </div>
</center>
<div id="body" hidden>
<div class="container py-5 mt-3">
    <div class="row mt-3">
        <div class="col-md-12 ">
            <div class="row">
            <div class="col-5 hidden-sm-up">
                                <img style=" float: right;" src="<?php echo PUBLIC_URL;?>img\LOGO-COCAI.png" class="img-fluid imghd" alt="img">
                            </div>
                <div class="col-md-6 mx-auto">
                    <span class="anchor" id="formLogin"></span>

                    <!-- form card login -->

                    <div class="card rounded-0">
                        <div class="card-header" style="padding: 3px">
                            <div class="row ">
                                <div class="col-3 hidden-xs-down">
                                    <img  src="<?php echo PUBLIC_URL;?>img\LOGO-COCAI.png" class="img-fluid" alt="epoc" style="float: left">
                                </div>
                                <div class="col">
                                        <h6 class="text-center textoh6">Inicio de sesión</h6>
                                </div>
                                <div class="col-3">
                                        <button class="btn btn-sm btn-outline-secondary" style="cursor: hand; cursor: pointer; border-radius: 4px; float: right;" type="button" name="" onclick="window.close();"  >
                                            <span class="fa fa-remove"></span>
                                        </button>
                                </div>

                            </div>
                            
                        </div>

                        <div class="card-body">
                        <div class="row mb-3 pb-3">
                            <div class="col-10">
                                    <h5 class="text-left"><strong>COCAI</strong></h5>
                                    <div class="row">
                                        <div class="col">
                                        <h6 class="text-left">Control de Costos y Administracion de Inventario</h6>
                                        </div>
                                    </div>
                                </div>
                            <div class="col-2 hidden-xs-down">
                                <img style=" float: right;" src="<?php echo PUBLIC_URL;?>img\llave.jpg" class="img-fluid imghd" alt="img">
                            </div>
                        </div>
                        
                        
                        
                            <form id="login" class="form-signin" action='<?php echo BASE_URL . 'login/signIn'?>' method="post">
                                <?php if (isset($this->_error)) echo $this->_error; ?>
                                
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon fa fa-lg fa-lock" id="basic-addon1"></span>
                                        <input type="password"  class="form-control" id="clave" placeholder="Contrase&ntilde;a" name="password"/>
                                    </div>
                                </div>
                                
                                <div class="input-group justify-content-center">
                                    <button style="cursor: hand; cursor: pointer" type="submit" id="btn-login" class="btn btn-outline-primary">
                                        <span  class="fa fa-sign-in"></span>
                                        <font style="margin-left: 1px;" size="4">  Iniciar Sesion</font>
                                    </button>
                                </div>

                                
                            </form>
                        </div>
                        
                        <!--/card-block-->
                    </div>
                    <p class="text-right">Powered by HDJGR</p>
                    <!-- /form card login -->

                </div>


            </div>
            <!--/row-->

        </div>
        <!--/col-->
    </div>
    <!--/row-->
</div>
<!--/container-->
</div>


        <footer></footer>


        <!-- Javascript -->
        <script src="<?php echo PUBLIC_URL; ?>js/jquery-1.12.1.min.js"></script>
        <script src="<?php echo PUBLIC_URL; ?>js/bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_URL; ?>js/jquery.backstretch.min.js"></script>
        <script src="<?php echo PUBLIC_URL; ?>js/scripts.js"></script>
        <script type="text/javascript"> 
        $(document).ready(function(){
            $('#cargando').fadeOut(700);
            setTimeout(function() {$('#body').fadeIn(800);$('#body').prop("hidden",false);$('.cabecera').fadeIn(800);$('.cabecera').prop("hidden",false);}, 700);
           /* $("a.subM").click(function(event){ event.preventDefault(); linkLocation = this.href; $('#body').fadeOut(500, redirectPage); }); function redirectPage() { window.location = linkLocation; } 
            $(".atras").click(function(event){ event.preventDefault();  $('#body').fadeOut(500); });*/ 
        });
    </script>
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->


  <label  hidden id="base_url"><?php echo BASE_URL; ?></label>
  <!-- / START - page related files and scripts [optional] -->
    <?php  if (isset($_view_params['js']) && count($_view_params['js'])): ?>
    <?php   for ($i = 0; $i < count($_view_params['js']); $i++):  ?>
        <script src="<?php echo $_view_params['js'][$i]; ?>"></script>
    <?php   endfor; ?>
    <?php  endif;?>
    <!-- / END - page related files and scripts [optional] -->
  <script>
    var BASE_URL = $('#base_url').text();
    </script>

  
  
  
  
  
  