<!doctype html>
<html lang="us">
<head>
  <meta charset="utf-8">
  <title>jQuery UI Example Page</title>
  <link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">

  <style>
    .labels{
      margin-bottom: -1%;
      float: left;
    }

  /* Tooltip */
  .test + .tooltip > .tooltip-inner {
      background-color: #337ab7; 
      color: #FFFFFF; 
      border: none; 
      padding: 1px;
      font-size: 14px;
  }
  /* Tooltip on top */
  .test + .tooltip.top > .tooltip-arrow {
      border-top: 5px solid #337ab7;
  }
  /* Tooltip on bottom */
  .test + .tooltip.bottom > .tooltip-arrow {
      border-bottom: 5px solid #337ab7;
  }
  /* Tooltip on left */
  .test + .tooltip.left > .tooltip-arrow {
      border-left: 5px solid #337ab7;
  }
  /* Tooltip on right */
  .test + .tooltip.right > .tooltip-arrow {
      border-right: 5px solid #337ab7;
  }
 /*autocomplete style for modal*/
.ui-menu .ui-menu-item a {
  font-size: 12px;
}
.ui-autocomplete {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1051 !important;
  float: left;
  display: none;
  min-width: 160px;
  _width: 160px;
  padding: 4px 0;
  margin: 2px 0 0 0;
  list-style: none;
  background-color: #ffffff;
  border-color: #ccc;
  border-color: rgba(0, 0, 0, 0.2);
  border-style: solid;
  border-width: 1px;
  -webkit-border-radius: 2px;
  -moz-border-radius: 2px;
  border-radius: 2px;
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -webkit-background-clip: padding-box;
  -moz-background-clip: padding;
  background-clip: padding-box;
  *border-right-width: 2px;
  *border-bottom-width: 2px;
}
.ui-menu-item > a.ui-corner-all {
    display: block;
    padding: 3px 15px;
    clear: both;
    font-weight: normal;
    line-height: 18px;
    color: #555555;
    white-space: nowrap;
    text-decoration: none;
}
.ui-state-hover, .ui-state-active {
      color: #ffffff;
      text-decoration: none;
      background-color: #0088cc;
      border-radius: 0px;
      -webkit-border-radius: 0px;
      -moz-border-radius: 0px;
      background-image: none;
}
#modalIns{
    width: 500px;
}
  </style>


  
</head>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
                            
<div id="page-wrapper">
            <div class="">

                <div class="row">
                    <div class="col-lg-12 ">
                        

                        <div style="margin-top: 2%" class="card cardH">
                        <div class="card-header">
                            <center><h3><o id="titulocard">Asignacion de productos al agrupado</o> <?php $ti=strtolower($this->mercancia[0]['producto']); echo "[".ucwords($ti)."]"; ?></h3></center>
                        </div>
                        <input type="hidden" name="" id="idtienda" value="<?php echo $this->model[0]['idU']?>">
                        <input type="hidden" name="" id="idempr" value="<?php echo $this->model[0]['empresa_id']?>">
                        <?php if ($this->tienda[0]['modelo'] != null): ?>
                            <div>
                              <img width="10%" height="10%" style="float: right;" src="<?php $model=strtolower($this->tienda[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-responsive" alt="">
                            </div>
                        <?php endif ?>
                        <div class="card-block" style="padding: 0px">
                          

                          <!-- Modal -->
                              <div class="modal fade" id="modalrec" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" ><b>Crear receta</b></h5>
                                    </div>
                                    <div class="modal-body">
                                    <div id="cuerpo"></div> 
                                    <div class="col-xs-12">
                                        <label class="labels" style="float: left;">Rendiemiento ideal <i class="fa fa-info-circle" id="ayuda2" style="cursor:pointer;"></i></label>
                                        <input type="text" class="form-control form-control-sm monto" id="rendimiento">
                                    </div>
                                    <div class="col-xs-12">
                                        <label class="labels" style="float: left;">Unidad de medida rendimiento</label>
                                        <select class="form-control form-control-sm" id="umr">
                                        </select>
                                    </div>                           
                                    </div>
                                <div class="container">
                                  <div class="row justify-content-center" id="bots">
                                 
                                  </div>
                                </div>
                                    <div class="modal-footer">
                                    </div>
                                    <div class="row ml-2">
                                      <div class="col-sm-12">
                                        <h6 id="help2" hidden>El rendimiento ideal, representa la cantidad que se debe preparar del producto con los ingredientes que componen su receta</h6>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                        
                        <?php if (isset($this->_error)) {
                            echo $this->_error;
                        } ?>
                        <?php if ($this->tienda[0]['modelo'] == null): ?>
                            <div>
                              <img width="8%" height="8%" style="float: right;" src="<?php $model=strtolower($this->tienda[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $this->tienda[0]['tienda']; ?>.png" class="img-responsive" alt="">
                            </div>
                        <?php endif ?>
                        
                        
                        <div class="well">
                        <input type="hidden" name="idudn" id="idudn" value="<?php echo $this->tienda[0]['idU']; ?>">
                        
                        
                                               
                        </div>
                        <center>
    <div id="load" hidden>
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

                        <div style="margin-bottom: 5%;" class="" id="tablaoculta" hidden>
                          <div class="dataTable_wrapper " >
                             <div class="col-sm-12 table-responsive">
                             <ul class="nav nav-tabs" role="tablist">
                              <li class="active nav-item"><a data-toggle="tab" href="#provta" class="nav-link" id="pventa">Productos de venta </a></li>
                              <li class="nav-item"><a data-toggle="tab" href="#procomp" class="nav-link" id="pcompra">Productos semi terminados <o data-toggle="tooltip" data-placement="top" title="Click para ver informacion referente a los productos semi terminados"><i data-toggle="modal" data-target="#modalhelp"  id="ayuda1"  class="fa fa-info-circle" style="font-size: 18px;"></i></o></a>
                                    
                                  
                                </li>
                            </ul>
                            </div>
                            <div class="tab-content">
                              <div id="provta" class="tab-pane fade in active mt-3" role="tabpanel">
                                  <table id="tablaproduct" class="table table-sm table-striped table-bordered table-hover" >
                                      <thead class="theadH">
                                          <tr>
                                              <th><center>#</center></th>
                                              <th><center>Codigo</center></th>
                                              <th><center>Nombre</center></th>
                                              <th><center>Costo</center></th>
                                              <th><center>%Costo</center></th>
                                              <th><center>PVP</center></th>
                                              <th><center>Receta</center></th>
                                          </tr>
                                      </thead>
                                      <tbody id="cuerpo"></tbody>
                                      
                                  </table>
                              </div>
                              <div id="procomp" class="tab-pane fade in mt-3" role="tabpanel">
                                  <table id="tablaproductcomp" class="table table-sm table-striped table-bordered table-hover" >
                                      <thead class="theadH">
                                          <tr>
                                              <th><center>#</center></th>
                                              <th><center>Codigo</center></th>
                                              <th><center>Nombre</center></th>
                                              <th><center>Costo</center></th>
                                              <th><center>Receta</center></th>
                                          </tr>
                                      </thead>
                                      <tbody id="cuerpo"></tbody>
                                      
                                  </table> 
                              </div>
                            </div>
                                       
                                </div>
                                
                            </div>
                            
                        </div>
                        <center><div id="mensaje" hidden><img width="45px" height="45px" src="http://localhost/COCAI/public/img/check1.gif" alt="exito"/></div></center>
                             
                        <div class="" id="recetasysubs">
                          
                          <div class="dataTable_wrapper " >
                            <h5 style="background: #ddd; text-align: center; margin-bottom: 5px; width: 88%; margin-left: 6%" id="titulo2"></h5>
                             <div class="col-sm-12 table-responsive">    
                              <div class="container">
                            

                                <table id="tablarecetario" class="display table table-sm table-striped table-bordered table-hover" >
                                  <thead class="theadH">
                                      <tr>
                                          <th><center>Codigo</center></th>
                                          <th><center>Ingrediente</center></th>
                                          <th><center>Cantidad</center></th>
                                          <th><center>U/M</center></th>
                                          <th><center>Costo</center></th>
                                          <th><center>Acciones</center></th>

                                      </tr>
                                  </thead>
                                  <tbody id="cuerpo_r"></tbody>
                                  
                              </table>
                              
                              <div class="container">
                              <div class="row justify-content-center">
                                  <div class="col-3">
                                      <button class="btn btn-sm btn-outline-primary filtro" value="1" id="btnagregar" data-toggle="modal" data-target="#modaling">Agregar productos</button>
                                      <a href="<?php echo BASE_URL; ?>inventario/stockE/<?php echo $this->tienda[0][0]; ?>" class="btn btn-sm btn-outline-primary filtro">Finalizar</a>
                                  </div>                                  
                                </div>
                              </div>
                              <div class="container">
                                <div class="row d-flex justify-content-start ml-3 mx-3 pl-1">
                                  <div class="col-12" id="costot">
                                    
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>     
                        </div>
                            <!--<div id="subreceta" class="tab-pane fade">
                              <h3>Sub recetas</h3>
                              <p>tabla con las subrecetas</p>
                            </div>
                            <div id="menu2" class="tab-pane fade">
                              <h3>Menu 2</h3>
                              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
                            </div>
                            <div id="menu3" class="tab-pane fade">
                              <h3>Menu 3</h3>
                              <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                            </div>-->


                        </div>


                        <!-- Modal Confirmacion para eliminar ingredientes-->
                            <div class="modal fade " id="modaldelete" role="dialog">
                              <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" ><b id="t">Eliminar ingrediente</b></h5>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button> 
                                  </div>
                                  <div class="modal-body" id="cuerpodelete">                                    
                                  </div>
                                  <div class="modal-footer" id="botones">
                                    
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                         <!-- fin de la modal-->

                         <!-- Modal informacion sobre el modulo-->
                            <div class="modal fade " id="modalhelp" role="dialog">
                              <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" ><b id="t">Informacion sobre los productos de inventario</b></h5>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button> 
                                  </div>
                                  <div class="modal-body" id="cuerpodelete">
                                    <h5>Los productos semi terminados son aquellos productos producidos en tienda, que contienen una receta compuesta por uno o mas ingredientes y a su vez estos productos semi terminados pueden formar parte de la receta de otro producto semiterminado o de productos de venta.</h5>                                    
                                  </div>
                                  <div class="modal-footer" id="botones">
                                      <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Aceptar</button> 
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                         <!-- fin de la modal-->
               

                         <!-- MODAL DEL LA FUNCION AGREGAR DE LOS PRODUCTOS -->
                <div class="modal fade" id="modaling" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                      <div class="modal-title" ><h3><o id="titulocard">Asignacion de productos al agrupado</o> <?php $ti=strtolower(str_replace('(PTY)', '', $this->mercancia[0]['producto'])); echo "[".ucwords($ti)."]"; ?></h3></div>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      </div>
                        <div class="modal-body">
                          <input type="hidden" id="fam" value="<?php echo $this->mercancia[0]['familia_id']; ?>">
                          <input type="hidden" name="idrece" id="idrece" value="<?php echo $this->mercancia[0]['receta_id']; ?>">
                          <input type="hidden" name="mercancia_id" id="mercid" >
                          <input type="hidden" name="idproductosel" id="idproduct" >
                          <input type="hidden" name="iding" id="iding" value="<?php echo $this->mercancia[0]['idpr'] ?>">
                                
                          
                          <div class="dataTable_wrapper " >
                              <div class="col-sm-12 table-responsive">
                                  <table id="tablafiltraje" class="display table table-sm table-striped table-bordered table-hover" >
                                    <thead class="theadH">
                                        <tr>
                                            <th>Codigo</th>
                                            <th>Ingrediente</th>
                                            <th>Precio Unitario</th>
                                            <th>Acción</th>
                                        </tr>
                                    </thead>
                                    <tbody id="cuerpo_i"></tbody>
                                </table>     
                              </div>     
                          </div>
                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                  </div> 
                </div>

                 <!-- MODAL DEL LA FUNCION AGREGAR DE LOS PRODUCTOS -->
                <div class="modal fade" id="modaling2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <div class="modal-title" id="enunciado2"></div>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <div class="modal-body">                                

                                <div class="dataTable_wrapper " >
                             <div class="col-sm-12 table-responsive">    
                                <table id="tablasubs" class="display table table-sm table-striped table-bordered table-hover" >
                                  <thead class="theadH">
                                      <tr>
                                          <th><center>Codigo</center></th>
                                          <th><center>Ingrediente</center></th>
                                          <th><center>Cantidad</center></th>
                                          <th><center>U/M</center></th>
                                          <th><center>Precio Unitario</center></th>
                                      </tr>
                                  </thead>
                                  <tbody id="cuerpo_r2"></tbody>  
                              </table>
                            </div>
                          </div>     
                        </div>
                        <div class="modal-footer">
                          <button data-dismiss="modal" type="button" class="btn btn-sm btn-outline-primary">Cerrar</button>
                        </div>
                        
                    </div>
                </div>

                  </div>
                              <!-- Modal cantidad x ingrediente-->
                              <div class="modal fade mcant" id="mcant" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" ><b id="tmcant"></b></h5>
                                    </div>
                                    <div class="modal-body">
                                    <div id="cuerpoagregar"></div>
                                        <div class="form-group">
                                          <label class="form-control-label">Cantidad:</label>
                                          <input id="canti" class="form-control monto" placeholder="cantidad"  title="cantidad por ingrediente" >
                                        </div>
                                        <div class="form-group">
                                          <label class="form-control-label">Unidad de medida:</label>
                                          <input type="text" id="unidadmedf"   class="form-control" readonly="">
                                          <input type="hidden" id="unidadmed" name="unidadmed"  class="form-control">
                                        </div>
                                        
                                    </div>
                                    <div class="modal-footer justify-content-center" id="bot">
                                      
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <!-- fin modal -->
                              
                              
                        

                              
                              
                              
                
                </div>
              </div>
        </div>
</div>
</div>
                            
</body>

</div>



<!-- Autocomplete -->

</html>
