<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
    <input type="hidden"  id="valore" value="0">
    <input type="hidden"  id="valore2" value="0">
    <div id="page-wrapper">
        <div class="">

            <div class="row">
                <div class="col-lg-12">
                    <!-- <div class="col-sm-6">
                        <h4 class="page-header" style="font-family: Times New Roman, Times, serif;">Lista de productos de la empresa</h4>
                    </div> 
                       <div class="col-sm-offset-1">
                            <img style="margin-left:0%;" src="<?php echo PUBLIC_URL;?>img\<?php echo $this->sm[0]['modelo']; ?>.png" class="img-responsive" alt="modelo">
                        </div> -->

                    <div class="card-block">
                        <div class="card cardH">
                            <form action="<?php echo BASE_URL;?>inventario/insertasignacion" method="post" accept-charset="utf-8" id="form-asignar">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="active nav-item"><a data-toggle="tab" href="#home" class="nav-link" id="info">Info <i class="fa fa-info-circle"></i></a></li>
                                <?php  #print_r($this->datos);
                                    for ($i=0; $i < count($this->modelo); $i++) { 
                                        echo '<li class="nav-item pestanias" id="'.$this->idm[$i].'"><a data-toggle="tab" role="tab" class="nav-link" href="#n'.$this->idm[$i].'">'.$this->modelo[$i].'</a></li>';
                                        
                                    }
                                ?>
                            </ul>
                            <div class="tab-content">
                                <input type="hidden" id="idmodel" name="idmodel">
                                <div id="home" class="tab-pane fade in active" role="tabpanel">
                                    <br>
                                <div class="form-group col-sm-12">
                                  <h5><p>Seleccione la marca a la que pertenece la unidad de negocio, a la cual desea asignar los productos.</p></h5>
                                </div>
                                </div>
                                <div class="row d-flex justify-content-center">
                                                  <label class="custom-control custom-radio radios" hidden>
                                                    <input type="radio" class="custom-control-input" name="asignacion" value="1" id="radiomodelo">
                                                    <span class="custom-control-indicator"></span>
                                                    <span class="custom-control-description" style="line-height: 1.8;">Aplicar a todo el modelo <o id="modelname"></o></span>
                                                  </label>
                                                  <label class="custom-control custom-radio radios" hidden>
                                                    <input type="radio" class="custom-control-input" name="asignacion" value="2" id="radiotiendas">
                                                    <span class="custom-control-indicator"></span>
                                                    <span class="custom-control-description" style="line-height: 1.8;">aplicar a <o id="especific">tienda especifica </o></span>
                                                  </label>
                                                </div>
                                
                                <?php
                                for ($l=0; $l < count($this->modelo); $l++) { 
                                    echo '<div id="n'.$this->idm[$l].'" class="tab-pane fade in">
                                            <br>
                                            
                                                

                                            <div class="col-sm-3 xtienda"  hidden>
                                                    <label class="control-label" style="float: left;">Unidada de negocio</label>
                                                    <div class="input-group">
                                                    <select id="AT'.$this->idm[$l].'" class="form-control form-control-sm AT"> 
                                                    <option value="" selected>Seleccione...</option>  
                                                    
                                                      
                                            ';
                                    for ($j=0; $j < count($this->datos); $j++) { 
                                        if ($this->modelo[$l] == $this->datos[$j]['modelo']) {
                                            echo '<option value="'.$this->datos[$j]['idU'].'">'.$this->datos[$j]['nombre'].'</option>
                                                  
                                                 ';  
                                        } 
                                    }
                                    echo '</select><span class="input-group-btn">
                                                    <button class="btn btn-sm btn-outline-primary continue" type="button" id="continue'.$l.'" >Continuar</button>
                                                    </span></div> </div></div>';

                                }
                                ?>
                                
                                
                                <div class="d-flex flex-row-reverse" style="margin-bottom: 0px;">
                                    <div class="col-sm-3">
                                       <h4 class="nombretienda" id="nombretienda"></h4>
                                    </div>
                                </div>
                                
                                <div class="col-sm-12" id="tabs2" hidden>
                             <ul class="nav nav-tabs" role="tablist">
                              <li class="active nav-item"><a data-toggle="tab" href="#provta" class="nav-link" id="pventa">Productos de venta </a></li>
                              <li class="nav-item"><a data-toggle="tab" href="#procomp" class="nav-link" id="pcompra">Productos de inventario <o data-toggle="tooltip" data-placement="top" title="Click para ver informacion referente a los productos de inventario"><i data-toggle="modal" data-target="#modalhelp"  id="ayuda1"  class="fa fa-info-circle" style="font-size: 18px;"></i></o></a>
                                    
                                  
                                </li>
                            </ul>
                            </div>
                                <br>
                            <div class="tab-content">
                                <center>
                                    <div id="loading" hidden>
                                        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                    </div>
                                </center>
                              <input type="hidden" id="botoncontinuar">
                            <div id="provta" class="tab-pane fade in active mt-3" role="tabpanel">
                                <div class="row">
                                <div class="col-sm-7 tablas"  hidden>
                                    <div class="dataTable_wrapper " >
                                        <div class="col-sm-12 table-responsive" style="padding: 0px">
                                            <table id="tablaproduct2" class="table table-sm table-bordered table-hover table-striped">
                                                <thead class="theadH">
                                                    <tr>
                                                        <th colspan="5" style="border-bottom: none"><center>PRODUCTOS NO ASIGNADOS</center></th>
                                                    </tr> 
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Codigo</th>
                                                        <th>Producto</th>
                                                        <th>Clasificacion</th>
                                                        <th>Asignar</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="bodyt2"></tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="alert alert-success col-sm-10 offset-1 exitofin" style="position: absolute; z-index: 100;" hidden>
                                    <center><h4><b>Los productos marcados han sido asignados a <o class="nombretienda"></o></b></h4></center>
                                </div>
                                <div class="col-sm-5 tablas" hidden>
                                    <div class="dataTable_wrapper" >
                                        <div class="col-sm-12 table-responsive" style="padding: 0px">
                                            <table id="tablapv" class="table table-sm">
                                                <thead class="theadH">
                                                    <tr>
                                                        <th colspan="5" style="border-bottom: none"><center class="proasignados">PRODUCTOS ASIGNADOS</center></th>
                                                    </tr>
                                                    <tr>
                                                        <th>Producto</th>
                                                        <th>Desasignar</th>
                                                        <th>id</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="boditablita">
                                                </tbody>
                                            </table>
                                            
                                        </div>
                                    </div>
                                    <table class="table table-sm table-bordered table-striped mt-3">
                                                <tbody id="bodytablapro">
                                                </tbody>
                                            </table>
                                    <div class="d-flex justify-content-center">
                                        <button type="button" data-toggle="tooltip" data-placemente="bottom" title="Asginar estos productos a la tienda seleccionada" class="btn btn-sm btn-outline-primary " id="asignar2" disabled hidden>Guardar</button>
                                    </div>
                                    <div class="d-flex justify-content-center">
                                        <button type="button" data-toggle="tooltip" data-placemente="bottom" title="Asginar estos productos a la tienda seleccionada" class="btn btn-sm btn-outline-primary " id="asignar2M" disabled hidden>Guardar</button>
                                    </div>
                                    
                                </div>
                                
                                </div>
                            </div>

                            <div id="procomp" class="tab-pane fade in active mt-3" role="tabpanel">
                                <input type="hidden" id="idempresa" name="idempresa" value="<?php echo $this->datos[0]['empresa_id']; ?>">
                                <input type="hidden" name="idti" id="idti">
                                <div class="row">
                                <div class="col-sm-7 tablas"  hidden>
                                    <div class="dataTable_wrapper " >
                                        <div class="col-sm-12 table-responsive" style="padding: 0px">
                                            <table id="tablaproduct" class="table table-sm table-bordered table-hover table-striped">
                                                <thead class="theadH">
                                                    <tr>
                                                        <th colspan="5" style="border-bottom: none"><center>PRODUCTOS NO ASIGNADOS</center></th>
                                                    </tr>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Codigo</th>
                                                        <th>Producto</th>
                                                        <th>Clasificacion</th>
                                                        <th>Asignar</th>
                                                        <th>id</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="bodyt"></tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="alert alert-success col-sm-10 offset-1 exitofin" style="position: absolute; z-index: 100;" hidden>
                                    <center><h4><b>Los productos marcados han sido asignados a <o class="nombretienda"></o></b></h4></center>
                                </div>
                                <div class="col-sm-5 tablas " hidden>
                                    <div class="dataTable_wrapper " >
                                        <div class="col-sm-12 table-responsive" style="padding: 0px">
                                            <table id="tablapi" class="table table-sm">
                                                <thead class="theadH">
                                                    <tr>
                                                        <th colspan="5" style="border-bottom: none"><center class="proasignados">PRODUCTOS ASIGNADOS</center></th>
                                                    </tr>
                                                    <tr>
                                                        <th>Producto</th>
                                                        <th>Desasignar</th>
                                                        <th>id</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="boditablita2">
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <table class="table table-sm table-bordered table-striped mt-3">
                                                
                                                <thead class="theadH">
                                                </thead>
                                                <tbody id="bodytabla2">
                                                </tbody>
                                            </table>
                                    <div class="d-flex justify-content-center">
                                        <button type="button" data-toggle="tooltip" data-placemente="bottom" title="Asginar estos productos a la tienda seleccionada" class="btn btn-sm btn-outline-primary" id="asignar" disabled hidden>Guardar</button>
                                    </div>
                                    <div class="d-flex justify-content-center">
                                        <button type="button" data-toggle="tooltip" data-placemente="bottom" title="Asginar estos productos al modelo seleccionado" class="btn btn-sm btn-outline-primary" id="asignarM" disabled hidden>Guardar</button>
                                    </div>
                                    
                                </div>
                                
                                </div>
                            </div>

                        </div>
                                
                              </div>
                              <!-- Modal -->
                            <div class="modal fade" id="modaldelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="modtitle"></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body" id="modbody">
                                    
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal" id="mcancelar">Cancelar</button>
                                    <button type="button" class="btn btn-sm btn-outline-primary" id="modcontinuar">Continuar</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- Modal informacion sobre el modulo-->
                            <div class="modal fade " id="modalhelp" role="dialog">
                              <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" ><b id="t">Informacion sobre los productos de inventario</b></h5>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button> 
                                  </div>
                                  <div class="modal-body" id="cuerpodelete">
                                    <h5>Los productos de inventario son aquellos productos comprados o producidos en tienda, que van a ser utilizados para armar una receta. Esta receta podra ser utilizada por cualquier producto de venta o por un producto de inventario producido en tienda que este compuesto por otros productos de inventario.</h5>                                    
                                  </div>
                                  <div class="modal-footer" id="botones">
                                      <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Aceptar</button> 
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                         <!-- fin de la modal-->
                              </form>
                        </div>
                    </div>
                    <div class="card-block">
                        <div class="card">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
            <!-- /.col-lg-12 -->
                    </div>
                </div>
            <!-- /.row -->
            </div>
        <!-- /.container-fluid -->
        </div>
    <!-- /#page-wrapper -->
    <!-- no borrar -->
    </div>
    <script>
        $(document).ready(function() {
            $('#info').trigger('click');
        });
    </script>