<style type="text/css" media="screen">
    .control-label{
        margin-bottom: 0px;
    }     
</style>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
<div id="page-wrapper">
            <div class="">

                <div class="row">
                    <div class="col-lg-12">
                    <div class="card cardH">
                      <?php $hoy = date('Y-m-d') ?>
                      <form id="history" class="form-horizontal" role="form"  action="<?php echo BASE_URL; ?>inventario/tomaInventario/"  method="post">
                      <input type="hidden" id="hoy" value="<?php echo $hoy; ?>">
                      <input type="hidden" name="tipe" id="tipe" value="">                      
                      <input type="hidden" name="unidad_n" id="unidad_n" value="">                      
                        <?php if (isset($this->mercancia[0]['tienda'])) {?>
                          <div class="card-header" hidden>
                              <center><h4 ><o id="titulocard">Carga de inventario</o> <?php $ti=strtolower(str_replace('(PTY)', '', $this->mercancia[0]['tienda'])); echo "[".ucwords($ti)."] Sub-modelo ".$this->mercancia[0]['subM'];  ?></h4></center>
                            </div>
                          
                          <div class="card-block">
                            <div class="row d-flex flex-wrap">
                                <div class="col-11">
                                    <h4 class="page-header" style="font-family: Times New Roman, Times, serif; text-align: center; background: #337ab7; color: white;">Almacen <?php echo str_replace('IVSS', 'principal', $this->mercancia[0]['tienda']); ?></h4>
                                </div>
                            
                                <div class="col-1 d-flex justify-content-end">
                                    <img  style="margin-left:0%;" src="<?php $model=strtolower($this->mercancia[0]['modelo']); echo PUBLIC_URL;?>img\IVSS.png" class=" hidden-xs" alt="modelo">
                                </div>
                            </div>
                            <div class="card-block" style="padding-top: 0px">
                              <input type="hidden" id="valorinic">
                              <input type="hidden" id="procesados">

                    <div id="" class="form-group row ml-3">
                      <div class="col-xs-12">
                        <h4 class="ml-3" style="background: #337ab7; color: white; text-align: center">Tipo de inventario</h4>
                          <label class="radio-inline ml-3" for="inicial" id="labelini" hidden><input type="radio" name="optradio" class="radiostipo" id="inicial"> Inventario inicial</label>
                          <label class="radio-inline ml-3 otros" for=""><input type="radio" name="optradio" class="radiostipo" id="final"> Cierre de mes</label>
                          <label class="radio-inline ml-3 otros" for=""><input type="radio" name="optradio" class="radiostipo" id="otro"> Otro</label>
                      </div>
                    </div>
                    <div id="divcompleto" class="form-group row ml-3" hidden>
                      <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2" id="tt" hidden>
                          <label class="labels" for="">Tipo de inventario</label><span class="fa fa-remove" style="color: red; float: right;" data-toggle="tooltip" data-placement="top" title="La carga de inventario mensual debe ser realizada el ultimo dia de cada mes" id="error" hidden></span>
                            <select class="form-control form-control-sm tipo_inv" name="tipo_inventario" id="tipo_inventario">
                            </select>
                      </div>
                      <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
                          <label class="labels"  for="">Fecha <o id="fini"></o></label>
                            <input class="form-control form-control-sm" name="fecha_ini" id="fecha_ini" type="date">
                      </div>
                      <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2" id="ffin" hidden>
                          <label class="labels"  for="">Fecha final</label>
                            <input class="form-control form-control-sm test" name="fecha_fin" id="fecha_fin" type="date" data-toggle="tooltip" data-placement="bottom" title="el valor debe ser posterior o igual a la fecha de inicio">
                      </div>
                    </div>
                    <div id="botn" hidden>
                      <div class="row d-flex justify-content-center">
                          <div class="col-xs-12 col-sm-1">
                            <input  type="button" class="btn btn-sm btn-outline-primary"  id="continuar" value="Continuar">
                          </div>          
<!--                           <div class="col">
                            <input  type="button" class="btn btn-sm btn-outline-primary"  id="excel" value="Imprimir">
                          </div> -->
                      </div>
                      <div class="row d-flex justify-content-start ml-3">
                        <div class="export" class="col-sm-1" style="margin-top: -5px;" hidden>
                            <input id="exportarExcel" data-toggle="tooltip" data-placement="top" type="image" style="cursor: hand; cursor: pointer; margin-left: 5px;" title="Exportar a excel formato de toma de inventario" type="image" width="35px" height="35px" class="img" src="<?php echo PUBLIC_URL; ?>img/excel.png">
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 checkbox export" hidden>
                          <label class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" name="checkcero" checked>
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description" style="line-height: 1.8;">Exportar solo los productos con existencia real en cero</span>
                          </label>
                          </div>
                        </div>
                    </div>
                  </div>  
                  </form> 
                        <?php }else{?>
                            <center class="mt-3"><h3>Esta tienda no tiene productos de inventario asignados.</h3>
                            <h5>Por favor Asigne los productos correspondientes para poder realizar la carga de inventarios</h5></center>
                        <?php } ?>
                            
                

                        
                            <center><div id="check" hidden><img width="45px" height="45px" src="http://localhost/COCAI/public/img/check1.gif" alt="exito"/></div></center>
                            <div class="alert alert-success" id="actualizado" hidden>
                                <center><h4>El inventario de fecha: <o id="np"></o> ha sido Cargado con exito </h4><br>
                                <h6 id="existencaactualizada" hidden>La existencia de los productos ah sido actualizada</h6></center>
                            </div>
                            <div class="alert alert-danger" id="faltaxcargar" hidden>
                                <a class="close" href="#" id="cerraralert"><i class="fa fa-close"></i></a>
                                <center><h4>Existe al menos un producto sin existencia real cargada.</h4><br>
                                <h6>Por favor verifique e intente nuevamente</h6></center>
                            </div>

                            <div class="modal fade " id="alerta2" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <div id="t2">Error!</div>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body" >

                                               <div id="cuerpo2"></div>
                                            </div>
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Aceptar</button>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->


                            <div id="tablita" hidden>
                            <?php $i = 1; ?> 
                            <div class="dataTable_wrapper">
                             <div class="col-sm-12 table-responsive">
                                       <table class="table table-sm table-striped table-bordered table-hover" id="tablamercancia">
                                        <thead class="theadH">
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th >Producto</th>
                                                <th >Familia</th>
                                                <th >Exist. teorica</th>
                                                <th >Exist. real</th>
                                                <th >Diferencia</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table> 

                                    <br>
                                                
                                     <!-- The Modal -->
                                      <div class="modal fade" id="modalreal">
                                        <div class="modal-dialog modal-sm">
                                          <div class="modal-content">
                                          
                                            <!-- Modal Header -->
                                            <div class="modal-header">
                                              <h5 class="modal-title" id="mtitle"></h5>
                                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            
                                            <!-- Modal body -->
                                            <div class="modal-body">
                                                <div id="" class="form-group row ml-1 mr-1">
                                                    <div class="col-xs-12" id="compra" hidden>
                                                      <label class="labels"  for="">Cantidad de <o id="cant1"></o></label>
                                                        <input type="text" class="form-control form-control-sm monto" name="cantidad1" id="cantidad1" placeholder="ej: 1.000,0000">
                                                    </div>
                                                    <div class="col-xs-12" id="consumo" hidden>
                                                      <label class="labels"  for="">Cantidad de <o id="cant2"></o></label>
                                                        <input type="text" class="form-control form-control-sm monto" name="cantidad2" id="cantidad2" placeholder="ej: 1.000,0000">
                                                    </div>
                                                    <div class="col-xs-12">
                                                      <label class="labels"  for="">Cantidad de <o id="cant3"></o></label>
                                                        <input type="text" class="form-control form-control-sm monto" name="cantidad3" id="cantidad3" placeholder="ej: 1.000,0000">
                                                    </div>
                                                    <div class="col-xs-12 mt-3">
                                                        <textarea class="form-control form-control-sm" rows="3" cols="200" name="comentario" id="comentario" placeholder="Observaciones.."></textarea>
                                                    </div>
                                                    <input type="hidden" id="idus">
                                                    <input type="hidden" id="idup">
                                                    <input type="hidden" id="iduc">
                                                    <input type="hidden" id="idpro">
                                                    <input type="hidden" id="idinve">
                                                </div>
                                            </div>
                                            
                                            <!-- Modal footer -->
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
                                              <button type="button" class="btn btn-sm btn-outline-primary" id="guardarm">Guardar</button>
                                            </div>
                                            
                                          </div>
                                        </div>
                                      </div>       
                                    
                                    <!-- <div class="container">
                                        <div class="row ">
                                            <div class="col-sm-12 d-flex justify-content-center">
                                        <button type="button" style="border-radius: 5px; width: 120px; margin-left: 15px" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#produ"> 
                                            <font size="2"><b>Agregar &nbsp;</b>
                                                <span class="fa fa-plus"></span>
                                            </font>
                                        </button>
                                            </div>
                                        </div>
                                    </div> -->
                                     <!-- MODAL DEL LA FUNCION EDITAR LOS PRODUCTOS -->
                <div class="modal fade" id="prodUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div id="enunciadoU"></div>
                                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form action="<?php echo BASE_URL;?>inventario/update" method="post" accept-charset="utf-8">
                            <div class="modal-body">
                                <!-- <input type="text" name="modelo" id="m" hidden value="<?php echo $this->pro[0]['idmodelo'];?>">
                                <input type="text" name="sub_modelo" id="sm" hidden value="<?php echo $this->pro[0]['sub_modelo_id'];?>"> -->
                                <input type="text" name="idT" id="idT" hidden value="<?php echo $this->mercancia[0]['idT'];?>">
                                <input type="text" name="idP" id="idP" hidden >
                                <input type="text" name="tipo" id="type">

                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="control-label">Codigo</label>
                                        <input style="cursor: not-allowed" type="text" class="form-control form-control-sm codigop" id="codi" name="codigo" readonly="">
                                    </div>
                                    <div class="col-sm-1" id="glyphicon"></div>
                                    <div class="col-sm-3">
                                        <label class="control-label">Codigo anterior</label>
                                        <input style="cursor: not-allowed" type="text" class="form-control form-control-sm" name="codigo_tcr" id="c_tcr" readonly>
                                    </div>
                                    <div class="col-sm-3 col-sm-">
                                        <label class="control-label">status</label>
                                        <select name="status" id="status" class="form-control form-control-sm" required> 
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="control-label">Nombre</label>
                                        <input type="text" class="form-control form-control-sm" name="nombre" id="nombre" required>
                                    </div>
                                    <div class="col-sm-1" id="glyphi"></div>
                                    <div class="col-sm-3">
                                        <label class="control-label">Marca</label>
                                        <input type="text" class="form-control form-control-sm" name="marca" id="marca">
                                    </div>
                                    <div class="col-sm-3 col-sm-">
                                        <label class="control-label">Clasificacion</label>
                                        <select name="familia_id" id="familias" class="form-control form-control-sm" required> 
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="control-label">Precio unitario</label>
                                        <input type="text" class="form-control form-control-sm precios" name="precio_unitario" id="pU"  required placeholder="0,00">
                                    </div>
                                    
                                    <div class="col-sm-3 ">
                                        <label class="control-label">Stock minimo <o class="abrevia"></o> </label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmin" id="stockmin">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="control-label">Stock maximo <o class="abrevia"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmax" id="stockmax">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="control-label">Existencia <o class="abrevia"></o></label>
                                        <input style="cursor: not-allowed" type="text"  class="form-control form-control-sm monto" name="existencia" id="existencia" readonly="" title="Se actualiza al cargar las remisiones y/o reposicion de mercancia">
                                    </div>
                                </div>
                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="control-label">Unidad de compra</label>
                                        <select name="unidad_medida_co" class="form-control form-control-sm" id="unidad_medida_co" required>
                                        </select>
                                    </div>   
                                    <div class="col-sm-3">
                                        <label class="control-label">Unidad de presentacion</label>
                                        <select name="unidad_medida_pr" id="unidad_medida_pr" class="form-control form-control-sm" required>
                                        </select>
                                    </div>   
                                    <div class="col-sm-3">
                                        <label class="control-label">Unidad de sistema</label>
                                        <select name="unidad_medida_si" id="unidad_medida_si" class="form-control form-control-sm" required>
                                        </select>
                                    </div> 
                                    <div class="col-sm-3 ">
                                        <label class="control-label">Contenido neto</label>
                                        <input type="text" class="form-control form-control-sm monto" name="contenidoN" id="contenidoN">
                                    </div>  

                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-3 ">
                                        <label class="control-label"><o id="abrevU"></o></label>
                                        <input type="text" class="form-control form-control-sm" name="cantidad" id="cantidad">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels" style="float: left;">Peso escurrido</label>
                                        <input type="text" class="form-control form-control-sm monto" name="pesoEs" id="pesoEs">
                                    </div>
                                </div>

                                <label class="control-label">Formulas de conversion</label>
                                        
                                    <div class="row ">
                                        <div class="col-10 offset-1">
                                            
                                                <div class="row align-items-center d-flex justify-content-center ">
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M compra <a class="secreto" onclick="infoFormula()"><i title="Ver informacion" class="fa fa-info-circle" style="cursor: hand; cursor: pointer;"></i></a></label>
                                                        <input type="text" class="form-control form-control-sm formulac" name="formulac" id="formulac">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M consumo</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulap" id="formulap">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M sistema</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulas" id="formulas">
                                                    </div>
                                                </div>
                                            
                                        </div>
                                    </div>
                                    

                                </div>
                                
                            <div class="row mt-3">
                                    <div class="col-sm-12">
                                        <h6>* La existencia se actualiza automaticamente al cargar las remisiones y/o reposicion de mercancia</h6>
                                    </div>
                                </div>
                            <div class="modal-footer">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <input type="submit" class="btn btn-primary" value="Guardar" id="botonG">
                                    </div>
                                </div>
                                
                                
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
                                    <!-- MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gr" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                      <h4 class="modal-title">Agregar Grupo</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/insert" method="post" accept-charset="utf-8">
                                                          <input type="text" name="modelo" hidden value="<?php echo $this->mercancia[0]['idmodelo']; ?>" >
                                                          <input type="text" name="submodelo" hidden value="<?php echo $this->mercancia[0]['submodelo_id']; ?>" >
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2">
                                                              <label class="control-label" style="float: left;">Orden</label>
                                                              <input type="text" class="form-control form-control-sm" name="orden" required>
                                                            </div>
                                                            <div class="col-sm-6">
                                                              <label class="control-label" style="float: left;">Nombre</label>
                                                              <input type="text" class="form-control form-control-sm" name="nombre" required placeholder="Nombre del grupo">
                                                            </div>
                                                            <div class="col-sm-3">
                                                              <label class="control-label" style="float: left;">Status</label>
                                                              <select name="status" class="form-control form-control-sm" required>
                                                                <option value="" disabled>Seleccione</option>
                                                                <option value="0">Activo</option>
                                                                <option value="1">Inactivo</option>
                                                              </select>
                                                            </div>
                                                          </div> <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" onclick="insert()"> </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                        
                                      <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gru" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                        <h4 class="modal-title">Modificar Producto</h4>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                        </button>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/update" method="post" accept-charset="utf-8">
                                                          <input type="text" hidden name="idsm" id="idSubM">
                                                          <input type="text" hidden name="idm" id="idMo">
                                                          <input type="text" hidden name="idg" id="idG">
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2" id="orden"></div>
                                                            <div class="col-sm-5" id="nombre"></div>
                                                            <div class="col-sm-3" >
                                                              <label class="control-label" style="float: left;">Status</label>
                                                              <select name="status" id="status" class="form-control form-control-sm">
                                                              <option value="" disabled>seleccione</option>
                                                              </select>
                                                            </div>
                                                          </div>
                                                          <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" > </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                                       
                                <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                    <div class="modal-dialog modal-md" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <div id="t"></div>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body" >

                                               <div id="cuerpo"></div>
                                            </div>
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
                                              <button type="button" class="btn btn-sm btn-outline-primary" id="guardaralerta">Continuar</button>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->
                                <!-- FIN DE LA MODAL DE CONFIRMACION -->
                                
                                


                                </div>
                            </div>
                            <div class="container">
                              <div class="row d-flex justify-content-center">
                                <div>
                                  <div class="col">
                                    <input  type="button" class="btn btn-sm btn-outline-primary"  id="finalizar" value="Finalizar">
                                  </div>
                                </div>
                              </div>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
</div>
</div>
</div>
</div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
    <!-- no borrar -->
    </div>