<link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">

  <style>
 /* Tooltip */
  .test + .tooltip > .tooltip-inner {
      background-color: #337ab7; 
      color: #FFFFFF; 
      border: none; 
      padding: 1px;
      font-size: 14px;
  }
  /* Tooltip on top */
  .test + .tooltip.top > .tooltip-arrow {
      border-top: 5px solid #337ab7;
  }
  /* Tooltip on bottom */
  .test + .tooltip.bottom > .tooltip-arrow {
      border-bottom: 5px solid blue;
  }
  /* Tooltip on left */
  .test + .tooltip.left > .tooltip-arrow {
      border-left: 5px solid red;
  }
  /* Tooltip on right */
  .test + .tooltip.right > .tooltip-arrow {
      border-right: 5px solid black;
  }
  .labels{
      margin-bottom: -1%;
      float: left;
    }
  </style>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
	<div id="page-wrapper">
        <div id="page-wrapper">
            <div style="margin-top: 2%;" class="container-fluid">

                <div class="row">
                    <div class="col-12 ">
                        

                        <div class="card cardH" >

                            <div class="card-header" style="padding: 5px; height: 25%">
                              <center><h3 class="page-header" style="font-family: Times New Roman, Times, serif;">Agregar productos </h3> </center>
                            </div>
                          
                          <div class="card-block">
                            <div class="row d-flex flex-wrap">
                                <!--<div class="col-6">
                                     <h4 class="page-header" style="font-family: Times New Roman, Times, serif; text-align: center">Unidad de negocio <?php echo $this->mercancia[0]['tienda'];?></h4> 
                                </div>-->
                            
                                <div class="col-12 d-flex justify-content-center">
                                    <img style="margin-left:0%;" src="<?php echo PUBLIC_URL;?>img\Corporacion multifranquicia.png" class="img-responsive" alt="modelo">
                                </div>
                            </div>

                	 <form action="<?php echo BASE_URL;?>inventario/insert" method="post" accept-charset="utf-8">
                            <input type="text" id="idT" name="idT" hidden value="<?php echo $this->idT;?>">
                                <input type="text" name="unidadS" hidden id="unidadS">

                                <div class="card" style="box-shadow: 1px;  background: #eee">
                                    <fieldset>
                                        <center><legend><label>Datos del producto</label></legend> </center>
                                <div class="form-group row d-flex justify-content-start offset-1 ">
                                        <div class="col-xs-4 col-sm-4 col-md-3">
                                            <label class="labels" style="float: left;">Codigo</label>
                                            <div class="col-1 d-flex offset-10" id="glyphicon" data-toggle="tooltip" data-placement="right" title="Este codigo esta asignado a otro producto">
                                            </div>
                                            <input type="text" class="form-control form-control-sm codigop" id="co" name="codigo" required>
                                        </div>
                                        
                                        <div class="col-xs-4 col-sm-4 col-md-3">
                                            <label class="labels" style="float: left;">Codigo anterior</label>
                                            <input type="text" class="form-control form-control-sm" name="codigo_anterior" id="c_tcr">
                                        </div>
                                </div>
                                

                                <div class="form-group row d-flex justify-content-start offset-1">
                                    <div class="col-xs-4 col-sm-4 col-md-3">
                                        <label class="labels" style="float: left;">Nombre</label>
                                        <div class="col-1 d-flex offset-10" id="glyphi" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                        </div>
                                        <input type="text" class="form-control form-control-sm" name="nombre" id="nombre" required>

                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3">
                                        <label class="labels" style="float: left;">Marca</label>
                                        <div class="col-1 d-flex offset-10" id="glyph" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                        </div>
                                        <input type="text" class="form-control form-control-sm" name="marca" id="marca" required>
                                    </div>
                                    <div class="col-xs-4 col-sm-4 col-md-3 ">
                                        <label class="labels" style="float: left;">Clasificacion</label>
                                        <select name="familia" id="familia" class="form-control form-control-sm" required> 

                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row d-flex justify-content-start offset-1">
                                    <div class="col-xs-4 col-sm-4 col-md-3">
                                        <label class="labels" style="float: left;">Peso escurrido</label>
                                        <input type="text" class="form-control form-control-sm monto" name="pesoEs" id="pesoEs">
                                    </div>
                                    
                                    <!-- <div class="col-xs-4 col-sm-4 col-md-3">
                                        <label class="labels" style="float: left;">Rendiemiento ideal</label>
                                        <input type="text" class="form-control form-control-sm monto" name="rendimientoId" id="rendimientoId">
                                    </div> -->
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 ">
                                        <label class="labels" style="float: left;">Contenido neto</label>
                                        <input type="text" class="form-control form-control-sm contneto monto" name="contenidoN" id="contenidoN" autocomplete="off" required>
                                    </div>
                                    <input type="text" id="CNtemporal" hidden>
                                </div>
                                 <div class="form-group row d-flex justify-content-start offset-1">
                                    <div class="col-xs-4 col-sm-4 col-md-3">
                                        <label class="labels" style="float: left;">Stock min</label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmin" id="stockmin" required>
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 ">
                                        <label class="labels" style="float: left;">Stock max</label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmax" id="stockmax" required>
                                    </div>
                                </div>
                                <div class="form-group row d-flex justify-content-start offset-1">
                                    <div class="col-xs-4 col-sm-4 col-md-3">
                                        <label class="labels" style="float: left;">Cantidad comprada</label>
                                        <input type="text" class="form-control form-control-sm" name="contenidoC" id="contenidoC" required>
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 ">
                                        <label class="labels" style="float: left;">Unidad de compra</label>
                                        <select name="unidad_medida_c" class="form-control form-control-sm umc" id="unidad_medida_c" required>
                                        </select>
                                    </div>

                                    <div class="col-xs-4 col-sm-4 col-md-3" id="canti" hidden>
                                        <label class="labels" style="float: left;">ud por <o id="uc"></o></label>
                                        <input type="text" class="form-control form-control-sm" name="cantidadConsumo" id="cantidadConsumo" value="1">
                                    </div>
                                    
                                    <div id="cant" class="" hidden><div class="col-xs-4 col-sm-4 col-md-3 " id="cantC"></div></div>  
                                    
                                </div>
                                <div class="form-group row d-flex justify-content-start offset-1">
                                    <div class="col-xs-4 col-sm-4 col-md-3 ">
                                        <label class="labels" style="float: left;">Precio unitario</label>
                                        <input type="text" class="form-control form-control-sm precios" name="precio_unitario" id="pU" placeholder="0,00" required>
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 ">
                                        <label class="labels" style="float: left;">Unidad Presentacion</label>
                                        <select name="unidad_medida_p" class="form-control form-control-sm ump" id="unidad_medida_pr" required>
                                        <option value="Seleccione">Seleccione...</option>
                                        </select>
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 ">
                                        <label class="labels" style="float: left;">Unidad Sistema</label>
                                        <select name="unidad_medida_s" class="form-control form-control-sm" id="unidad_medida_s" required>
                                        <option value="Seleccione">Seleccione...</option>
                                        </select>
                                    </div>
                                     
                                </div>
                                <div class="form-group row d-flex justify-content-start offset-1">
                                    <div class="col-xs-4 col-sm-4 col-md-3">
                                        <label class="labels" style="float: left;">Descripcion</label>
                                        <textarea class="form-control form-control-sm" rows="3" name="descripcion"></textarea>
                                    </div>
                                </div>
                            
                                
                                    <fieldset>
                                        <center><legend><label>Formulas de conversion</label></legend></center>
                                        
                                    <div class="row ">
                                        <div class="col-10 offset-1">
                                            <div style="background: #eee; border-top: 1px outset  #DDDDDD; border-left: 1px outset  #DDDDDD" class="card pb-3 mb-3">
                                                <div class="row align-items-center d-flex justify-content-center ">
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M compra <a style="cursor: hand;" class="secreto" onclick="infoFormula()"><i data-toggle="tooltip" data-placement="top" title="Click para informacion sobre esta formula" class="fa fa-info-circle"></i></a></label>
                                                        <input type="text" class="form-control form-control-sm formulac" name="formulac" id="formulac">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M consumo</label>
                                                        <input type="text" class="form-control form-control-sm formulap" name="formulap" id="formulap">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M sistema</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulas" id="formulas">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </fieldset>
                                </div>
                                
                                    <div class="row offset-1">
                                    <div class="col-xs-4 col-sm-4 col-md-3 checkbox">
                                        <label class="custom-control custom-checkbox">
                                          <input type="checkbox" class="custom-control-input" name="estatus">
                                          <span class="custom-control-indicator"></span>
                                          <span class="custom-control-description" style="line-height: 1.8;">Inactivo</span>
                                        </label>
                                    </div>
                                    <div class="col-xs-4 col-sm-4 col-md-4 checkbox">
                                        <label class="custom-control custom-checkbox">
                                          <input type="checkbox" class="custom-control-input" name="exento">
                                          <span class="custom-control-indicator"></span>
                                          <span class="custom-control-description" style="line-height: 1.8;">Producto exento de impuesto</span>
                                        </label>
                                    </div>
                                    <!-- <div class="col-xs-4 col-sm-4 col-md-3 checkbox">
                                        <label class="custom-control custom-checkbox">
                                          <input type="checkbox" class="custom-control-input" name="estatus">
                                          <span class="custom-control-indicator"></span>
                                          <span class="custom-control-description" style="line-height: 1.8;">Contiene Receta</span>
                                        </label>
                                    </div> -->
                                </div>

                                    </fieldset>
                    <div class="row ">
                        <div class="col-12 ">
                        
                            <div class="card mb-3 " style="background: #eee;">
                            <center><legend style="margin-bottom: -5%">Proveedor</legend></center>
                                 

                            <ul class="nav nav-tabs justify-content-end">
                            
                              <li class="nav-item">
                                <a id="dh" class="nav-link active" style="cursor: hand; cursor: pointer;"><b style="font-size: 12px;"></b><span style="padding: 1px;  font-size: 10px" class="buscador fa fa-chevron-down"></span></a>
                              </li>
                              
                            </ul>
                                <div class="form-group row d-flex justify-content-start">
                                <div class="col-12 offset-sm-0 offset-xs-0 offset-md-1">


                                    <div id="datos2" hidden>
                                        <div class="row d-flex justify-content-start "> 

                                            <div class="col-xs-2 col-sm-3 col-md-2">
                                                <label class="labels">Proveedor</label>
                                                <input id="autoC" class="form-control form-control-sm test" placeholder="filtrar por nombre" data-toggle="tooltip" data-placement="top" title="Escriba el nombre del proveedor para filtrar!">
                                                <input type="text" name="idProveedor" id="idProveedor" hidden>
                                            </div>
                                            <div class="col-xs-2 col-sm-3 col-md-2" id="codeP" >
                                                <label class="labels">Codigo P.</label>
                                                <input class="form-control form-control-sm" name="codigoP" id="codigoP" type="text">
                                            </div>

                                            <div class="col-xs-2 col-sm-3 col-md-2" id="priceP">
                                                <label class="labels">Precio</label>
                                                <input class="form-control form-control-sm precios" name="precioP" id="precioP" type="text"  placeholder="0,00">
                                            </div>

                                        <div class="row d-flex ">
                                            <div class="col-xs-2 col-sm-3 col-md-1 offset-xs-5 mt-2" >
                                                <button type="button" style="margin-left: 15px;" class="btn mt-3 btn-xs py-1 px-2 btn-outline-primary " onclick="asignacionProveedor()"> 
                                                    <font size="4"><b>
                                                        <span class="fa fa-plus"></span></b>
                                                    </font>
                                                </button>
                                            </div>
                                        </div>
                                        </div>
                                        <div class="dataTable_wrapper mt-3">
                                        <div class="col-sm-10 table-responsive">
                                          <table style="border: solid 1px;" class="table table-sm table-bordered table-striped table-striped ">
                                            <thead class="theadH">
                                              <tr>
                                                <th><center>Proveedor</center></th>
                                                <th><center>Codigo</center></th>
                                                <th><center>Precio</center></th>
                                                <th><center>Eliminar</center></th>
                                              </tr>
                                            </thead>
                                            <tbody id="columna">
                                            </tbody>
                                          </table>
                                        </div>
                                        </div>
                                    </div>    
                                </div>
                                </div>

                            </div>

                            
                        </div>
                    </div>
                            <div class="row  pt-3 mt-3">
                                <div class="col d-flex justify-content-center">
                                    <input type="submit" class="btn btn-sm btn-outline-primary" value="Guardar" id="botonG">
                                </div>
                            </div>
                            
                </div>
                <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <div id="t"></div>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>


                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpo"></div><br><br>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>   
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                

                    
            </div>
                                <script src="<?php echo PUBLIC_URL; ?>js/jquery.js"></script>
                                <script src="<?php echo PUBLIC_URL; ?>js/jquery-ui.js"></script>
                                <script>
                                    $(document).ready(function($) {
                                        $.ajax({
                                                url: BASE_URL+'/inventario/selectProveedor',
                                                type: 'POST',
                                                dataType: 'json'
                                        })
                                        .done(function(data) {
                                            //alert(data[0][0]);
                                            $( "#autoC" ).autocomplete({
                                            source: data
                                            });
                                        });
                                    });
                                </script>
                       
                     </form>
                     </div>
                     </div>

				</div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /.row -->
</div>
<!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<!-- no borrar -->
</div>
