<link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">

  <style>
 /* Tooltip */
  .test + .tooltip > .tooltip-inner {
      background-color: #337ab7; 
      color: #FFFFFF; 
      border: none; 
      padding: 1px;
      font-size: 14px;
  }
  /* Tooltip on top */
  .test + .tooltip.top > .tooltip-arrow {
      border-top: 5px solid #337ab7;
  }
  /* Tooltip on bottom */
  .test + .tooltip.bottom > .tooltip-arrow {
      border-bottom: 5px solid blue;
  }
  /* Tooltip on left */
  .test + .tooltip.left > .tooltip-arrow {
      border-left: 5px solid red;
  }
  /* Tooltip on right */
  .test + .tooltip.right > .tooltip-arrow {
      border-right: 5px solid black;
  }
  .labels{
      margin-bottom: -1%;
      float: left;
  }
  .even{
    height: 31px;
  }
  </style>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
  <input type="hidden" id="tienda" value="<?php echo $this->idT; ?>">
	<div id="page-wrapper">
        <div id="page-wrapper">
            <div class="">
                <div class="row">
                    <div class="col-12 ">
                        <div class="card cardH" >
                            <div class="card-header" style="padding: 5px; height: 25%" hidden="">
                              <center><h3 class="page-header" style="font-family: Times New Roman, Times, serif;"><o id="titulocard">Agregar productos de inventario<o/></h3> </center>
                            </div>
                          <div class="">
                            <div class="row d-flex flex-wrap">
                                <!--<div class="col-6">
                                     <h4 class="page-header" style="font-family: Times New Roman, Times, serif; text-align: center">Unidad de negocio <?php echo $this->mercancia[0]['tienda'];?></h4> 
                                </div>-->
                                <div class="col-12 d-flex justify-content-center">
                                    <img style="margin-left:0%;"  src="<?php echo PUBLIC_URL;?>img\Corporacion multifranquicia.png" class="img-responsive" alt="modelo">
                                </div>
                            </div>
                            <!-- MODAL DEL LA FUNCION ASIGNAR LOS PRODUCTOS -->
                <div class="modal fade" id="modaling" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <div class="modal-title" ><h3>Asociar productos</h3></div>
                          <button type="button" class="close cerrar" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      </div>
                        <div class="modal-body" style="padding-bottom: 0px">
                          <form action="" method="post" accept-charset="utf-8" id="form-asociar">
                          <div class="dataTable_wrapper " >
                              <div class="col-sm-12 table-responsive">
                                  <table id="tablafiltraje" class="display table table-sm table-striped table-bordered table-hover" >
                                    <thead class="theadH">
                                        <tr>
                                            <th>Codigo</th>
                                            <th>Ingrediente</th>
                                            <th>Costo</th>
                                            <th>Asociar</th>
                                        </tr>
                                    </thead>
                                    
                                    <tbody id="cuerpo_i">
                                    </tbody>
                                    
                                </table>     
                              </div>     
                          </div>
                        </div>
                        </form>
                        <div class="modal-footer" style="padding-top: 1px">
                          <button type="button" class="btn btn-sm btn-outline-secondary cerrar" data-dismiss="modal" id="bcancelar" title="Se eliminara la asociacion de tolos los productos asignados hasta ahora">Cancelar</button>
                          <button type="button" class="btn btn-sm btn-outline-primary" id="bcontinuar" title="asignar productos seleccionados">Continuar</button>
                        </div>
                    </div>
                  </div> 
                </div>

                	 <form action="<?php echo BASE_URL;?>inventario/insert" method="post" accept-charset="utf-8" role="form">
                            <input type="text" id="idT" name="idT" hidden value="<?php echo $this->idT;?>">
                                <input type="text" name="unidadS" hidden id="unidadS">

                                <div class="card" style="box-shadow: 1px;  background: linear-gradient(to top left, rgba(255,255,255,.1), rgba(100,180,255,.2));">
                                    <fieldset>
                                        <legend style="text-align: center"><label>Datos del producto de inventario</label></legend>
                            <div class="card ml-2 mr-1" id="recetasysubs" hidden style="border: solid 1px #909090; border-radius: 4px; width: 98%">
                            <div class="card-header" style="padding: 5px; height: 25%;">
                              <center><h3 class="page-header" style="font-family: Times New Roman, Times, serif;">Productos asociados</h3> </center>
                            </div>
                              <div class="dataTable_wrapper" >
                                 <div class="col-sm-12 table-responsive ml-1 " style=" padding-top: 2px">
                                  <!-- <h5 style="background: #ddd; text-align: center; margin-bottom: 5px;" id="titulo2"><b>Productos asociados</b></h5> -->
                                    <table id="tablarecetario" class="display table table-sm table-striped table-bordered table-hover" >

                                        <thead class="theadH">

                                            <tr>
                                                <th><center>Codigo</center></th>
                                                <th><center>Ingrediente</center></th>
                                                <th><center>Cantidad</center></th>
                                                <th><center>U/M</center></th>
                                                <th><center>Costo</center></th>
                                            </tr>
                                        </thead>
                                        <tbody id="cuerpo_r"></tbody>
                                    </table>
                                  </div>
                                </div>
                            </div><br>
                                <div class="form-group row d-flex justify-content-start ml-3  ">
                                        <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 ">
                                            <label class="labels" style="float: left;">Clasificacion</label>
                                            <select name="familia" id="familia" class="form-control form-control-sm familia" required> 
                                            </select>
                                        </div>
                                        <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 ">
                                            <label class="labels" style="float: left;">Sub clasificacion</label>
                                            <select name="subfamilia" id="sub_familia" class="form-control form-control-sm"> 

                                            </select>
                                        </div>
                                        <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 ">
                                            <label class="labels" style="float: left;">Tipo de producto</label>
                                            <select name="tipo_ingrediente" id="tipo_ingrediente" class="form-control form-control-sm" required>
                                              <option value="" disabled selected="">Seleccione..</option>
                                            </select>
                                        </div>
                                        <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2">
                                            <label class="labels" style="float: left;">Codigo</label>
                                            <div class="col-1 d-flex offset-10" id="glyphicon" data-toggle="tooltip" data-placement="right" title="Este codigo esta asignado a otro producto">
                                            </div>
                                            <input type="text" class="form-control form-control-sm codigop" id="co" name="codigo" required>
                                        </div>
                                        
                                        <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2">
                                            <label class="labels" style="float: left;">Codigo anterior</label>
                                            <input type="text" class="form-control form-control-sm" name="codigo_anterior" id="c_tcr">
                                        </div>
                                        
                                </div>
                                

                                <div class="form-group row d-flex justify-content-start ml-3 ">
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2">
                                        <label class="labels" style="float: left;">Nombre</label>
                                        <div class="col-1 d-flex offset-10" id="glyphi" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                        </div>
                                        <input type="text" class="form-control form-control-sm" name="nombre" id="nombre" required>

                                    </div>
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 simples asoc asociated" hidden>
                                        <label class="labels" style="float: left;">Unidad de consumo</label>
                                        <select  class="form-control form-control-sm ump" id="unidad_mp" >
                                        <option value="" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 simples asoc asociated" hidden>
                                        <label class="labels" style="float: left;">Unidad de sistema</label>
                                        <select class="form-control form-control-sm ums" id="unidad_ms" >
                                        <option value="" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 simples">
                                        <label class="labels" style="float: left;">Marca</label>
                                        <div class="col-1 d-flex offset-10" id="glyph" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                        </div>
                                        <input type="text" class="form-control form-control-sm" name="marca" id="marca" >
                                    </div>

                                     <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 ">
                                        <label class="labels" style="float: left;">Tipo de inventario</label>
                                        <select name="tipo_inventario" id="tipo_inventario" class="form-control form-control-sm" required>
                                        </select>
                                      </div>

                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 agrupado" hidden>
                                        <label class="labels" style="float: left;">Descripcion</label>
                                        <textarea class="form-control form-control-sm" rows="3" name="descripcion2"></textarea>
                                    </div>
                                    
                                </div>
                                
                                <div class="simples">
                                  <div class="form-group row d-flex justify-content-start ml-3  ">
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2">
                                        <label class="labels" style="float: left;">Stock min</label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmin" id="stockmin" placeholder="0,0000">
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 ">
                                        <label class="labels" style="float: left;">Stock max</label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmax" id="stockmax" placeholder="0,0000">
                                    </div>

                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2">
                                        <label class="labels" style="float: left;">Peso escurrido</label>
                                        <input type="text" class="form-control form-control-sm monto" name="pesoEs" id="pesoEs" placeholder="0,0000">
                                    </div>
                                  </div>
                                </div>
                                 

                              <div class="productoscompra simples" hidden>
                                  
                                

                                <div class="form-group row d-flex justify-content-start ml-3 ">
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 ">
                                        <label class="labels" style="float: left;">Contenido neto</label>
                                        <input type="text" class="form-control form-control-sm contneto monto" name="contenidoN" id="contenidoN" autocomplete="off" placeholder="0,0000">
                                    </div>
                                    <input type="text" id="CNtemporal" hidden>
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 ">
                                        <label class="labels" style="float: left;">Precio unitario</label>
                                        <input type="text" class="form-control form-control-sm precios" name="precio_unitario" id="pU" placeholder="0,0000" >
                                    </div>
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2">
                                        <label class="labels" style="float: left;">Cantidad comprada</label>
                                        <input type="text" class="form-control form-control-sm" name="contenidoC" id="contenidoC" placeholder="0,0000">
                                    </div>
                                </div>
                                
                              </div>


                                <div class="form-group row d-flex justify-content-start ml-3  simples">

                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 productoscompra simples" hidden>
                                        <label class="labels" style="float: left;">Unidad de compra</label>
                                        <select name="unidad_medida_c" class="form-control form-control-sm umc" id="unidad_medida_c" required>
                                        </select>
                                    </div>

                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2" id="canti" hidden>
                                        <label class="labels" style="float: left;">ud por <o id="uc"></o></label>
                                        <input type="text" class="form-control form-control-sm" name="cantidadConsumo" id="cantidadConsumo" value="1">
                                    </div>
                                    
                                    <div id="cant" class="" hidden><div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 " id="cantC"></div></div> 

                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 simples">
                                        <label class="labels" style="float: left;">Unidad de Consumo</label>
                                        <select name="unidad_medida_p" class="form-control form-control-sm ump1" id="unidad_medida_pr" required>
                                        <option value="Seleccione" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>
                                    
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 simples">
                                        <label class="labels" style="float: left;">Unidad de Sistema</label>
                                        <select name="unidad_medida_s" class="form-control form-control-sm umsis" id="unidad_medida_s" required>
                                        <option value="Seleccione" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>
                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 simples">
                                        <label class="labels" style="float: left;">Descripcion</label>
                                        <textarea class="form-control form-control-sm" rows="3" name="descripcion"></textarea>
                                    </div>
                                </div>
                            
                                
                                    <fieldset class="simples asoc">
                                    <legend style="text-align: center"><label>Formulas de conversion<a style="cursor: hand;" class="secreto" onclick="infoFormula()"><img class="img ml-1 mb-1" src="<?php echo PUBLIC_URL; ?>img/info.icon.png" data-toggle="tooltip" data-placement="top" title="Click para informacion sobre esta formula"></a></label></legend>
                                        
                                    <div class="row ">
                                        <div class="col-10 offset-1">
                                            <div style="border-top: 1px solid  #DDDDDD; border-left: 1px outset  #DDDDDD;" class="card pb-3 mb-3">
                                                <div class="row align-items-center d-flex justify-content-center ">
                                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 mt-3 productoscompra simples" hidden>
                                                        <label class="labels" style="float: left;">U/M compra </label>
                                                        <input type="text" class="form-control form-control-sm formulac" name="formulac" id="formulac">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 mt-3">
                                                        <label class="labels" style="float: left;">U/M consumo</label>
                                                        <input type="text" class="form-control form-control-sm formulap" name="formulap" id="formulap">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 mt-3">
                                                        <label class="labels" style="float: left;">U/M sistema</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulas" id="formulas">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </fieldset>
                            
                                    <div class="row offset-1 simples">
                                      <div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 checkbox">
                                          <label class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" name="estatus">
                                            <span class="custom-control-indicator"></span>
                                            <span class="custom-control-description" style="line-height: 1.8;">Inactivo</span>
                                          </label>
                                      </div>
                                      <div class="col-xs-4 col-sm-4 col-md-4 checkbox productoscompra simples" hidden>
                                          <label class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" name="exento">
                                            <span class="custom-control-indicator"></span>
                                            <span class="custom-control-description" style="line-height: 1.8;">Producto exento de impuesto</span>
                                          </label>
                                      </div>
                                  <!--<div class="col-xs-4 col-sm-4 col-md-3 col-lg-2 checkbox">
                                          <label class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" name="estatus">
                                            <span class="custom-control-indicator"></span>
                                            <span class="custom-control-description" style="line-height: 1.8;">Contiene Receta</span>
                                          </label>
                                      </div> -->
                                    </div>
                                </div>
                                
                                  

                                    </fieldset>
                    <div class="row productoscompra simples" hidden>
                        <div class="col-12 ">
                        
                            <div class="card mb-3 " style="background: #FFFFFF;">
                            <center><legend style="margin-bottom: -5%">Proveedor</legend></center>
                                 

                            <ul class="nav nav-tabs justify-content-end">
                            
                              <li class="nav-item">
                                <a id="dh" class="nav-link active" style="cursor: hand; cursor: pointer;"><b style="font-size: 12px;"></b><span style="padding: 1px;  font-size: 10px" class="buscador fa fa-chevron-down"></span></a>
                              </li>
                              
                            </ul>
                                <div class="form-group row d-flex justify-content-start">
                                <div class="col-12 offset-sm-0 offset-xs-0 offset-md-1">


                                    <div id="datos2" hidden>
                                        <div class="row d-flex justify-content-start "> 

                                            <div class="col-xs-2 col-sm-3 col-md-2">
                                                <label class="labels">Proveedor</label>
                                                <input id="autoC" class="form-control form-control-sm test" placeholder="filtrar por nombre" data-toggle="tooltip" data-placement="top" title="Escriba el nombre del proveedor para filtrar!">
                                                <input type="text" name="idProveedor" id="idProveedor" hidden>
                                            </div>
                                            <div class="col-xs-2 col-sm-3 col-md-2" id="codeP" >
                                                <label class="labels">Codigo P.</label>
                                                <input class="form-control form-control-sm" name="codigoP" id="codigoP" type="text">
                                            </div>

                                            <div class="col-xs-2 col-sm-3 col-md-2" id="priceP">
                                                <label class="labels">Precio</label>
                                                <input class="form-control form-control-sm precios" name="precioP" id="precioP" type="text"  placeholder="0,00">
                                            </div>

                                        <div class="row d-flex ">
                                            <div class="col-xs-2 col-sm-3 col-md-1 offset-xs-5 mt-2" >
                                                <button type="button" style="margin-left: 15px;" class="btn mt-3 btn-xs py-1 px-2 btn-outline-primary " onclick="asignacionProveedor()"> 
                                                    <font size="4"><b>
                                                        <span class="fa fa-plus" data-toggle="tooltip" data-placement="top" title="Agregar datos del proveedor"></span></b>
                                                    </font>
                                                </button>
                                            </div>
                                        </div>
                                        </div>
                                        <div class="dataTable_wrapper mt-3">
                                        <div class="col-sm-10 table-responsive">
                                          <table style="border: solid 1px;" class="table table-sm table-bordered table-striped table-striped ">
                                            <thead class="theadH">
                                              <tr>
                                                <th><center>Proveedor</center></th>
                                                <th><center>Codigo</center></th>
                                                <th><center>Precio</center></th>
                                                <th><center>Eliminar</center></th>
                                              </tr>
                                            </thead>
                                            <tbody id="columna">
                                            </tbody>
                                          </table>
                                        </div>
                                        </div>
                                    </div>    
                                </div>
                                </div>

                            </div>

                            
                        </div>
                    </div>
                            <div class="row  pt-3 mt-3">
                                <div class="col d-flex justify-content-center">
                                    <input type="button" class="btn btn-sm btn-outline-primary " value="Asociar productos" data-toggle="tooltip" data-placement="top" title="agregar elementos asociados a este producto" id="asoci" hidden>
                                    <input type="submit" class="btn btn-sm btn-outline-primary" value="Guardar" id="botonG" disabled>
                                </div>
                            </div>
                            
                </div>
                </form>
                <!-- MODAL DE ALERTA-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <div id="t"></div>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>


                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpo"></div><br><br>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>   
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->

              

                    <!-- MODAL DE AGREGAR SUB_FAMILIAS NUEVAS-->
                    <div class="modal fade " id="modalsubfamilia" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div id="t"><h6>Agregar nueva Sub-Clasificacion</h6></div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>


                                </div>
                                <div class="modal-body" >

                                   <div id="cuerpo"></div>
                                   <div class="form-group">
                                    <div class="col-sm-12">
                                      <label class="labels">Nombre de Sub-Clasificacion</label>
                                      <input type="text" id="nuevasub" class="form-control form-control-sm">
                                    </div>
                                   </div>
                                    
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" id="mcancelar">Cancelar</button>
                                  <button type="button" class="btn btn-sm btn-outline-primary" id="mcontinuar">Continuar</button>
                                </div>   
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                                

                    
            </div>
                                <script src="<?php echo PUBLIC_URL; ?>js/jquery.js"></script>
                                <script src="<?php echo PUBLIC_URL; ?>js/jquery-ui.js"></script>
                                <script>
                                    $(document).ready(function($) {
                                        $.ajax({
                                                url: BASE_URL+'/inventario/selectProveedor',
                                                type: 'POST',
                                                dataType: 'json'
                                        })
                                        .done(function(data) {
                                            //alert(data[0][0]);
                                            $( "#autoC" ).autocomplete({
                                            source: data
                                            });
                                        });
                                    });
                                </script>
                       
                     
                     </div>
                     </div>

				</div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /.row -->
</div>
<!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<!-- no borrar -->
</div>
