<!doctype html>
<html lang="us">
<head>
  <meta charset="utf-8">
  <title>jQuery UI Example Page</title>



  
</head>
<style>
  .red{
    background: blue;
  }
</style>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
<div id="page-wrapper">
            <div class="">

                <div class="row">
                    <div class="col-12 ">
                        

                        <div class="card cardH">

                            <div class="card-header" hidden>
                              <center><h3 ><o id="titulocard">Movimientos de Kardex</o> <?php $ti=strtolower($this->model[0]['udn']); echo "[".ucwords($ti)."]"; ?></h3></center>
                            </div>
                          
                          <div class="card-block">



                        
                        <?php if (isset($this->_error)) {
                            echo $this->_error;
                        } ?>
                        <?php if ($this->model[0]['modelo'] != null): ?>
                            <div>
                              <img width="12%" height="10%" style="float: right;" src="<?php $model=strtolower($this->model[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-responsive" alt="">
                            </div>
                          <?php else: ?>
                            <div>
                              <img width="8%" height="8%" style="float: right;" src="<?php $model=strtolower($this->model[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $this->model[0]['udn']; ?>.png" class="img-responsive" alt="">
                            </div>
                        <?php endif ?>
                        
                        
                        <input type="hidden" name="idudn" id="idudn" value="<?php echo $this->model[0]['idU']; ?>">

                        <fieldset>
                            
                          
                            <div id="" class="form-group row ml-3">
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3 ">
                                    <label class="labels"  for="">Fecha de incio:</label>
                                      <input class="form-control form-control-sm" name="fecha_ini" id="fecha_ini" type="date">
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3">
                                    <label class="labels"  for="">Fecha limite:</label>
                                      <input class="form-control form-control-sm test" name="fecha_fin" id="fecha_fin" type="date" disabled data-toggle="tooltip" data-placement="bottom" title="el valor debe ser posterior o igual a la fecha de inicio">
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3 ">
                                    <label class="labels" for="">Producto:</label>
                                      <select  id="products" name="productos"  class="form-control form-control-sm" disabled>
                                        <option selected disabled value="seleccione">Seleccione..</option>
                                      </select>
                                </div>
                            </div>

                             <div id="" class="form-group row ml-3">
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3 ">
                                    <label class="labels" for="">Tipo de mov.:</label>
                                      <select  id="tipoMov" name="tipoMov"  class="form-control form-control-sm" disabled>
                                        <option selected disabled value="seleccione">Seleccione..</option>
                                        <option value="131">Entradas</option>
                                        <option value="132">Salidas</option>
                                      </select>
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3">
                                      <label class="labels" for="">Motivo:</label>
                                      <select id="motivo" name="motivo" class="form-control form-control-sm" disabled>
                                        <option selected disabled value="seleccione">Seleccione..</option>
                                      </select>
                                </div>
                                
                                    
                              </div>
                                    <input type="hidden" name="mercancia_id" id="mercid" >
                                    <input type="hidden" name="idt" id="idt" value="<?php echo $this->model[0]['idU'];?>">
                                    <input type="hidden" name="status_id" id="status_id" value="126">
                            
                        </fieldset>
                        <div class="container">
                              <div class="row d-flex justify-content-center">
                                <div>
                                  <div class="col">
                                    <input  type="button" class="btn btn-sm btn-outline-primary"  id="consult" value="Consultar" disabled>
                                  </div>
                                </div>
                              </div>
                              
                            </div>
                                               
                        </div>
                        <center>
    <div id="load" hidden>
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
                                    <div class="container " hidden>
                                        <div class="row ">
                                            <div class="col d-flex justify-content-center my-3">
                                                <a href="<?php echo BASE_URL;?>inventario/facturasdecompra/<?php echo $this->model[0]['idU'];?>" class="btn btn-sm btn-outline-primary"> 
                                                    <b>Cargar factura de compra directa </b>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                        <div class="dataTable_wrapper " id="tablaoculta" hidden>
                             <div class="col-sm-12 table-responsive">
                                <table id="tablakardex" class="table table-sm table-striped table-bordered table-hover" cellspacing="0" width="100%" >
                                  <?php if (!is_null($this->model[0]['empresa_id'])): ?>
                                    <thead class="theadH">
                                      <tr>
                                          <th>Codigo</th>
                                          <th>Producto</th>
                                          <th>Grupo</th>
                                          <th>Fecha</th>
                                          <th>Tipo</th>
                                          <th>Motivo</th>
                                          <th>Cantidad</th>
                                          <th>Existencia</th>
                                          <!-- <th>Descripcion</th> -->
                                          <th>Usuario</th>
                                          <th>st</th>
                                      </tr>
                                  </thead>
                                  <?php else: ?>
                                    <thead class="theadH">
                                      <tr>
                                          <th>Tienda</th>
                                          <th>Codigo</th>
                                          <th>Producto</th>
                                          <th>Grupo</th>
                                          <th>Fecha</th>
                                          <th>Tipo</th>
                                          <th>Motivo</th>
                                          <th>Cantidad</th>
                                          <th>Existencia</th>
                                          <!-- <th>Descripcion</th> -->
                                          <th>Usuario</th>
                                          <th>st</th>
                                      </tr>
                                  </thead>

                                  <?php endif ?>
                                  <tfoot class="theadH">
                                      <tr>

                                          <th colspan="3" style="text-align:left;" >Total Entrada: <o id="entra"></o></th>
                                          <th colspan="3" style="text-align:left;" >Total Salida: <o id="sale"></o></th>
                                          <th colspan="2" ></th>
                                      </tr>
                                  </tfoot>
                                  <tbody id="cuerpo"></tbody>
                                  
                              </table>
                                       
                                </div>
                            </div>
                            



                  </div>
                </div>
              </div>
        </div>
</div>
</div>
</body>


</div>
</html>
</div>
</div>



<!-- Autocomplete -->

</html>
