<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
<div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">
                        

                        <div style="margin-top: 2%" class="panel panel-default">
                        <div class="panel-body">
                        <div class="col-sm-12">
                        <div class="col-sm-6">
                        	<img  src="<?php $model=strtolower($this->datos[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-responsive" alt="modelo">
                        </div>
                        <div class="col-sm-6">
                            	<h4  style="font-family: Times New Roman, Times, serif; margin-top: 0px; text-align: right; color: #337ab7;">Datos de la <?php echo $this->datos[0]['statusN']." #00".$this->datos[0]['idk'];?>
                            	</h4>
                            	<h4  style="font-family: Times New Roman, Times, serif; text-align: right;"><?php echo 'Destinatario: <b>'.$this->datos[0]['tiendar']."</b>";  ?></h4>
                            	<h5 style="text-align: right;">Fecha: <?php echo $this->datos[0]['fecha']." / ". $this->datos[0]['hora'] ?></h5>
                        </div>
                        </div>
                        
                        <div class="col-sm-12">
                        </div>
                            <?php $i = 1; ?>  
                            
                            
                            <div style="border: solid 1px; border-bottom: none; text-align: justify;" class="col-sm-12"> 
                                

                                    <?php foreach ($this->datos as $g): ?>
                                    	<label for="">Datos de la unidad de negocio solicitante:</label><br>
                                    	<?php echo "Unidad de negocio: ".$g['tiendae']."";?><br>
                                    	<?php echo "Rif: ".$g['rife']."";?><br>
                                    	<?php echo "Razon Social: ".$g['razon_se']."";?><br>
                                    	<?php echo "Correo: ".$g['emailue']."";?>


                                                
                                    <?php endforeach ?>

                            </div>

							<div style="border: solid 1px;  text-align: justify;" class="col-sm-12 "><br>
                            <div class="col-sm-12 table-responsive"> 
                                       <table class="table table-striped table-bordered table-hover" id="tablaGru">
                                        <thead>
                                            <tr>                                                 
                                                <th ><center>Codigo</center></th>
                                                <th ><center>Nombre<center></th> 
                                                <th ><center>Marca<center></th>
                                                <th ><center>Familia<center></th>
                                                <th ><center>Cantidad solicitada<center></th>
                                                <th ><center>Motivo<center></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                            <tr> 
                                                <td ><?php echo $g['codim'];?></td>
                                                <td style="text-align:left"><?php echo $g['producto'];?></td>
                                                <td ><?php echo $g['marca'];?></td>
                                                <td ><?php echo $g['familia'];?></td>
                                                <td ><?php echo $g['cantidad'].' '.$g['abrevpres'];;?></td>
                                                <td ><?php echo $g['motivo'];?></td>
                                            </tr>

                                        </tbody>
                                    </table> 
                                
                            </div>
                            </div>
                            <div class="col-sm-6">
                            	
                            	<h5  style="font-family: Times New Roman, Times, serif; text-align: left;"><?php echo 'Remitente: <b>'.$this->datos[0]['nombre']." ".$this->datos[0]['apellido']."</b>";  ?></h5>
                        	</div>
                        	<div class="col-sm-12">
                                    <button type="button" style="border-radius: 5px; margin-top: 2px" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#produ"> 
                                        <font size="2"><b>Procesar &nbsp;</b>
                                            <span class="glyphicon glyphicon-check"></span>
                                        </font>
                                    </button>
                            </div>
                                     <!-- MODAL DEL LA FUNCION AGREGAR DE LOS PRODUCTOS -->
                <div class="modal fade product" id="produ" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-md" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <div class="modal-title" id="enunciado"></div>
                            </div>
                            <div class="modal-body">
                            <form action="<?php echo BASE_URL;?>inventario/existenciaT/rcd" method="post" accept-charset="utf-8">
                                <input type="hidden" name="idmer" id="idmer">
                                <input type="hidden" name="idtienda" id="idtienda">
                                <input type="hidden" name="unidadS" id="unidadS">

                                
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-4">
                                        <label class="control-label" style="float: left;">Precio unitario</label>
                                        <input type="text" class="form-control" name="precio_unitario" id="pU" onkeyup="format(this)" onchange="format(this)" required placeholder="0,00">
                                    </div>
                                    
                                    <div class="col-sm-4 ">
                                        <label class="control-label" style="float: left;" >Stock minimo</label>
                                        <input type="text" class="form-control" name="stockmin" id="stockmin" readonly="">
                                    </div>
                                    <div class="col-sm-4">
                                        <label class="control-label" style="float: left;" >Stock maximo</label>
                                        <input type="text" class="form-control" name="stockmax" id="stockmax" readonly="">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-4">
                                        <label class="control-label" style="float: left;">ud. de compra</label>
                                        <select name="unidad_medida_c" class="form-control" id="unidad_medida_c" required>
                                        </select>
                                    </div>
                                    <div class="col-sm-4 ">
                                        <label class="control-label" style="float: left;">Cant. comprada</label>
                                        <input type="text" class="form-control" name="contenidoC" id="contenidoC">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-4">
                                        <label class="control-label" style="float: left;">ud. de presentacion</label>
                                        <select name="unidad_medida_p" id="unidad_medida_p" class="form-control" required>
                                        <option value="seleccione">Seleccione..</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-4 " id="contenidoneto" hidden>
                                        <label class="control-label" style="float: left;">Contenido neto</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">
                                    </div>
                                    <div class="col-sm-4" id="cantx"></div>

                                    <div class="col-sm-4 col-sm-offset-1" hidden>
                                        <label class="control-label" style="float: left;">ud. de sistema</label>
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-9">
                                        <label class="control-label" style="float: left;">Descripcion</label>
                                        <textarea rows="4" cols="50" class="form-control sty" 
                                            placeholder="motivo de la reposicion" id="message" required
                                            data-validation-required-message="Please enter your message" minlength="5" 
                                            data-validation-minlength-message="Min 5 characters" 
                                            maxlength="300" name="detalles" style="resize:none">
                                        </textarea>
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                <input type="submit" class="btn btn-primary" value="Guardar" id="botonG">
                                </div>
                                </form>
                            </div>
                            <div style="border: none" class="modal-footer">    
                            </div>
                                
                            
                        </div>
                    </div>
                </div>
                                    <!-- MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gr" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                      <h4 class="modal-title">Agregar Grupo</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/insert" method="post" accept-charset="utf-8">
                                                          <input type="text" name="modelo" hidden value="<?php echo $this->datos[0]['idmodelo']; ?>" >
                                                          <input type="text" name="submodelo" hidden value="<?php echo $this->datos[0]['submodelo_id']; ?>" >
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2">
                                                              <label class="control-label" style="float: left;">Orden</label>
                                                              <input type="text" class="form-control" name="orden" required>
                                                            </div>
                                                            <div class="col-sm-6">
                                                              <label class="control-label" style="float: left;">Nombre</label>
                                                              <input type="text" class="form-control" name="nombre" required placeholder="Nombre del grupo">
                                                            </div>
                                                            <div class="col-sm-3">
                                                              <label class="control-label" style="float: left;">Status</label>
                                                              <select name="status" class="form-control" required>
                                                                <option value="" disabled>Seleccione</option>
                                                                <option value="0">Activo</option>
                                                                <option value="1">Inactivo</option>
                                                              </select>
                                                            </div>
                                                          </div> <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" onclick="insert()"> </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                      <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gru" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                      <h4 class="modal-title">Modificar grupo</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/update" method="post" accept-charset="utf-8">
                                                          <input type="text" hidden name="idsm" id="idSubM">
                                                          <input type="text" hidden name="idm" id="idMo">
                                                          <input type="text" hidden name="idg" id="idG">
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2" id="orden"></div>
                                                            <div class="col-sm-5" id="nombre"></div>
                                                            <div class="col-sm-3" >
                                                              <label class="control-label" style="float: left;">Status</label>
                                                              <select name="status" id="status" class="form-control">
                                                              <option value="" disabled>seleccione</option>
                                                              </select>
                                                            </div>
                                                          </div>
                                                          <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" > </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->

                                        <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <div id="titulo"></div>
                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpo"></div><br><br>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>   
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                        <!-- FIN DE LA MODAL DE CONFIRMACION -->

                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
</div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
 		<!-- no borrar -->
 		</div>