<!doctype html>
<html lang="us">
<head>
  <meta charset="utf-8">
  <title>COCAI</title>
  <link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">
  <style>
    label{
      margin-bottom: -1%;
      float: left;
    }

  /* Tooltip */
  .test + .tooltip > .tooltip-inner {
      background-color: #337ab7; 
      color: #FFFFFF; 
      border: none; 
      padding: 1px;
      font-size: 14px;
  }
  /* Tooltip on top */
  .test + .tooltip.top > .tooltip-arrow {
      border-top: 5px solid #337ab7;
  }
  /* Tooltip on bottom */
  .test + .tooltip.bottom > .tooltip-arrow {
      border-bottom: 5px solid blue;
  }
  /* Tooltip on left */
  .test + .tooltip.left > .tooltip-arrow {
      border-left: 5px solid red;
  }
  /* Tooltip on right */
  .test + .tooltip.right > .tooltip-arrow {
      border-right: 5px solid black;
  }
  </style>


  
</head>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
<div id="page-wrapper">
            <div class="">

                <div class="row justify-content-center">
                    <div class="col-lg-12 ">
                        

                        <div style="margin-top: 2%" class="card cardH">
                        <div class="card-header" hidden>
                            <center><h3 ><o id="titulocard">Solicitud de remision</o> de mercancia <?php $ti=strtolower($this->datos[0]['tiendaen']); echo "[".ucwords($ti)."]"; ?></h3></center>
                        </div>
                        <div class="card-block">
                        
                        
                        <?php if (isset($this->_error)) {
                            echo $this->_error;
                        } ?>
                        <div>
                            <img width="10%" height="8%" style="float: right;" src="<?php $model=strtolower($this->datos[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-responsive" alt="modelo">
                        </div>

                                <div class="dataTable_wrapper ">
                                  <div class=" table-responsive">
                                       
                                          <table id="tablaremi" class=" table-sm table-striped table-bordered table-hover" >
                                            <thead class="theadH">
                                                <tr>
                                                    <th>Codigo</th>
                                                    <th>Ingrediente</th>
                                                    <th>Existencia</th>
                                                    <th>Min</th>
                                                    <th>Max</th>
                                                    <th>Accion</th>

                                                </tr>
                                            </thead>
                                            <tbody id="cuerpo_i"></tbody>
                                            
                                        </table>    
                                          </div>
                                          
                                  </div>


                                  <!-- Modal cantidad x ingrediente-->
                              <div class="modal fade modalcant" id="modalcant" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="tit"></h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                                    </div>
                                    <div class="modal-body">
                                    <form id="usuario" class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>inventario/insertRemision"  method="post">
                                      <input type="hidden" name="mercancia_id" id="mercid">
                                      <input type="hidden" name="tiendae" id="tiendae" value="<?php echo $this->idu;?>">
                                      <input type="hidden" name="status_id" id="status_id" value="126">

                                        <div class="form-group">
                                          <label  for="">Destinatario:</label>
                                        <select class="form-control" name="tiendar" id="tiendar" required="">
                                        <option value="" selected disabled>Seleccione..</option>
                                          <?php $cont=count($this->datos); 
                                            for ($i=0; $i < $cont ; $i++) { 
                                              echo '<option value="'.$this->datos[$i]['id'].'">'.$this->datos[$i]['nombre'].'</option>';
                                            } 
                                          ?>
                                          
                                        </select>
                                        </div>
                                        <div class="form-group">
                                          <label for="recipient-name" class="form-control-label">Cantidad:</label>
                                          <input type="text" class="form-control monto"  name="cantidadR" id="cantidadR">
                                        </div>
                                        <div class="form-group">
                                          <label for="recipient-name" class="form-control-label">Unidad de medida:</label>
                                          <select id="unidades" name="unidades"  class="form-control">
                                          </select>
                                        </div>
                                        <div class="form-group">
                                          <label for="message-text" class="form-control-label">Motivo de la solicitud:</label>
                                          <textarea class="form-control" name="descripcion" id="descripcion"></textarea>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
                                      <button class="btn btn-sm btn-outline-primary"  type="submit" class=""  id="btnguardar"><b>Enviar solicitud</b></button>
                                    </div>
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- fin modal -->

                  </div>
                </div>
              </div>
        </div>
</div>
</div>
</body>

</div>



<!-- Autocomplete -->

</html>
