<style type="text/css" media="screen">
    .labels{
        margin-bottom: 0px;
    }
    
</style>
<script>
    $(document).ready(function() {
       $.ajax({
        url: BASE_URL+'/inventario/consultfiltro/',
        type: 'POST',
        dataType: 'json'
      })
      .done(function(data) {
        var idemp = $('#tienda').val();
        if (data[0]['gr']>0) {
            load('referencia','familia2',idemp,data[0]['gr']);
            setTimeout(function(){ 
                $("#grupo option[value="+ data[0]['gr'] +"]").attr("selected",true);
            },200);
        }
        if (data[0]['fam']>0) {
            load('referencia','sub_familia',idemp,data[0]['fam']);
            setTimeout(function(){
                $("#familia2 option[value="+ data[0]['fam'] +"]").attr("selected",true);
            },2000);
        }
        if (data[0]['subf']>0) {
            setTimeout(function(){
                $("#sub_familia option[value="+ data[0]['subf'] +"]").attr("selected",true);
            },2000);
        }
      });
    });
</script>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
<div id="page-wrapper">
            <div class="">
<input type="text" name="idT" id="tienda" hidden value="<?php echo $this->mercancia[0]['idT'];?>">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                    <div class="card cardH">
                        <?php if (isset($_SESSION['idmercancia'])): ?>
                            <input type="text" id="newp" hidden value="<?php echo $_SESSION['idmercancia']; ?>">
                        <?php else: ?>
                            <input type="text" id="newp" hidden>
                        <?php endif ?>
                    
                            <div class="card-header" hidden>
                              <center><h4 ><o id="titulocard">Consulta de inventario</o> <?php $ti=strtolower(str_replace('(PTY)', '', $this->mercancia[0]['tienda'])); echo "[".ucwords($ti)."]";  ?></h4></center>
                            </div>
                          
                          <div class="card-block">
                            <div class="row d-flex flex-wrap d-flex justify-content-center mb-3">
                                <div class="alert alert-success exporting" style="position: absolute; z-index: 99;" hidden>
                              <h4>Lista de productos exportada con exito</h4>
                            </div>
                                <!--<div class="col-6">
                                     <h4 class="page-header" style="font-family: Times New Roman, Times, serif; text-align: center">Unidad de negocio <?php echo $this->mercancia[0]['tienda'];?></h4> 
                                </div>-->
                                <!-- <div class="col-xs-12 col-sm-6 d-flex justify-content-start">
                                    <div class="container ">
                                        <div class="col-sm-6 col-lg-4">
                                            <table class="table table-sm table-bordered">
                                                <thead class="theadH">
                                                    <tr>
                                                        <td colspan="2" class="font11"><center>Tipos de productos</center></td>
                                                    </tr>
                                                </thead>
                                                <?php if (isset($_SESSION['idmercancia'])): ?>
                                                <tr id="trnuevo">
                                                    <td style="background: #dff0d8; color: #dff0d8;"></td>
                                                    <td class="font11">Nuevo</td>
                                                </tr>
                                                <?php endif ?>
                                                <tr>
                                                    <td style="background: #D4E5F4; color: #D4E5F4;"></td>
                                                    <td class="font11">Agrupados</td>
                                                </tr>
                                                <tr>
                                                    <td style="background: #e1eefb; color: #e1eefb;"></td>
                                                    <td class="font11">Asociados</td>
                                                </tr>
                                                <tr>
                                                    <td class="tdleyenda"></td>
                                                    <td class="font11">Simples</td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div> -->
                                <div class="col-xs-6 hidden-sm-down">
                                    <img width="200" height="70" style="margin-left:0%;" src="<?php echo PUBLIC_URL;?>img/<?php echo $this->mercancia[0]['tienda']; ?>.png"  alt="modelo">
                                </div>
                            </div>
                            <div class="row d-flex justify-content-end mr-3">
                                <div class="col-xs-2 mr-3">
                                    <h1 style="color: black;"><center>(<?php echo count($this->mercancia) ?>)</center></h1>
                                    <h4 style="color: black; margin-bottom: -10px"><center>Productos</center></h4>
                                </div>
                            </div>
                            <div class="alert alert-success col-sm-12" style="position: absolute; z-index: 100;" id="nuevop" hidden>
                                <center><h4>el producto se registro de forma exitosa</h4></center>
                            </div>
                            <?php $i = 1; ?>  
                            <div class="row d-flex justify-content-center" id="barradefiltro">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2 ">
                                    <label class="labels" style="float: left;">Grupo</label>
                                    <div class="col-xs-1 d-flex offset-11" >
                                      <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="En este campo debe seleccionar el elemento que permitirá especificar a que grupo pertenece el producto."></span>
                                    </div>
                                    <select name="grupo" id="grupo" class="form-control form-control-sm selectag" required>
                                    </select>
                                    <input type="hidden" name="grupo" id="grupoid">
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2 ">
                                    <label class="labels" style="float: left;">Clasificación</label>
                                    <div class="col-xs-1 d-flex offset-11" >
                                      <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="En este campo debe especificar la clasificación del grupo al que pertenece el producto."></span>
                                    </div>
                                    <select name="familia" id="familia2" class="form-control form-control-sm familia selectag" required> 
                                      <option value="">Seleccione..</option>
                                    </select>
                                    <input type="hidden" name="familia" id="familiaid">
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2 ">
                                    <label class="labels" style="float: left;">Sub clasificación</label>
                                    <div class="col-xs-1 d-flex offset-11" >
                                      <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="En este campo debe especificar la Sub clasificación de la clasificación del grupo al que pertenece el producto."></span>
                                    </div>
                                    <select name="subfamilia" id="sub_familia" class="form-control form-control-sm selectag"> 
                                      <option value="">Seleccione..</option>
                                    </select>
                                    <input type="hidden" name="subfamilia" id="subfamiliaid">
                                </div>
                                <div class="col-sm-1 mt-1" style="padding-left: 0px">
                                    <button type="button" id="filtrado" class="btn btn-sm btn-outline-primary mt-3">Filtrar</button>
                                </div>
                            </div>
                            
                            <div class="dataTable_wrapper ">
                             <div class=" table-responsive">
                                <table class="table table-sm table-striped table-bordered table-hover" id="tablaSM">
                                        <thead class="theadH">
                                            <?php if (isset($_SESSION['idmercancia'])): ?>
                            <div class="container cont-btn">
                                <div class="row d-flex mb-3">
                                    <div class="col-sm-2">
                                        <a href="<?php echo BASE_URL;?>inventario/evaluar/<?php echo $this->mercancia[0]['idT']; ?>" class="btn btn-sm btn-outline-primary">Ver todos los productos</a>
                                    </div>
                                </div>
                            </div>
                            <?php endif ?>
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th >Nombre</th> 
                                                <th >Marca</th>
                                                <th >Grupo</th>
                                                <th >Clasificación</th>
                                                <th >Sub clasificación</th>
                                                <th >Cont. neto</th>
                                                <!-- <th >Costo</th> -->
                                               <!--  <th >Existencia</th> -->
                                                <th >Stock min</th>
                                                <th >Stock max</th>
                                                <th >Estatus</th>
                                                <th >Acciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->mercancia as $merca): ?>
                                              <?php if ($merca['status'] == 1) {
                                                        $status = 'Inactivo';
                                                    }else{
                                                        $status = 'Activo';
                                                    } ?>
                                            <tr>

                                             
                                                <td  class="font11"><?php echo $i?></td>   
                                                <td class="font11" style="text-align:left"><?php echo $merca['codigo'];?></td>
                                                <td class="font11" style="text-align:left"><?php echo $merca['producto'];?></td>
                                                <td class="font11" style="text-align:left"><?php echo $merca['marca'];?></td>
                                                <td class="font11" style="text-align:left"><?php echo $merca['grupo'];?></td>
                                                <td class="font11" style="text-align:left"><?php echo $merca['familia'];?></td>
                                                <td class="font11" style="text-align:left"><?php echo $merca['subfamilia'];?></td>
                                                <td class="font11" style="text-align:right"><?php echo number_format($merca['contenido_neto'],2,",",".").$merca['abreviaturaS'];?></td>
                                                <!-- <td class="font11" style="text-align:right"><?php echo number_format($merca['precio_unitario'],2,",",".")." ".$_SESSION['monedatienda'];?></td> -->
                                                <!-- <td class="font11" style="text-align:right;"><?php echo $merca['stock'].$merca['abreviaturaS'].' ';?><a style="cursor: pointer; cursor: hand;" onclick="infoConversion('<?php echo $merca['idP'];?>','<?php echo $merca['idT'];?>')"><i data-toggle="tooltip" data-placement="top" title="Ver informacion detallada de la existencia" class="fa fa-info-circle ico faicons"></i></a></td> -->
                                                <td class="font11" style="text-align:right;"><?php echo $merca['stockm'].$merca['abreviaturaS'];?></td>
                                                <td class="font11" style="text-align:right;"><?php echo $merca['stockm2'].$merca['abreviaturaS'];?></td>
                                                <td class="font11" style="text-align:center"><?php echo $status;?></td>
                                                
                                                <th>
                                                    <center><a style="cursor: hand; font-size: 14px" class="test" data-toggle="modal" data-target="#prodUpdate" onclick="modalUpdate('<?php echo $merca['idP'];?>','<?php echo $merca['idT'];?>')">
                                                        <span data-toggle="tooltip" data-placement="top" title="Editar producto" class="fa fa-edit ico faicons"></span>
                                                    </a><a style="cursor: hand; font-size: 14px; margin-left: 5px" onclick="confirmacionDelete('<?php echo $merca['idP'];?>','<?php echo $merca['idT'];?>')">
                                                        <span data-toggle="tooltip" data-placement="top" title="Eliminar producto" class="fa fa-remove ico faicons"></span>
                                                    </a>
                                                    <!-- <a style="cursor: hand; margin-left: 5px; font-size: 14px" class="test" data-toggle="modal" data-target="#modalreposicion" onclick="compradirecta('<?php echo $merca['idP'];?>','<?php echo $merca['idT'];?>')">
                                                        <span data-toggle="tooltip" data-placement="top" title="Reposicion de mercancia por compra directa" class="fa fa-money"></span>
                                                    </a> -->
                                                    <?php if ($merca['tipo_ingrediente'] == 'Agrupado') {?>
                                                        <a href="<?php echo BASE_URL;?>inventario/grouped/<?php echo $merca['idT'].'/'.$merca['idP'].'/'.$merca['receta_id'];?>" style="cursor: hand; margin-left: 5px; font-size: 14px" class="test">
                                                        <span data-toggle="tooltip" data-placement="top" title="Agregar mas ingredientes" class="fa fa-plus-circle ico faicons" style="color: #666"></span>
                                                        </a>
                                                    <?php } ?>

                                                    </center>
                                                </th>
                                                
                                                
                                                
                                            </tr>
                                            <?php $i++; ?>

                                            <?php endforeach ?>
                                        </tbody>
                                    </table>

                                    <div class="container " >
                                        <div class="row d-flex justify-content-center">
                                            <div class="col-sm-1 col-xs-12 my-3 " >
                                                <button type="button" class="btn btn-sm btn-primary" id="print" data-toggle="tooltip" data-placement="top" title="Exportar a excel">Exportar <span class="fa fa-file-excel-o"></span></button>
                                            </div>
                                            <div class="col-sm-1 col-xs-12 my-3 mr-3">
                                                <button class="btn btn-sm btn-primary exportar" id="exportar">Ver listado <span class="fa fa-file-pdf-o"></span></button>
                                            </div>
                                            <div class="col-sm-1 col-xs-12 my-3">
                                                <a href="<?php echo BASE_URL;?>inventario/insert/<?php echo $merca['idT'];?>" class="btn btn-sm btn-outline-primary" onclick="codigoPropuesto('<?php echo $merca['idT'];?>')"> 
                                                    <font size="2"><b>Agregar </b>
                                                        
                                                    </font>
                                                    <span class="fa fa-plus-square"></span>
                                                </a>
                                            </div>
                                           
                                        </div>
                                    </div>

                                    <form action="<?php echo BASE_URL;?>inventario/excelExport" method="post" accept-charset="utf-8" id="form-print" hidden>
                                        <input type="hidden" name="idtienda" id="idtienda" value="<?php echo $this->mercancia[0]['idT'] ?>">
                                        <input type="hidden" name="gr" id="gr">
                                        <input type="hidden" name="fam" id="fam">
                                        <input type="hidden" name="subf" id="subf">
                                        <button type="submit" class="btn btn-sm btn-outline-primary" id="btnform2" hidden></button>
                                    </form>
                                    
                                        <br>
        

                <div class="modal fade" id="prodUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div id="enunciadoU"></div>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <form action="<?php echo BASE_URL;?>inventario/update" method="post" accept-charset="utf-8">
                            <div class="modal-body">
                                
                                <input type="text" name="idT" id="idT" hidden value="<?php echo $this->mercancia[0]['idT'];?>">
                                <input type="text" name="idemp" id="idemp" hidden value="<?php echo $this->mercancia[0]['empresa_id'];?>">
                                <input type="text" name="idP" id="idP" hidden >
                                <input type="text" name="tipo" id="type" hidden>

                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="labels">Grupo</label>
                                        <select name="grupo" id="groups" class="form-control form-control-sm selectag" required>
                                            </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels">Clasificación</label>
                                        <select name="familia_id" id="familias" class="form-control form-control-sm familia" required> 
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels" style="float: left;">Sub-Clasificación</label>
                                        <select name="subfamilia" id="sub_familias" class="form-control form-control-sm" required> 

                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels" style="float: left;">Código</label>
                                        <div class="col-1 d-flex offset-10" id="glyphicon" title="Este codigo esta asignado a otro producto">
                                        </div>
                                        <input type="text" class="form-control form-control-sm codigop" id="codi" name="codigo">
                                    </div>
                                    
                                    <div class="col-sm-3" hidden>
                                        <label class="labels">Codigo anterior</label>
                                        <input type="text" class="form-control form-control-sm" name="codigo_tcr" id="c_tcr">
                                    </div>
                                    
                                    
                                </div>
                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="labels" style="float: left;">Tipo de inventario</label>
                                        <select name="tipo_inventario" id="tipo_inventario" class="form-control form-control-sm" required> 
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels" style="float: left;">Tipo de producto</label>
                                        <input type="hidden" id="tipoing_id" name="tipo_ingrediente">
                                        <input type="text" id="tipo_ingrediente" class="form-control form-control-sm" readonly>
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels" style="float: left;">Nombre</label>
                                        <div class="col-1 d-flex offset-10" id="glyphi" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                        </div>
                                        <input type="text" class="form-control form-control-sm" name="nombre" id="nombre" required>
                                    </div>
                                    <div class="col-sm-3 simples">
                                        <label class="labels" style="float: left;">Marca</label>
                                        <div class="col-1 d-flex offset-10" id="glyph" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                        </div>
                                        <input type="text" class="form-control form-control-sm" name="marca" id="marca">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-sm-3 articulos" hidden>
                                        <label class="labels" style="float: left;">Modelo</label>
                                        <div class="col-xs-1 d-flex offset-11" >
                                              <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Modelo del producto"></span>
                                            </div>
                                        <input type="text" class="form-control form-control-sm" name="modelo" id="modelo" >
                                    </div>

                                    <div class="col-sm-3 equipos" hidden>
                                        <label class="labels" style="float: left;">Serial</label>
                                        <div class="col-xs-1 d-flex offset-11" >
                                              <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Serial unico del producto"></span>
                                            </div>
                                        <input type="text" class="form-control form-control-sm" name="serial" id="serial" >
                                    </div>

                                    <div class="col-sm-3 equipos" hidden>
                                        <label class="labels" style="float: left;" data-toggle="tooltip" data-placement="top" title="fecha del proximo mantenimiento">Fecha proximo Mtto.</label>
                                        <div class="col-xs-1 d-flex offset-11" >
                                              <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Fecha pautada para el proximo mantenimiento"></span>
                                            </div>
                                        <input type="date" style="height: 30px" class="form-control form-control-sm" name="mtto" id="mtto" >
                                    </div>

                                    <div class="col-sm-3 articulos" hidden>
                                        <label class="labels" style="float: left;">Talla</label>
                                        <input type="text" class="form-control form-control-sm inputsag" name="talla" id="talla" >
                                    </div>

                                    <div class="col-sm-3 articulos" hidden>
                                        <label class="labels" style="float: left;">Color</label>
                                        <input type="text" class="form-control form-control-sm inputsag" name="color" id="color" >
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels">status</label>
                                        <select name="status" id="status" class="form-control form-control-sm" required> 
                                        </select>
                                    </div>
                                </div>

                                <!-- <div class="form-group row simples">                                    
                                    <div class="col-sm-3 ">
                                        <label class="labels">Stock minimo <o class="abrevia"></o> </label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmin" id="stockmin">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels">Stock maximo <o class="abrevia"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmax" id="stockmax">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels">Existencia <o class="abrevia"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="existencia" id="existencia" readonly>
                                    </div>
                                    <div class="col-sm-3" hidden>
                                        <label class="labels" style="float: left;">Peso escurrido</label>
                                        <input type="text" class="form-control form-control-sm monto" name="pesoEs" id="pesoEs">
                                    </div>
                                </div> -->
                                <!-- <div class="form-group row " id="simplesdiv">
                                    
                                    <div class="col-sm-3 productoscompra simples">
                                        <label class="labels">Unidad de recepción</label>
                                        <select name="unidad_medida_co" class="form-control form-control-sm umc" id="unidad_medida_co" required>
                                        </select>
                                    </div>   
                                    <div class="col-sm-3 simples">
                                        <label class="labels">Unidad de consumo</label>
                                        <select name="unidad_medida_pr" id="unidad_medida_pr" class="form-control form-control-sm unidad_medida_p ump1" required>
                                        </select>
                                    </div> 
                                    <div class="col-sm-3 simples">
                                        <label class="labels" style="float: left;">Unidad de Consumo 2</label>
                                        <select name="unidad_medida_p2" class="form-control form-control-sm ump12" id="unidad_medida_pr2" >
                                          <option value="Seleccione" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>

                                    <div class="col-sm-3 simples">
                                        <label class="labels" style="float: left;">Unidad de Consumo 3</label>
                                        <select name="unidad_medida_p3" class="form-control form-control-sm ump13" id="unidad_medida_pr3" >
                                          <option value="Seleccione" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>  
                                    <div class="col-sm-3 simples">
                                        <label class="labels">Unidad de sistema</label>
                                        <select name="unidad_medida_si" id="unidad_medida_si" class="form-control form-control-sm ums" required>
                                        </select>
                                    </div>                                                              
                                    
                                    
                                    <div class="col-sm-3 asoc asociated" hidden>
                                        <label class="labels" style="float: left;">Unidad Consumo</label>
                                        <select  class="form-control form-control-sm ump " id="unidad_mp1" >
                                        <option value="" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>
                                    
                                    <div class="col-sm-3 asoc asociated" hidden>
                                        <label class="labels" style="float: left;">Unidad Sistema</label>
                                        <select class="form-control form-control-sm ums" id="unidad_ms1" >
                                        <option value="" selected disabled>Seleccione...</option>
                                        </select>
                                    </div>
                                    
                                    
                                </div> -->

                                <!-- <div class="row form-group simples">

                                    <div class="col-sm-3" id="canti1">
                                        <label class="labels" style="float: left;"><o id="umcons1"></o> / <o id="uc"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="cantidadConsumo" id="cantidadConsumo">
                                    </div>
                                    <div class="col-sm-3" id="canti2">
                                        <label class="labels" style="float: left;"><o id="umcons2"></o> / <o id="umco1"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="cantidadConsumo2" id="cantidadConsumo2">
                                    </div>
                                    <div class="col-sm-3" id="canti3">
                                        <label class="labels" style="float: left;"><o id="umcons3"></o> / <o id="umco2"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="cantidadConsumo3" id="cantidadConsumo3">
                                    </div>
                                    <div class="col-sm-3" id="canti4">
                                        <label class="labels" style="float: left;"><o id="umsis1"></o> / <o id="umco3"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="cantidadConsumo4" id="cantidadConsumo4">
                                    </div>
                              
                                </div> -->

                                <div class="form-group row">
                                    <div class="col-sm-3 " hidden>
                                        <label class="labels">Precio unitario</label><span style="float: right; cursor: pointer; cursor: hand;" class="fa fa-question-circle" id="infopreciou"></span>
                                        <div class="input-group">
                                            <input type="text" class="form-control form-control-sm precios" name="precio_unitario" id="pU" required placeholder="0,00">
                                            <span class="btn btn-sm input-group-addon bg-info" id="avconsumo" title="unidad de medida">U/M</span>
                                        </div>
                                    </div>
                                    <div class="col-sm-3" hidden>
                                        <label class="labels">Contenido neto</label><span style="float: right; cursor: pointer; cursor: hand;" class="fa fa-question-circle" id="infocontneto"></span>
                                        <div class="input-group">
                                            <input type="text" class="form-control form-control-sm contneto monto" name="contenidoN" id="contenidoN" autocomplete="off">
                                            <span class="btn btn-sm input-group-addon bg-info" id="avsistema" title="unidad de medida">U/M</span>
                                        </div>
                                    </div> 
                                    <div class="col-sm-3" hidden id="canti">
                                        <label class="labels">Uds por <o id="abrevU"></o></label>
                                        <input type="text" class="form-control form-control-sm cantix" name="cantidad" id="cantidad">
                                    </div>
                                    
                                    <div class="col-sm-6">
                                        <label class="labels" >Descripcion</label>
                                        <textarea class="form-control form-control-sm" rows="3" name="descripcion2" id="description"></textarea>
                                    </div> 
                                </div>
                                


                                <!-- <label class="control-label">Formulas de conversion</label>
                                        
                                    <div class="row ">
                                        <div class="col-10 offset-1">
                                            
                                                <div class="row align-items-center d-flex justify-content-center ">
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3 productoscompra simples">
                                                        <label class="labels" style="float: left;">U/M compra <a class="secreto" onclick="infoFormula()"><i title="Ver informacion" class="fa fa-info-circle" style="cursor: hand; cursor: pointer;"></i></a></label>
                                                        <input type="text" class="form-control form-control-sm formulac" name="formulac" id="formulac">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M consumo</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulap" id="formulap">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M sistema</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulas" id="formulas">
                                                    </div>
                                                </div>
                                            
                                        </div>
                                    </div> -->
                                    

                                </div>
                            
                            <div class="modal-footer">
                                <input type="button" class="btn btn-sm btn-outline-primary mr-3" value="Asociar productos" title="agregar elementos asociados a este producto" id="asoci" hidden>
                                <input type="submit" class="btn btn-sm btn-outline-primary" value="Guardar" id="botonG">
                            </div>
                            </form>
                        </div>
                    </div>
                </div>

                <!-- MODAL DE AGREGAR SUB_FAMILIAS NUEVAS-->
                    <div class="modal fade " id="modalsubfamilia" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div id="tc"><h6>Agregar nueva Sub-Clasificacion</h6></div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>


                                </div>
                                <div class="modal-body" >

                                   <div id="cuerpo"></div>
                                   <div class="form-group">
                                    <div class="col-sm-12">
                                      <label class="labels">Nombre de Sub-Clasificacion</label>
                                      <input type="text" id="nuevasub" class="form-control form-control-sm">
                                    </div>
                                   </div>
                                    
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" id="mcancelar">Cancelar</button>
                                  <button type="button" class="btn btn-sm btn-outline-primary" id="mcontinuar">Continuar</button>
                                </div>   
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->

                                                <!-- MODAL DEL LA FUNCION AGREGAR DE LOS PRODUCTOS -->
                <div class="modal fade" id="modaling" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <div class="modal-title" ><h3>Asociar productos</h3></div>
                          <button type="button" class="close cerrar" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      </div>
                        <div class="modal-body" style="padding-bottom: 0px">
                          <form action="" method="post" accept-charset="utf-8" id="form-asociar">
                          <div class="dataTable_wrapper " >
                              <div class="col-sm-12 table-responsive">
                                  <table id="tablafiltraje" class="display table table-sm table-striped table-bordered table-hover" >
                                    <thead class="theadH">
                                        <tr>
                                            <th>Codigo</th>
                                            <th>Ingrediente</th>
                                            <th>Costo</th>
                                            <th>Asociar</th>
                                        </tr>
                                    </thead>
                                    
                                    <tbody id="cuerpo_i">
                                    </tbody>
                                    
                                </table>     
                              </div>     
                          </div>
                        </div>
                        </form>
                        <div class="modal-footer" style="padding-top: 1px">
                          <button type="button" class="btn btn-sm btn-outline-secondary cerrar" data-dismiss="modal" id="bcancelar" title="Se eliminara la asociacion de tolos los productos asignados hasta ahora">Cancelar</button>
                          <button type="button" class="btn btn-sm btn-outline-primary" id="bcontinuar" title="asignar productos seleccionados">Continuar</button>
                        </div>
                    </div>
                  </div> 
                </div>
                                        <!--Modal para compras directas-->
                                        <div class="modal" tabindex="-1" role="dialog" id="modalreposicion">
                                          <div class="modal-dialog " role="document">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title" id="titulorep"></h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                                </button>
                                              </div>
                                              <div class="modal-body">
                                                <form action="<?php echo BASE_URL;?>inventario/compraDirecta" method="post" accept-charset="utf-8">
                                                    <input type="hidden" name="idT" id="idT2" value="<?php echo $this->mercancia[0]['idT'];?>">
                                                    <input type="hidden" name="idP" id="idP2" >
                                                    <input type="hidden" name="unidad_medida_si" id="umsis">
                                                    <input type="hidden" name="motivo" id="motivo" value="122">
                                                <div class="form-group row ">
                                                    
                                                    <div class="col-sm-4">
                                                        <label class="labels" style="float: left;">Contenido neto</label>
                                                        <div class="col-1 d-flex offset-10" id="glyphi" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                                        </div>
                                                        <input type="text" class="form-control form-control-sm contneto" name="contneto" id="contneto">
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label class="labels" style="float: left;">Cant. comprada</label>
                                                        <div class="col-1 d-flex offset-10" id="glyphi" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                                        </div>
                                                        <input type="text" class="form-control form-control-sm" name="cantcomprada" id="cantcomprada" required>
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label class="labels" style="float: left;">U/M Compra</label>
                                                        <select name="umcompra" class="form-control form-control-sm" id="umcompra" required>
                                                            <option value="selected disabled">Seleccione..</option>}
                                                        </select>
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label for="" class="labels" style="float: left;">Conversion a <o id="conver"></o></label>
                                                        <input type="text" class="form-control form-control-sm formulac" name="formulacomp" id="formulacomp">
                                                    </div> 
                                                    <div class="col-sm-4" id="canti" hidden>
                                                        <label class="labels" style="float: left;"><o id="up"></o><o class="uc"></o></label>
                                                        <input type="text" class="form-control form-control-sm cantix" name="cantix" id="cantix">
                                                    </div>

                                                    <div class="col-sm-8">
                                                        <label class="labels" style="float: left;">Descripcion</label>
                                                        <textarea class="form-control form-control-sm" rows="2" name="descripcion"></textarea>
                                                    </div>                                                 
                                                </div>
                                                
                                              </div>
                                              <div class="modal-footer">
                                                <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal">Cancelar</button>
                                                <input type="submit" class="btn btn-sm btn-outline-primary" value="Guardar">
                                              </div>
                                            </form>
                                            </div>
                                          </div>
                                        </div>
                                        <!--fin Modal para compras directas-->

                <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <div id="t"></div>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>


                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpoi" class="cuerpo"></div>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>  
                                                    <div class="modal-footer" id="mfooter">
                                                      
                                                    </div> 
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                        <!-- FIN DE LA MODAL DE CONFIRMACION -->
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
</div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
        <!-- no borrar -->
        </div>