<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
<div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="col-sm-4">
                            <h4 class="page-header" style="font-family: Times New Roman, Times, serif;">Lista de productos de la empresa</h4>
                        </div> 
                      <!--  <div class="col-sm-offset-1">
                            <img style="margin-left:0%;" src="<?php echo PUBLIC_URL;?>img\<?php echo $this->sm[0]['modelo']; ?>.png" class="img-responsive" alt="modelo">
                        </div> -->

                        <div class="panel panel-default">
                        <div class="panel-body">
                            <?php $i = 1; ?>  
                            <div class="dataTable_wrapper ">
                             <div class="col-sm-12 table-responsive">
                                <table class="table table-striped table-bordered table-hover " id="tablaSM">
                                        <thead>
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th>Nombre</th> 
                                                <th >Marca</th>
                                                <th >Cont. neto</th>
                                                <th >Precio ud.</th>
                                                <th >Existencia</th>
                                                <th >Stock min</th>
                                                <th >Stock max</th>
                                                <th >Estatus</th>
                                                <th >Familia</th>
                                                <th >Modificar</th>
                                                <th >Eliminar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->mercancia as $merca): ?>
                                              <?php if ($merca['status'] == 1) {
                                                        $status = 'Inactivo';
                                                    }else{
                                                        $status = 'Activo';
                                                    } ?>
                                            <tr> 
                                                <td ><?php echo $i?></td>   
                                                <td style="text-align:left"><?php echo $merca['codigo'];?></td>
                                                <td style="text-align:left"><?php echo $merca['producto'];?></td>
                                                <td style="text-align:left"><?php echo $merca['descripcion'];?></td>
                                                <td style="text-align:left"><?php echo $merca['contenido_neto'];?></td>
                                                <td style="text-align:left"><?php echo $merca['precio_unitario'];?></td>
                                                <td style="text-align:left"><?php echo $merca['cantidad_inventariada'].$merca['abreviatura'];?></td>
                                                <td style="text-align:left"><?php echo $merca['stock_minimo'];?></td>
                                                <td style="text-align:left"><?php echo $merca['stock_maximo'];?></td>
                                                <td style="text-align:left"><?php echo $status;?></td>
                                                <td style="text-align:left"><?php echo $merca['familia'];?></td>
                                                <th>
                                                    <center><a class="test" data-toggle="modal" data-target=".subModels" onclick="idSubmodelo('<?php echo $sm['idsm'];?>','<?php echo $sm['idmodelo'];?>')">
                                                        <span  class="glyphicon glyphicon-edit"></span>
                                                    </a></center>
                                                </th>
                                                
                                                <th>
                                                   <center><a onclick="confirmacionDelete('<?php echo $sm['idsm'];?>','<?php echo $sm['idmodelo'];?>')">
                                                        <span  class="glyphicon glyphicon-remove"></span>
                                                    </a></center>
                                                </th>
                                                
                                            </tr>
                                            <?php $i++; ?>

                                            <?php endforeach ?>
                                        </tbody>
                                    </table> 
                                    <button type="button" style="border-radius: 5px; width: 120px; margin-left: 15px" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#produ"> 
                                        <font size="2"><b>Agregar &nbsp;</b>
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </font>
                                    </button>
                                    <!-- MODAL DEL LA FUNCION AGREGAR DE LOS PRODUCTOS -->
                <div class="modal fade" id="produ" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <div id="enunciado"></div>
                            </div>
                            <form action="<?php echo BASE_URL;?>producto/insert" method="post" accept-charset="utf-8">
                            <div class="modal-body">
                                <input type="text" name="modelo" id="m" hidden value="<?php echo $this->pro[0]['idmodelo'];?>">
                                <input type="text" name="sub_modelo" id="sm" hidden value="<?php echo $this->pro[0]['sub_modelo_id'];?>">
                                <input type="text" name="tipo" id="type" hidden>

                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Codigo</label>
                                        <input type="text" class="form-control" id="co" name="codigo">
                                    </div>
                                    <div class="col-sm-1" id="glyphicon"></div>
                                    <div class="col-sm-4">
                                        <label class="control-label" style="float: left;">Codigo anterior</label>
                                        <input type="text" class="form-control" name="codigo_tcr" id="c_tcr">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Nombre</label>
                                        <input type="text" class="form-control" name="nombre" id="nombre" required>
                                    </div>
                                    <div class="col-sm-1" id="glyphi"></div>
                                    <div class="col-sm-4">
                                        <label class="control-label" style="float: left;">Marca</label>
                                        <input type="text" class="form-control" name="marca" id="marca">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Precio unitario</label>
                                        <input type="text" class="form-control" name="precio_unitario" id="pU" onkeyup="format(this)" onchange="format(this)" required placeholder="0,00">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Clasificacion</label>
                                        <select name="familia_id" id="familia" class="form-control" required> 
                                        </select>
                                    </div>
                                    <div class="col-sm-2 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Stock minimo</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">
                                    </div>
                                    <div class="col-sm-2">
                                        <label class="control-label" style="float: left;">Stock maximo</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Unidad de medida compra</label>
                                        <select name="ocultar" class="form-control" id="ocultar" required>
                                        </select>
                                    </div>
                                    <div class="col-sm-3 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Cantidad comprada</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">
                                    </div>
                                    <div class="col-sm-3 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Contenido neto unidad</label>
                                        <input type="text" class="form-control" name="cantidad" id="cantidad">
                                    </div>
                                    
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Precio unitario</label>
                                        <input type="text" class="form-control" name="precio_unitario" id="pU" onkeyup="format(this)" onchange="format(this)" required placeholder="0,00">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Clasificacion</label>
                                        <select name="familia_id" id="familia" class="form-control" required> 
                                        </select>
                                    </div>
                                    <div class="col-sm-2 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Stock minimo</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">
                                    </div>
                                    <div class="col-sm-2">
                                        <label class="control-label" style="float: left;">Stock maximo</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">
                                    </div>
                                </div>

                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-primary" value="Guardar" id="botonG">
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
                                      <!-- FIN DE LA MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                      <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade subModels" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog modal-sm" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                      <h4 class="modal-title">Modificar sub-modelo</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>submodelo/update" method="post" accept-charset="utf-8">
                                                          <input type="text" hidden name="idsm" id="idsm">
                                                          <input type="text" hidden name="idm" id="idm">
                                                          <input type="text" name="subModelo" class="form-control" id="Smodelo" placeholder="nombre del sub-modelo"> <br>
                                                         <center> <input type="submit" class="btn btn-primary" value="Guardar" onclick="insert()"> </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->

                                       <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <div id="titulo"></div>
                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpo"></div><br><br>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>   
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                        <!-- FIN DE LA MODAL DE CONFIRMACION -->
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
</div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
 		<!-- no borrar -->
 		</div>