<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
<div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">
                      <div class="panel panel-default">
                        <div class="panel-body">
                        <div class="col-sm-6">
                            <h4 class="page-header" style="font-family: Times New Roman, Times, serif;">Inventario de productos </h4>
                        </div> 
                        <div class="col-sm-offset-1">
                            <img style="margin-left:0%;" src="<?php echo PUBLIC_URL;?>img\Corporacion multifranquicia.png" class="img-responsive" alt="modelo">
                        </div> <br><br>
                            <?php $i = 1; ?>  
                            <div class="dataTable_wrapper ">
                             <div class="col-sm-12 table-responsive">
                                <table class="table table-striped table-bordered table-hover " id="tablaSM">
                                        <thead>
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th>Nombre</th> 
                                                <th >Marca</th>
                                                <th >Cont. neto</th>
                                                <th >Precio ud.</th>
                                                <th >Existencia</th>
                                                <th >Stock min</th>
                                                <th >Stock max</th>
                                                <th >Estatus</th>
                                                <th >Familia</th>
                                                <th >Modificar</th>
                                                <th >Eliminar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->mercancia as $merca): ?>
                                              <?php if ($merca['status'] == 1) {
                                                        $status = 'Inactivo';
                                                    }else{
                                                        $status = 'Activo';
                                                    } ?>
                                            <tr> 
                                                <td ><?php echo $i?></td>   
                                                <td style="text-align:left"><?php echo $merca['codigo'];?></td>
                                                <td style="text-align:left"><?php echo $merca['producto'];?></td>
                                                <td style="text-align:left"><?php echo $merca['marca'];?></td>
                                                <td style="text-align:left"><?php echo $merca['contenido_neto'];?></td>
                                                <td style="text-align:left"><?php echo $merca['precio_unitario'];?></td>
                                                <td style="text-align:left"><?php echo $merca['existencia'].$merca['abreviaturaS'];?><a onclick="infoConversion('<?php echo $merca['idP'];?>','<?php echo $merca['idT'];?>')"><i class="fa fa-info-circle"></i></a></td>
                                                <td style="text-align:left"><?php echo $merca['stock_min'];?></td>
                                                <td style="text-align:left"><?php echo $merca['stock_max'];?></td>
                                                <td style="text-align:left"><?php echo $status;?></td>
                                                <td style="text-align:left"><?php echo $merca['familia'];?></td>
                                                <th>
                                                    <center><a class="test" data-toggle="modal" data-target="#produPdate" onclick="modalUpdate('<?php echo $merca['idP'];?>','<?php echo $merca['idT'];?>')">
                                                        <span  class="glyphicon glyphicon-edit"></span>
                                                    </a></center>
                                                </th>
                                                
                                                <th>
                                                   <center><a onclick="confirmacionDelete('<?php echo $merca['idP'];?>','<?php echo $merca['idT'];?>')">
                                                        <span  class="glyphicon glyphicon-remove"></span>
                                                    </a></center>
                                                </th>
                                                
                                            </tr>
                                            <?php $i++; ?>

                                            <?php endforeach ?>
                                        </tbody>
                                    </table> 
                                    <a href="<?php echo BASE_URL;?>inventario/insert/<?php echo $merca['idT'];?>" type="button" style="border-radius: 5px; width: 120px; margin-left: 15px" class="btn btn-sm btn-primary" onclick="codigoPropuesto('<?php echo $merca['idT'];?>')"> 
                                        <font size="2"><b>Agregar &nbsp;</b>
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </font>
                                    </a>
                                        <br>
                                   
                                 
                      

                                       <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <div id="t"></div>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <div id="titulo"></div>
                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpo"></div><br><br>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>   
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                        <!-- FIN DE LA MODAL DE CONFIRMACION -->
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
</div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
        <!-- no borrar -->
        </div>