<style type="text/css" media="screen">
    .labels{
        margin-bottom: 0px;
    }
</style>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
<div id="page-wrapper">
            <div  class="">

                <div class="row">
                    <div class="col-lg-12">
                    <div class="card cardH">

                            <div class="card-header" hidden>
                              <center><h4 ><o id="titulocard">Consulta de inventario</o> <?php $ti=strtolower(str_replace('(PTY)', '', $this->g[0]['tienda'])); echo "[".ucwords($ti)."] Sub-modelo ".$this->g[0]['subM'];  ?></h4></center>
                            </div>
                          
                          <div class="card-block">
                            <div class="row d-flex flex-wrap">
                                <div class="col-6">
                                    <h4 class="page-header" style="font-family: Times New Roman, Times, serif; text-align: center">Unidad de negocio <?php echo str_replace('(PTY)', '', $this->g[0]['tienda']); echo '<br> Sub-modelo '.$this->g[0]['subM'];  ?></h4>
                                </div>
                            
                                <div class="col-6 d-flex justify-content-end">
                                    <img  style="margin-left:0%;" src="<?php $model=strtolower($this->g[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-fluid" alt="modelo">
                                </div>
                            </div>


                            
                            <?php $i = 1; ?> 
                            <div class="dataTable_wrapper">
                             <div class="col-sm-12 table-responsive">
                                <?php if ($this->g[0]['producto'] === 'vacio'):?>
                                <table class="table table-sm table-striped table-bordered table-hover" cellspacing="0" width="100%" id="tablaGru">
                                        <thead>
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th>Nombre</th> 
                                                <th >Marca</th>
                                                <th >Can. Invent</th>
                                                <th >Ud. Medida</th>
                                                <th >Familia</th>
                                                <th >Estatus</th>
                                                <th >Modificar</th>
                                                <th >Eliminar</th>
                                            </tr>
                                        </thead>
                                </table> 
                                    <?php else: ?>
                                       <table class="table table-sm table-striped table-bordered table-hover" id="tablaGru">
                                        <thead class="theadH">
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th>Nombre</th> 
                                                <th >Marca</th>
                                                <th >Familia</th>
                                                <th >Existencia</th>
                                                <th >Estatus</th>
                                                <th >Acciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->g as $g): ?>
                                              <?php if ($g['status'] == 1) {
                                                        $status = 'Inactivo';
                                                    }else{
                                                        $status = 'Activo';
                                                    } ?>
                                            <tr> 
                                                <td class="font11" style="text-align:center;"><?php echo $i?></td>
                                                <td class="font12"><?php echo $g['codigo'];?></td>
                                                <td class="font12" style="text-align:left"><?php echo $g['producto'];?></td>
                                                <td class="font12" ><?php echo $g['marca'];?></td>
                                                <td class="font12" ><?php echo $g['familia'];?></td>  
                                                <td class="font12" style="text-align:right;"><?php echo $g['stock'].$g['abreviaturaS'].' ';?>
                                                    <a style="cursor: pointer; cursor: hand;" onclick="infoConversion('<?php echo $g['idP'];?>','<?php echo $g['idT'];?>')"><i data-toggle="tooltip" data-placement="top" title="Ver informacion detallada de la existencia" class="fa fa-info-circle ico faicons"></i>
                                                    </a>
                                                </td>
                                                <td class="font12" style="text-align:center;"><?php echo $status;?></td>

                                                <th>
                                                    <center>
                                                        <a style="cursor: hand; font-size: 14px" class="test" data-toggle="modal" data-target="#prodUpdate" onclick="modalUpdate('<?php echo $g['idP'];?>','<?php echo $g['idT'];?>')">
                                                            <span  class="fa fa-edit ico faicons" data-toggle="tooltip" data-placement="top" title="Editar Producto"></span>
                                                        </a>
                                                        <!-- <a style="cursor: hand; margin-left: 10px; font-size: 17px" class="test" data-toggle="modal" data-target="#modalreposicion" onclick="compradirecta('<?php echo $g['idP'];?>','<?php echo $g['idT'];?>')">
                                                            <span data-toggle="tooltip" data-placement="top" title="Reposicion de mercancia por compra directa" class="fa fa-money"></span>
                                                        </a> -->
                                                    </center>
                                                </th>

                                            </tr>
                                            <?php $i++; ?>

                                            <?php endforeach ?>
                                        </tbody>
                                    </table> 
                                  <?php endif; ?>
                                    <br>
                                    <div class="container-fluid">
                                        <div class="col-sm-3">
                                            <table class="table table-sm table-bordered">
                                                <thead class="theadH">
                                                    <tr>
                                                        <td colspan="2" class="font11"><center>Tipos de productos</center></td>
                                                    </tr>
                                                </thead>
                                                <tr>
                                                    <td style="background: #D4E5F4; color: #D4E5F4;"></td>
                                                    <td class="font11">Agrupados</td>
                                                </tr>
                                                <tr>
                                                    <td style="background: #e1eefb; color: #e1eefb;"></td>
                                                    <td class="font11">Asociados</td>
                                                </tr>
                                                <tr>
                                                    <td class="tdleyenda"></td>
                                                    <td class="font11">Simples</td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                                
                                            
                                    
                                    <!-- <div class="container">
                                        <div class="row ">
                                            <div class="col-sm-12 d-flex justify-content-center">
                                        <button type="button" style="border-radius: 5px; width: 120px; margin-left: 15px" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#produ"> 
                                            <font size="2"><b>Agregar &nbsp;</b>
                                                <span class="fa fa-plus"></span>
                                            </font>
                                        </button>
                                            </div>
                                        </div>
                                    </div> -->
                                     <!-- MODAL DEL LA FUNCION EDITAR LOS PRODUCTOS -->
                <div class="modal fade" id="prodUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div id="enunciadoU"></div>
                                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form action="<?php echo BASE_URL;?>inventario/update" method="post" accept-charset="utf-8">
                            <div class="modal-body">
                                <!-- <input type="text" name="modelo" id="m" hidden value="<?php echo $this->pro[0]['idmodelo'];?>">
                                <input type="text" name="sub_modelo" id="sm" hidden value="<?php echo $this->pro[0]['sub_modelo_id'];?>"> -->
                                <input type="text" name="idT" id="idT" hidden value="<?php echo $this->g[0]['idT'];?>">
                                <input type="text" name="idP" id="idP" hidden >
                                <input type="text" name="tipo" id="type" hidden>

                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="labels">Codigo</label>
                                        <input style="cursor: not-allowed" type="text" class="form-control form-control-sm codigop" id="codi" name="codigo" readonly="">
                                    </div>
                                    <div class="col-sm-1" id="glyphicon"></div>
                                    <div class="col-sm-3">
                                        <label class="labels">Codigo anterior</label>
                                        <input style="cursor: not-allowed" type="text" class="form-control form-control-sm" name="codigo_tcr" id="c_tcr" readonly>
                                    </div>
                                    <div class="col-sm-3 col-sm-">
                                        <label class="labels">status</label>
                                        <select name="status" id="status" class="form-control form-control-sm" required> 
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="labels">Nombre</label>
                                        <input type="text" class="form-control form-control-sm" name="nombre" id="nombre" required>
                                    </div>
                                    <div class="col-sm-1" id="glyphi"></div>
                                    <div class="col-sm-3">
                                        <label class="labels">Marca</label>
                                        <input type="text" class="form-control form-control-sm" name="marca" id="marca">
                                    </div>
                                    <div class="col-sm-3 col-sm-">
                                        <label class="labels">Clasificacion</label>
                                        <select name="familia_id" id="familias" class="form-control form-control-sm" required> 
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="labels">Precio unitario</label>
                                        <input type="text" class="form-control form-control-sm precios" name="precio_unitario" id="pU"  required placeholder="0,00">
                                    </div>
                                    
                                    <div class="col-sm-3 ">
                                        <label class="labels">Stock minimo <o class="abrevia"></o> </label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmin" id="stockmin">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels">Stock maximo <o class="abrevia"></o></label>
                                        <input type="text" class="form-control form-control-sm monto" name="stockmax" id="stockmax">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels">Existencia <o class="abrevia"></o></label>
                                        <input style="cursor: not-allowed" type="text"  class="form-control form-control-sm monto" name="existencia" id="existencia" readonly="" title="Se actualiza al cargar las remisiones y/o reposicion de mercancia">
                                    </div>
                                </div>
                                <div class="form-group row ">
                                    <div class="col-sm-3">
                                        <label class="labels">Unidad de compra</label>
                                        <select name="unidad_medida_co" class="form-control form-control-sm" id="unidad_medida_co" required>
                                        </select>
                                    </div>   
                                    <div class="col-sm-3">
                                        <label class="labels">Unidad de presentacion</label>
                                        <select name="unidad_medida_pr" id="unidad_medida_pr" class="form-control form-control-sm" required>
                                        </select>
                                    </div>   
                                    <div class="col-sm-3">
                                        <label class="labels">Unidad de sistema</label>
                                        <select name="unidad_medida_si" id="unidad_medida_si" class="form-control form-control-sm" required>
                                        </select>
                                    </div> 
                                    <div class="col-sm-3 ">
                                        <label class="labels">Contenido neto</label>
                                        <input type="text" class="form-control form-control-sm monto" name="contenidoN" id="contenidoN">
                                    </div>  

                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-3 ">
                                        <label class="labels"><o id="abrevU"></o></label>
                                        <input type="text" class="form-control form-control-sm" name="cantidad" id="cantidad">
                                    </div>
                                    <div class="col-sm-3">
                                        <label class="labels" style="float: left;">Peso escurrido</label>
                                        <input type="text" class="form-control form-control-sm monto" name="pesoEs" id="pesoEs">
                                    </div>
                                </div>

                                <label class="control-label">Formulas de conversion</label>
                                        
                                    <div class="row ">
                                        <div class="col-10 offset-1">
                                            
                                                <div class="row align-items-center d-flex justify-content-center ">
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M compra <a class="secreto" onclick="infoFormula()"><i title="Ver informacion" class="fa fa-info-circle" style="cursor: hand; cursor: pointer;"></i></a></label>
                                                        <input type="text" class="form-control form-control-sm formulac" name="formulac" id="formulac">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M consumo</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulap" id="formulap">
                                                    </div>
                                                    <div class="col-xs-4 col-sm-4 col-md-3 mt-3">
                                                        <label class="labels" style="float: left;">U/M sistema</label>
                                                        <input type="text" class="form-control form-control-sm" name="formulas" id="formulas">
                                                    </div>
                                                </div>
                                            
                                        </div>
                                    </div>
                                    

                                </div>
                                
                            <div class="row mt-3">
                                    <div class="col-sm-12">
                                        <h6>* La existencia se actualiza automaticamente al cargar las remisiones y/o reposicion de mercancia</h6>
                                    </div>
                                </div>
                            <div class="modal-footer">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <input type="submit" class="btn btn-primary" value="Guardar" id="botonG">
                                    </div>
                                </div>
                                
                                
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
                                    <!-- MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gr" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                      <h4 class="modal-title">Agregar Grupo</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/insert" method="post" accept-charset="utf-8">
                                                          <input type="text" name="modelo" hidden value="<?php echo $this->g[0]['idmodelo']; ?>" >
                                                          <input type="text" name="submodelo" hidden value="<?php echo $this->g[0]['submodelo_id']; ?>" >
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2">
                                                              <label class="labels" style="float: left;">Orden</label>
                                                              <input type="text" class="form-control form-control-sm" name="orden" required>
                                                            </div>
                                                            <div class="col-sm-6">
                                                              <label class="labels" style="float: left;">Nombre</label>
                                                              <input type="text" class="form-control form-control-sm" name="nombre" required placeholder="Nombre del grupo">
                                                            </div>
                                                            <div class="col-sm-3">
                                                              <label class="labels" style="float: left;">Status</label>
                                                              <select name="status" class="form-control form-control-sm" required>
                                                                <option value="" disabled>Seleccione</option>
                                                                <option value="0">Activo</option>
                                                                <option value="1">Inactivo</option>
                                                              </select>
                                                            </div>
                                                          </div> <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" onclick="insert()"> </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                        
                                      <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gru" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                        <h4 class="modal-title">Modificar Producto</h4>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                        </button>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/update" method="post" accept-charset="utf-8">
                                                          <input type="text" hidden name="idsm" id="idSubM">
                                                          <input type="text" hidden name="idm" id="idMo">
                                                          <input type="text" hidden name="idg" id="idG">
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2" id="orden"></div>
                                                            <div class="col-sm-5" id="nombre"></div>
                                                            <div class="col-sm-3" >
                                                              <label class="labels" style="float: left;">Status</label>
                                                              <select name="status" id="status" class="form-control form-control-sm">
                                                              <option value="" disabled>seleccione</option>
                                                              </select>
                                                            </div>
                                                          </div>
                                                          <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" > </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                                       
                                        <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <div id="t"></div>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpo" class="cuerpo"></div>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>   
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                        <!-- FIN DE LA MODAL DE CONFIRMACION -->

                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
</div>
</div>
</div>
</div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
    <!-- no borrar -->
    </div>