<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

<div id="body" hidden>
<div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="col-sm-6">
                            <h4 class="page-header" style="font-family: Times New Roman, Times, serif;">Unidad de negocio <?php echo $this->g[0]['tienda']; echo '<br> Sub-modelo'.$this->g[0]['subM'];  ?></h4>
                        </div> 
                        <div class="col-sm-offset-1">
                            <img style="margin-left:0%;" src="<?php $model=strtolower($this->g[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-responsive" alt="modelo">
                        </div>

                        <div class="panel panel-default">
                        <div class="panel-body">
                            <?php $i = 1; ?>  
                            <div class="dataTable_wrapper">
                             <div class="col-sm-12 table-responsive">
                                <?php if ($this->g[0]['producto'] === 'vacio'):?>
                                <table class="table table-striped table-bordered table-hover" id="tablaGru">
                                        <thead>
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th>Nombre</th> 
                                                <th >Marca</th>
                                                <th >Can. Invent</th>
                                                <th >Ud. Medida</th>
                                                <th >Familia</th>
                                                <th >Estatus</th>
                                                <th >Modificar</th>
                                                <th >Eliminar</th>
                                            </tr>
                                        </thead>
                                </table> 
                                    <?php else: ?>
                                       <table class="table table-striped table-bordered table-hover" id="tablaGru">
                                        <thead>
                                            <tr>
                                                <th>#</th>                                                    
                                                <th >Codigo</th>
                                                <th>Nombre</th> 
                                                <th >Marca</th>
                                                <th >Existencia</th>
                                                <th >Ud. Medida</th>
                                                <th >Familia</th>
                                                <th >Estatus</th>
                                                <th >Modificar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->g as $g): ?>
                                              <?php if ($g['status'] == 1) {
                                                        $status = 'Inactivo';
                                                    }else{
                                                        $status = 'Activo';
                                                    } ?>
                                            <tr> 
                                                <td ><?php echo $i?></td>
                                                <td ><?php echo $g['codigo'];?></td>
                                                <td style="text-align:left"><?php echo $g['producto'];?></td>
                                                <td ><?php echo $g['descripcion'];?></td>
                                                <td ><?php echo $g['cantidad_inventariada'];?></td>
                                                <td ><?php echo $g['unidad'];?></td>
                                                <td ><?php echo $g['familia'];?></td>   
                                                <td ><?php echo $status;?></td>

                                                <th>
                                                    <center><a class="test" data-toggle="modal" data-target=".gru" onclick="idgrupo('<?php echo $g['submodelo_id'];?>','<?php echo $g['idmodelo'];?>','<?php echo $g['id'];?>')">
                                                        <span  class="glyphicon glyphicon-edit"></span>
                                                    </a></center>
                                                </th>

                                            </tr>
                                            <?php $i++; ?>

                                            <?php endforeach ?>
                                        </tbody>
                                    </table> 
                                  <?php endif; ?>
                                    <button type="button" style="border-radius: 5px; width: 120px; margin-left: 15px" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#produ"> 
                                        <font size="2"><b>Agregar &nbsp;</b>
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </font>
                                    </button>
                                     <!-- MODAL DEL LA FUNCION AGREGAR DE LOS PRODUCTOS -->
                <div class="modal fade" id="produ" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <div id="enunciado"></div>
                            </div>
                            <form action="<?php echo BASE_URL;?>producto/insert" method="post" accept-charset="utf-8">
                            <div class="modal-body">
                                <input type="text" name="modelo" id="m" hidden value="<?php echo $this->pro[0]['idmodelo'];?>">
                                <input type="text" name="sub_modelo" id="sm" hidden value="<?php echo $this->pro[0]['sub_modelo_id'];?>">
                                <input type="text" name="tipo" id="type" hidden>

                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Codigo</label>
                                        <input type="text" class="form-control" id="co" name="codigo">
                                    </div>
                                    <div class="col-sm-1" id="glyphicon"></div>
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Codigo anterior</label>
                                        <input type="text" class="form-control" name="codigo_tcr" id="c_tcr">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Nombre</label>
                                        <input type="text" class="form-control" name="nombre" id="nombre" required>
                                    </div>
                                    <div class="col-sm-1" id="glyphi"></div>
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Marca</label>
                                        <input type="text" class="form-control" name="marca" id="marca">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Precio unitario</label>
                                        <input type="text" class="form-control" name="precio_unitario" id="pU" onkeyup="format(this)" onchange="format(this)" required placeholder="0,00">
                                    </div>
                                    <div class="col-sm-3 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Clasificacion</label>
                                        <select name="familia_id" id="familia" class="form-control" required> 
                                        </select>
                                    </div>
                                    <div class="col-sm-2 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Stock minimo</label>
                                        <input type="text" class="form-control" name="stockmin" id="stockmin">
                                    </div>
                                    <div class="col-sm-2">
                                        <label class="control-label" style="float: left;">Stock maximo</label>
                                        <input type="text" class="form-control" name="stockmax" id="stockmax">
                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">Unidad de compra</label>
                                        <select name="unidad_medida_c" class="form-control" id="unidad_medida_c" required>
                                        </select>
                                    </div>
                                    
                                    <div class="col-sm-3 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Cantidad comprada</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">

                                    </div>
                                </div>
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="control-label" style="float: left;">unidad de presentacion</label>
                                        <select name="unidad_medida_p" id="unidad_medida_p" class="form-control" required>
                                        </select>
                                    </div>
                                    <div class="col-sm-2 col-sm-offset-1">
                                        <label class="control-label" style="float: left;">Contenido neto</label>
                                        <input type="text" class="form-control" name="contenidoN" id="contenidoN">
                                    </div>
                                    <div class="col-sm-4" id="cantx"></div>

                                    <div class="col-sm-3 col-sm-offset-1" hidden>
                                        <label class="control-label" style="float: left;">unidad de sistema</label>
                                    </div>
                                </div>

                                </div>
                            
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-primary" value="Guardar" id="botonG">
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
                                    <!-- MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gr" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                      <h4 class="modal-title">Agregar Grupo</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/insert" method="post" accept-charset="utf-8">
                                                          <input type="text" name="modelo" hidden value="<?php echo $this->g[0]['idmodelo']; ?>" >
                                                          <input type="text" name="submodelo" hidden value="<?php echo $this->g[0]['submodelo_id']; ?>" >
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2">
                                                              <label class="control-label" style="float: left;">Orden</label>
                                                              <input type="text" class="form-control" name="orden" required>
                                                            </div>
                                                            <div class="col-sm-6">
                                                              <label class="control-label" style="float: left;">Nombre</label>
                                                              <input type="text" class="form-control" name="nombre" required placeholder="Nombre del grupo">
                                                            </div>
                                                            <div class="col-sm-3">
                                                              <label class="control-label" style="float: left;">Status</label>
                                                              <select name="status" class="form-control" required>
                                                                <option value="" disabled>Seleccione</option>
                                                                <option value="0">Activo</option>
                                                                <option value="1">Inactivo</option>
                                                              </select>
                                                            </div>
                                                          </div> <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" onclick="insert()"> </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION AGREGAR DE LOS SUB-MODELOS -->
                                      <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                                      <div class="modal fade gru" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                          <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                      <h4 class="modal-title">Modificar grupo</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <form action="<?php  echo BASE_URL;?>grupo/update" method="post" accept-charset="utf-8">
                                                          <input type="text" hidden name="idsm" id="idSubM">
                                                          <input type="text" hidden name="idm" id="idMo">
                                                          <input type="text" hidden name="idg" id="idG">
                                                          <div class="col-sm-12">
                                                            <div class="col-sm-2" id="orden"></div>
                                                            <div class="col-sm-5" id="nombre"></div>
                                                            <div class="col-sm-3" >
                                                              <label class="control-label" style="float: left;">Status</label>
                                                              <select name="status" id="status" class="form-control">
                                                              <option value="" disabled>seleccione</option>
                                                              </select>
                                                            </div>
                                                          </div>
                                                          <br>
                                                         <center style="margin-top:50px"> <input type="submit" class="btn btn-primary" value="Guardar" > </center>
                                                      </form>
                                                  </div>   
                                              </div><!-- /.modal-content -->
                                          </div><!-- /.modal-dialog -->
                                      </div><!-- /.modal -->
                                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->

                                        <!-- MODAL DE CONFIRMACION PARA ELIMINAR-->
                                        <div class="modal fade " id="alerta" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        <div id="titulo"></div>
                                                    </div>
                                                    <div class="modal-body" >

                                                       <div id="cuerpo"></div><br><br>
                                                        <center>    
                                                            <div id="espera" hidden>
                                                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                                                            </div>
                                                            <div id="exito" hidden>
                                                                <img width="140px" height="140px" class="img" src="<?php echo PUBLIC_URL; ?>img/check1.gif">
                                                            </div>
                                                        </center>
                                                    </div>   
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                        <!-- FIN DE LA MODAL DE CONFIRMACION -->

                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
</div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
    <!-- no borrar -->
    </div>