<head>
  <meta charset="utf-8">
  <title>Inicio</title>



  
</head>
<center>
    <div style="margin-top: 15%" id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
   <div class="card cardH" > 
   <section class="dashboard-counts section-padding">
        <div class="container-fluid">
        
          <div class="row justify-content-around ">
            
            <div class="col-xl-4 col-lg-4 col-md-4 col-4 ">
              <div class="wrapper count-title d-flex justify-content-center">
                <div class="icon"><i class="icon-bag"></i></div>
                <div class="name"><strong class="">Compras</strong><span>hoy</span>
                  <div class="count-number">0</div>
                </div>
              </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-4">
              <div class="wrapper count-title d-flex justify-content-center">
                <div class="icon"><i class="icon-banknote"></i></div>
                <div class="name"><strong class="">Ventas</strong><span>hoy</span>
                  <div class="count-number">0</div>
                </div>
              </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-4">
              <div class="wrapper count-title d-flex justify-content-center">
                <div class="icon"><i class="icon-align-center"></i></div>
                <div class="name"><strong class="">Productos por agotarse</strong><span>hoy</span>
                  <div class="count-number">0</div>
                </div>
              </div>
            </div>
            </div>
          </div>
        
      </section>
    </div>
    <div class="row d-flex justify-content-end mr-3" >
      <a href="http://www.hdjgr.com.ve" class="navbar-brand" target="_blank" id="hdjgr">
        <img data-toggle="tooltip" data-placement="left" title="" style="width: 15%; position:absolute; bottom:5px; right: 5px" class="img" src="<?php echo PUBLIC_URL; ?>img/logo-EPOC-WEB.png" data-original-title="Visitar pagina del desarrollador">
      </a>
    </div>
    
</div>
<script>
  $(document).ready(function() {
    $('#hdjgr').click(function(event) {
      $('#hdjgr').blur();
    });
  });
</script>
      <!-- Header Section-->
 	
 	
 				
 					
 					
 					
 					