<!doctype html>
<html lang="us">
<head>
  <meta charset="utf-8">
  <title>Produccion</title>
  <link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">


  
</head>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
                            
<div id="page-wrapper">
            <div class="">

                <div class="row">
                    <div class="col-lg-12 ">
                        

                        <div  class="card cardH">
                        <div class="card-header" hidden>
                            <center><h3><o id="titulocard">Compras</o> <?php $ti=strtolower($this->g[0]['tienda']); echo "[".ucwords($ti)."] Sub-modelo ".$this->g[0]['subM'];  ?></h4></center>
                        </div>
                        
                        <div class="card-block" style="padding-bottom: 0px; ">                        
						<ul class="nav nav-tabs ml-3" role="tablist">
						  	<li class="active nav-item">
						  		<a data-toggle="tab" href="#insert" class="nav-link" id="ingresar">Ingresar factura</a>
						  	</li>
                            <!-- <li class="nav-item">
                            	<a class="nav-link" id="rec" style="cursor: not-allowed;"><o data-toggle="tooltip" data-placement="right" title="Debe seleccionar un producto para poder consultar su receta" id="tooltiprec">Recetario</o></a>
                            </li> -->
                            <li class="nav-item">
                            	<a data-toggle="tab" href="#consults" class="nav-link" id="consultas">Consultas</a>
                            </li>
						</ul>

						
						<div class="tab-content" >
							<center>
							    <div id="load" hidden>
							        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
							    </div>
							</center>
							<div class="row form-group">
								<div class="col-sm-12" style="margin-bottom: -1%">
									<?php if ($this->g[0]['modelo'] != null): ?>
			                            <div>
			                              	<img class="hidden-sm-down" style="float: right;" src="<?php $model=strtolower($this->g[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png">
			                              	<img width="25%" height="8%" class="hidden-sm-up" style="float: right;" src="<?php $model=strtolower($this->g[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png">
			                            </div>
	                        		<?php endif ?>
                        
                          			<input type="hidden" id="modelos" value="<?php echo $this->g[0]['idm']; ?>">
			                        <?php if (isset($this->_error)) {
			                            echo $this->_error;
			                        } ?>
			                        <?php if ($this->g[0]['modelo'] == null): ?>
			                            <div>
			                              <img class="hidden-sm-down" style="float: right;" src="<?php $model=strtolower($this->g[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $this->g[0]['udn']; ?>.png">
			                              <img width="25%" height="8%" class="hidden-sm-up" style="float: right;" src="<?php $model=strtolower($this->g[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $this->g[0]['udn']; ?>.png">
			                            </div>
			                        <?php endif ?>
								</div>
								<div class="col-sm-12" style="margin-bottom: -2%">
									<div class="row form-group d-flex justify-content-center">
										<div class="col-xs-12 col-sm-12 col-md-10 col-lg-6">
											<h4 class="text-white" style="background: #337ab7; border-radius: 4px; text-align: center" id="selectedpro"></h4>
										</div>
										
									</div>
								</div>

							</div>
							
						
                            <div id="insert" class="tab-pane fade in active " role="tabpanel">
                            	<div class="col-sm-12">
                            		<div class="alert alert-success" id="produccionOK" hidden>
	                                    <h4 id="datosproduccion"></h4>
	                                </div>
                            	</div>
                            	<div class="col-sm-12">
                            		<div class="alert alert-danger" id="produccionerror" hidden>
	                                    <h4 id="datosproduccion2"></h4>
	                                </div>
                            	</div>
                                
                            	<div class="form-group row">
	                                <div class="col-sm-12">
	                                    <h4 style="border-bottom: solid 1px #A5A5A5;">Datos de la factura</h4>
	                                </div>
	                                <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
	                                    <label class="control-label labels" style="float: left;">Fecha de la factura</label>
	                                    <input style="height: 30px" type="date" class="form-control form-control-sm fechac" name="fechac" id="fechac" autocomplete="off">
	                                </div>
	                                <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
	                                    <label class="control-label labels" style="float: left;">N° de factura</label>
	                                    <input style="height: 30px" type="text" class="form-control form-control-sm num_factura" name="num_factura" id="num_factura" autocomplete="off" placeholder="numero de factura">
	                                </div>
	                                <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
	                                    <label class="control-label labels" style="float: left;">Proveedor</label><span style="float: right; cursor: pointer; cursor: hand;" title="informacion del proveedor" data-toggle="tooltip" data-placement="top" class="fa fa-info-circle" id="infoproveedor" hidden></span>
	                                    <select name="selectp" id="selectp" class="form-control form-control-sm">
	                                    </select>
	                                </div>
	                            </div>

	                            <div class="form-group row d-flex justify-content-center">
	                            	<div class="col-xs-12">
	                            		<button class="btn btn-sm btn-outline-primary" id="btnseleccion" data-toggle="modal" data-target="#modalingredientes">Seleccionar productos</button>
	                            	</div>
	                            </div>
                            
                            	
                                    

                                    <!-- Modal de ingredientes-->
										  <div class="modal fade" id="modalingredientes">
										    <div class="modal-dialog modal-lg">
										      <div class="modal-content">
										        <!-- Modal Header -->
										        <div class="modal-header">
										          <h5 class="modal-title" >Seleccion de productos para la factura #: <o id="Facturanum"></o></h5>
										          <button type="button" class="close" data-dismiss="modal">&times;</button>
										        </div>
										        <!-- Modal body -->
										        <div class="modal-body">
										        	<div class="dataTable_wrapper">
				                                        <div class="table-responsive col-sm-12">
				                                            <table id="tablaingredientes" class="display table table-sm table-striped table-bordered table-hover" >
				                                                <thead class="theadH">
				                                                    <tr>
				                                                        <th>#</th>
				                                                        <th>Codigo</th>
				                                                        <th>Producto</th>
				                                                        <th>Marca</th>
				                                                        <th>Existencia</th>
				                                                        <th>Stock Min</th>
				                                                        <th>Stock Max</th>
				                                                        <th>Acciones</th>
				                                                    </tr>
				                                                </thead>
				                                                <tbody id="cuerpo_r"></tbody>
				                                            </table>
				                                        </div>
				                                    </div>
										        </div>
										        <!-- Modal footer -->
										        <div class="modal-footer">
										          <button type="button" class="btn btn-sm btn-outline-primary" data-dismiss="modal">Aceptar</button>
										        </div>
										      </div>
										    </div>
										  </div>
										<!-- fin modal -->

										<!-- Modal cantidades-->
                                      <div class="modal fade" id="modalcant">
                                        <div class="modal-dialog modal-sm">
                                          <div class="modal-content">
                                          
                                            <!-- Modal Header -->
                                            <div class="modal-header">
                                              <h5 class="modal-title" id="mtitle"></h5>
                                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            
                                            <!-- Modal body -->
                                            <div class="modal-body">
                                                <div id="" class="form-group row ml-1 mr-1">
                                                    <div class="col-xs-12" id="compra" hidden>
                                                      <label class="labels"  for="">Cantidad de <o id="cant1"></o></label>
                                                        <input type="text" class="form-control form-control-sm monto" name="cantidad1" id="cantidad1" placeholder="ej: 1.000,0000">
                                                    </div>
                                                    <div class="col-xs-12" id="consumo" hidden>
                                                      <label class="labels"  for="">Cantidad de <o id="cant2"></o></label>
                                                        <input type="text" class="form-control form-control-sm monto" name="cantidad2" id="cantidad2" placeholder="ej: 1.000,0000">
                                                    </div>
                                                    <div class="col-xs-12">
                                                      <label class="labels"  for="">Cantidad de <o id="cant3"></o></label>
                                                        <input type="text" class="form-control form-control-sm monto" name="cantidad3" id="cantidad3" placeholder="ej: 1.000,0000">
                                                    </div>
                                                    <div class="col-xs-12 mt-3">
                                                        <textarea class="form-control form-control-sm" rows="3" cols="200" name="comentario" id="comentario" placeholder="Observaciones.."></textarea>
                                                    </div>
                                                    <input type="hidden" id="idus">
                                                    <input type="hidden" id="idup">
                                                    <input type="hidden" id="iduc">
                                                    <input type="hidden" id="idpro">
                                                    <input type="hidden" id="idinve">
                                                </div>
                                            </div>
                                            
                                            <!-- Modal footer -->
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancelar</button>
                                              <button type="button" class="btn btn-sm btn-outline-primary" id="guardarm">Guardar</button>
                                            </div>
                                            
                                          </div>
                                        </div>
                                      </div> 
										<!-- fin modal -->

                                		<!-- Modal de informacion del proveedor-->
										  <div class="modal fade" id="modalinfoprov">
										    <div class="modal-dialog modal-sm">
										      <div class="modal-content">
										        <!-- Modal Header -->
										        <div class="modal-header">
										          <h5 class="modal-title" >Datos del proveedor: <br><o id="nombreprov"></o></h5>
										          <button type="button" class="close" data-dismiss="modal">&times;</button>
										        </div>
										        <!-- Modal body -->
										        <div class="modal-body">
										        	<div class="container">
										        		<div class="row form-group">
										        			<h5><b>RIF / RUC: </b><o id="rifprov"></o></h5>
										        		</div>
										        		<div class="row form-group">
										        			<h5><b>Razon social: </b><o id="razonprov"></o></h5>
										        		</div>
										        		<div class="row form-group">
										        			<h5><b>Correo electronico: </b><o id="correoprov"></o></h5>
										        		</div>
										        		<div class="row form-group">
										        			<h5><b>Direccion: </b><o id="estado"></o>, municipio <o id="municipio"></o>, parroquia<o id="parroquia"></o>. Urbanizacion <o id="urbanizacion"></o>, calle <o id="calle"></o>, Edif./local <o id="edificio"></o></h5>
										        		</div>
										        		<div class="row form-group">
										        			<h5><b>Telefono: </b><o id="tlf"></o></h5>
										        		</div>

										        	</div>
										        </div>
										        <!-- Modal footer -->
										        <div class="modal-footer">
										          <button type="button" class="btn btn-sm btn-outline-primary" data-dismiss="modal">Aceptar</button>
										        </div>
										      </div>
										    </div>
										  </div>
										<!-- fin modal -->

                                     <!--Modal compra directa-->
                                      <div class="modal" tabindex="-1" role="dialog" id="modalreposicion">
                                          <div class="modal-dialog " role="document">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title" id="titulorep"></h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                                </button>
                                              </div>
                                              <div class="modal-body">
                                                <form action="<?php echo BASE_URL;?>inventario/compraDirecta" method="post" accept-charset="utf-8">
                                                    <input type="hidden" name="idT" id="idtienda" value="<?php echo $this->g[0]['idT'];?>">
                                                    <input type="hidden" name="idP" id="idP2" >
                                                    <input type="hidden" name="unidad_medida_si" id="umsis">
                                                    <input type="hidden" name="motivo" id="motivo" value="122">
                                                <div class="form-group row ">
                                                    
                                                    <div class="col-sm-4">
                                                        <label class="control-label" style="float: left;">Contenido neto</label>
                                                        <div class="col-1 d-flex offset-10" id="glyphi" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                                        </div>
                                                        <input type="text" class="form-control form-control-sm contneto" name="contneto" id="contneto" autocomplete="off">
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label class="control-label" style="float: left;">Cant. comprada</label>
                                                        <div class="col-1 d-flex offset-10" id="glyphi" data-toggle="tooltip" data-placement="right" title="ya existe un producto con el mismo nombre y marca">
                                                        </div>
                                                        <input type="text" class="form-control form-control-sm" name="cantcomprada" id="cantcomprada" required>
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label class="control-label" style="float: left;">U/M Compra</label>
                                                        <select name="umcompra" class="form-control form-control-sm umc" id="umcompra" required>
                                                            <option value="selected disabled">Seleccione..</option>}
                                                        </select>
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label for="" class="control-label" style="float: left;">Conversion a <o id="conver"></o></label>
                                                        <input type="text" class="form-control form-control-sm formulac" name="formulacomp" id="formulacomp">
                                                    </div> 
                                                    <div class="col-sm-4" id="canti" hidden>
                                                        <label class="control-label" style="float: left;"><o id="up"></o><o class="uc"></o></label>
                                                        <input type="text" class="form-control form-control-sm cantix" name="cantix" id="cantix">
                                                    </div>
                                                    <div class="col-sm-8">
                                                        <label class="control-label" style="float: left;">Descripcion de compra</label>
                                                        <textarea class="form-control form-control-sm" rows="2" name="descripcion"></textarea>
                                                    </div>                                                 
                                                </div>
                                                
                                              </div>
                                              <div class="modal-footer">
                                                <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal">Cancelar</button>
                                                <input type="submit" class="btn btn-sm btn-outline-primary" value="Guardar">
                                              </div>
                                            </form>
                                            </div>
                                          </div>
                                        </div>
                                      <!-- fin de la modal compra directa -->
                            <!-- <div id="recetassemi" class="tab-pane fade in" role="tabpanel" hidden>
                            	<div class="col-sm-12 ml-3">
                            <h5 style="color: black" id="leyenda" class="ml-3"><img class="img mb-2" src="<?php echo PUBLIC_URL; ?>img/info.icon.png"> La receta mostrada corresponde a un rendimiento de <o id="infrece"></o></h5>
                          </div>
		                          <div class="dataTable_wrapper ">
		                            <h5 style="background: #ddd; text-align: center; margin-bottom: 5px; width: 88%; margin-left: 6%" id="titulo2"></h5>
		                             <div class="col-sm-12 table-responsive">    
		                              <div class="container">
		                                <table id="tablarecetario" class="display table table-sm table-striped table-bordered table-hover" >
		                                  <thead class="theadH">
		                                      <tr>
		                                          <th><center>Codigo</center></th>
		                                          <th><center>Ingrediente</center></th>
		                                          <th><center>Cantidad</center></th>
		                                          <th><center>U/M</center></th>
		                                          <th><center>Costo</center></th>
		                                      </tr>
		                                  </thead>
		                                  <tbody id="cuerpo_r"></tbody>
		                                  
		                              </table>
		                              <div class="container">
		                                <div class="row d-flex justify-content-start ml-3 mx-3 pl-1">
		                                  <div class="col-12" id="costot">
		                                    
		                                  </div>
		                                </div>
		                              </div>
		                            </div>
		                          </div>     
		                        </div>
		                        <div class="row d-flex justify-content-center">
			                        <div class="alert alert-success exporting" style="position: absolute; z-index: 99;" hidden>
		                              	<h4>Receta exportada con exito</h4>
		                            </div>
	                            	<img width="35px" height="35px" class="ocultos excel" src="<?php echo PUBLIC_URL;?>img\excel.png" id="excel2" hidden style="cursor: hand; cursor: pointer;" data-toggle="tooltip" data-placement="top" title="exportar receta para">
                            	</div>

                            </div> -->

                            <div id="consults" class="tab-pane fade in active " role="tabpanel">
	                            <div class="col-sm-12">
	                        		<div class="alert alert-success" id="reversada" hidden>
	                                    <center><h4> La producción ha sido reversada de forma exitosa</h4></center>
	                                </div>
	                        	</div>
	                        	<div class="col-sm-12">
	                        		<div class="alert alert-danger" id="errorreversar" hidden>
	                                    <center><h4> Ocurrio un error al intentar reversar la producción</h4><br>
	                                    <h5>Por favor intente nuevamente</h5></center>
	                                </div>
	                        	</div>                             
                            	<div class="col-xs-12" id="tablaoculta2">
                            		<div class="row form-group d-flex justify-content-center" >
	                            		<div class="col-xs-1" id="colbtnrev">
											<button class="btn btn-sm btn-outline-danger" id="btn-rev" value="1">Consultar reversos</button>
										</div>
									
	                            		<div class="col-xs-1 ml-3" id="colbtn">
											<button class="btn btn-sm btn-outline-primary" id="btn-filtro">Quitar filtro de producto seleccionado</button>
										</div>
									</div>
	                            			<div class="dataTable_wrapper ">

					                             <div class="col-sm-12 table-responsive">    
					                              <div class="container">                            	
					                                <table id="producidos" class="display table table-sm table-striped table-bordered table-hover" >
					                                  <thead class="theadH">
					                                      <tr>
					                                          <th><center>#</center></th>
					                                          <th><center>Codigo</center></th>
					                                          <th><center>Producto</center></th>
					                                          <th><center>marca</center></th>
					                                          <th><center>tandas</center></th>
					                                          <th><center>R/ideal</center></th>
					                                          <th><center>R/real</center></th>
					                                          <th><center>fecha</center></th>
					                                          <th><center>acciones</center></th>
					                                      </tr>
					                                  </thead>
					                                  <tbody id="cuerpo_r"></tbody>
					                                  
					                              </table>
					                              <div class="container">
					                                <div class="row d-flex justify-content-start ml-3 mx-3 pl-1">
					                                  <div class="col-12" id="costot">
					                                    
					                                  </div>
					                                </div>
					                              </div>
					                            </div>
					                          </div>     
					                        </div>
	                            		</div>

	                            		
                            </div>
                            	
                            </div>
                        </div>



                       
                            
                        </div>
                        <center><div id="mensaje" hidden><img width="45px" height="45px" src="http://localhost/COCAI/public/img/check1.gif" alt="exito"/></div></center>
                             
                        
                              
                
                </div>
              </div>
        </div>
</div>
</div>
                            
</body>

</div>



<!-- Autocomplete -->

</html>
