<head>
  <meta charset="utf-8">
  <title>Explosion</title>
</head>
<center>
    <div style="margin-top: 15%" id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
    <div id="page-wrapper">
            <div class="">

                <div class="row">
                    <div class="col-12 ">
                        

                        <div class="card cardH">

                            <div class="card-header" style="padding: 5px; height: 25%" hidden>
                              <center><h3 ><o id="titulocard">Rankings de ventas</o> <?php $ti=strtolower(str_replace('(PTY)', '', $this->model[0]['udn'])); echo "[".ucwords($ti)."]"; ?></h3></center>
                            </div>
                          
                          <div class="card-block ml-3">
                            <ul class="nav nav-tabs" role="tablist">
                              <li class="active nav-item">
                                <a data-toggle="tab" href="#consultar" class="nav-link" id="expconsulta">Consultas </a>
                              </li>
                              <li class="nav-item" id="tab-r">
                                <a   class="nav-link" id="expranking">Rankings pendientes por procesar</a>
                              </li>
                              
                            </ul>
                            <?php if ($this->model[0]['modelo'] != null): ?>
                                    <div>
                                      <img width="12%" height="10%" style="float: right;" src="<?php $model=strtolower($this->model[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-responsive" alt="">
                                    </div>
                                  <?php else: ?>
                                    <div>
                                      <img width="8%" height="8%" style="float: right;" src="<?php $model=strtolower($this->model[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $this->model[0]['udn']; ?>.png" class="img-responsive" alt="">
                                    </div>
                                <?php endif ?>
                            <div class="tab-content">
                              <div id="consultar" class="tab-pane fade in active mt-3" role="tabpanel">
                                <!-- <?php if (isset($this->_error)) {
                                    echo $this->_error;
                                } ?> -->
                                
                                
                                
                                <input type="hidden" name="codit" id="codit" value="<?php echo $this->model[0]['codigo']; ?>">
                                <input type="hidden" name="idudn" id="idudn" value="<?php echo $this->model[0]['idU']; ?>">
                                <!-- Small modal -->
                                

                                <div class="modal fade " tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="modalcerrado">
                                  <div class="modal-dialog modal-sm">
                                    <div class="modal-content" >
                                      <div class="modal-header">
                                        <h5 class="modal-title">Aviso!</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body" >
                                        <h5>Ya se genero la explosion correspondiente al dia en curso</h5>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" >
                                          Cerrar
                                        </button>
                                      </div>
                                      
                                    </div>
                                  </div>
                                </div>

                                    
                                  
                                    <div id="" class="form-group row ml-3">
                                        <div class="col-sm-3  col-md-3 col-lg-2 col-sm-offset-1">
                                            <label class="labels"  for="">Fecha de incio:</label>
                                              <input class="form-control form-control-sm" name="fecha_ini" id="fecha_ini" type="date">
                                        </div>
                                        <div class="col-sm-3 col-md-3 col-lg-2 ">
                                            <label class="labels"  for="">Fecha limite:</label>
                                              <input class="form-control form-control-sm test" name="fecha_fin" id="fecha_fin" type="date" disabled data-toggle="tooltip" data-placement="bottom" title="el valor debe ser posterior o igual a la fecha de inicio">
                                        </div>
                                    </div>
                                    <div class="container">
                                      <div class="row justify-content-center">
                                        <div class="col-1">
                                            <button class="btn btn-sm btn-outline-primary" id="consult" disabled>
                                              <o data-toggle="tooltip" data-placement="top" title="Seleccione un rango de fechas y haga click aqui para consultar el ranking de venta">Consultar</o>
                                            </button>
                                        </div>
                                      </div>
                                      
                                    </div>
                                    <br>

                        <center>
                            <div id="load" hidden>
                                <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
                            </div>
                        </center>

                        <div class="dataTable_wrapper " id="tablaoculta1" hidden>
                          <h3 style="border-bottom: solid 1px #A5A5A5;">Ranking de ventas</h3><br>
                             <div class="col-sm-12 table-responsive">
                                <table id="tablarank" class="table table-sm table-striped table-bordered table-hover" cellspacing="0" width="100%" >
                                  
                                    <thead class="theadH">
                                      <tr>
                                          <tr>                                                   
                                              <th><center>Codigo</center></th>
                                              <th><center>Producto</center></th> 
                                              <th><center>Grupo</center></th>
                                              <th><center>Cant</center></th>
                                              <th><center>Precio</center></th>
                                              <th><center>% Vta</center></th>
                                              <th><center>Costo</center></th>
                                              <th><center>Costo total</center></th>
                                              <th><center>% Costo</center></th>
                                              <th><center>fecha</center></th>
                                          </tr>
                                      </tr>
                                  </thead>
                                  <tbody id="cuerporank"></tbody>
                                  
                                </table><br>
                                <div class="row justify-content-center">
                                  <div class="col-sm-2">
                                    <button class="btn btn-sm btn-outline-primary" id="consultaingredientes">Ver explosion de ingredientes</button>
                                  </div>
                                </div> 
                              </div>  
                            </div>


                      <div class="" id="tabsexplotion" hidden>
                        <div class="modal fade " id="alerta2" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <div id="t2">Error!</div>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body" >

                                               <div id="cuerpo2"></div>
                                            </div>
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Aceptar</button>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->
                      
                            <ul class="nav nav-tabs " role="tablist">
                              <li class="nav-item" >
                                <a data-toggle="tab" href="#consolidado"  class="nav-link" id="consolid"> Consolidado de explosion de ingredientes </a>
                              </li>
                              <li class="active nav-item">
                                <a style="cursor: not-allowed;" class="nav-link" id="porpro">Explosion de ingredientes por productos </a>
                              </li>
                              
                              
                            </ul>
                      <div class="tab-content">
                              <div id="porproductos" class="tab-pane fade in active mt-3" role="tabpanel">
                        <div class="dataTable_wrapper " id="tablaoculta" hidden>                          
                             <div class="col-sm-12 table-responsive">
                                <table id="tablaexplosion" class="table table-sm table-striped table-bordered table-hover" cellspacing="0" width="100%" >
                                  
                                    <thead class="theadH">
                                      <tr>
                                          <th><center>#</center></th>
                                          <th><center>codigo</center></th>
                                          <th><center>Ingrediente</center></th>
                                          <th><center>Cantidad</center></th>
                                          <th><center>Costo</center></th>
                                          <th><center>Costo total</center></th>
                                          <th><center>Fecha</center></th>
                                          <th><center>Producto</center></th>
                                      </tr>
                                  </thead>
                                  <tbody id="cuerpo"></tbody>
                                  
                              </table>
                                       
                                </div>
                            </div>
                          </div>
                        </div>

                        <div class="tab-content">
                            <div id="consolidado" class="tab-pane fade in mt-3" role="tabpanel">
                              <div id="conso" hidden>
                              <div class="form-group row ml-3">
                                <div class="col-sm-2">
                                  <label>Tipo de Inventario</label>
                                  <div class="input-group">
                                    <select class="form-control form-control-sm" id="tipo_inventario">
                                    </select>
                                    <span class="input-group-btn">
                                      <button class="btn btn-sm btn-outline-primary" type="button" id="ojo" disabled><i class="fa fa-eye"></i></button>
                                    </span>
                                  </div>
                                </div>
                              </div>
                              <div class="dataTable_wrapper " id="tablaoculta2" hidden>                                
                                   <div class="col-sm-12 table-responsive">
                                      <table id="tablaexplosion2" class="table table-sm table-striped table-bordered table-hover" cellspacing="0" width="100%" >
                                        
                                          <thead class="theadH">
                                            <tr>
                                                <th><center>#</center></th>
                                                <th><center>codigo</center></th>
                                                <th><center>Ingrediente</center></th>
                                                <th><center>Cant.usada</center></th>
                                                <th><center>Exist. teorica</center></th>
                                                <th><center>Exist. Real</center></th>
                                                <th><center>Diferencias</center></th>
                                                <th><center>costo</center></th>
                                                <th><center>Costo total</center></th>
                                            </tr>
                                        </thead>
                                        <tbody id="cuerpo"></tbody>
                                        
                                    </table>
                                             
                                      </div>
                                  </div>
                                  </div>
                            </div>
                        </div>

                        </div>

                                     <!-- <div id="" class="form-group row">
                                        <div class="col-sm-3 col-sm-offset-1">
                                            <label class="labels" for="">Tipo de mov.:</label>
                                              <select  id="tipoMov" name="tipoMov"  class="form-control form-control-sm" disabled>
                                                <option selected disabled value="seleccione">Seleccione..</option>
                                                <option value="131">Entradas</option>
                                                <option value="132">Salidas</option>
                                              </select>
                                        </div>
                                        <div class="col-sm-3">
                                              <label class="labels" for="">Motivo:</label>
                                              <select id="motivo" name="motivo" class="form-control form-control-sm" disabled>
                                                <option selected disabled value="seleccione">Seleccione..</option>
                                              </select>
                                        </div>
                                        
                                            <input type="hidden" name="mercancia_id" id="mercid" >
                                            <input type="hidden" name="tiendae" id="tiendae" value="<?php echo $this->idu;?>">
                                            <input type="hidden" name="status_id" id="status_id" value="126">
                                      </div> -->
            
                                          

                                    
                                    

                              </div>
                              <div id="generar" class="tab-pane fade in active mt-3" role="tabpanel">
                                <!-- Small modal -->
                                

                                <div class="modal fade " tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="modaladvertencia">
                                  <div class="modal-dialog modal-sm">
                                    <div class="modal-content" >
                                      <div class="modal-header">
                                        <h5 class="modal-title">Aviso!</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <h5>Existen varios rankings por procesar, verifique la fecha de los mismos y proceda a cargarlos de forma ordenada.</h5>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" >
                                          Cerrar
                                        </button>
                                      </div>
                                      
                                    </div>
                                  </div>
                                </div>

                                <div id="cuerpor">
                                  
                                </div>
                                
                                
                                
                                <input type="hidden" name="idudn" id="idudn" value="<?php echo $this->model[0]['idU']; ?>">
                                

                              </div>
                              
                          </div>
                          <div class="col-sm-12">
                            <h5 style="color: black" id="leyenda" class="mt-3"><img class="img mb-2" src="<?php echo PUBLIC_URL; ?>img/info.icon.png"> Para consultar la explosion de ingredientes, primero debe haber cargado el inventario correspondiente, luego consultar el ranking de venta correspondiente. </h5>
                          </div>
      
                        </div>
</div>
      <!-- Header Section-->
 	
 	
 				
 					
 					
 					
 					