<!DOCTYPE html>
<!-- saved from url=(0040)http://getbootstrap.com/examples/signin/ -->
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="description" content="">
    <meta name="author" content="">
   <link rel="icon" type="image/png" href="<?php echo PUBLIC_URL; ?>img/favicon.ico" />

        <title>EPOC-WEB</title>


    <!-- Bootstrap core CSS 
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template 
    <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">-->

     <link href="<?php echo PUBLIC_URL; ?>/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
   
    <link href="<?php echo PUBLIC_URL; ?>css/sb-admin-2.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="./Signin Template for Bootstrap_files/ie-emulation-modes-warning.js"></script><style type="text/css"></style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

 <body>

    <div class="container">

    