<!doctype html>
<html lang="us">
<head>
  <meta charset="utf-8">
  <title>COCAI - Adm. Usuarios</title>
  <link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">
</head>
<body>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>    
<input type="hidden" name="" id="idtienda" value="<?php echo $this->g[0]['idT']?>">
<input type="hidden" name="" id="idempr" value="<?php echo $this->g[0]['empresa_id']?>">                       
  <div id="page-wrapper">
    <div class="row">
      <div class="col-lg-12 ">
        <div  class="card cardH">
          <div class="card-header" hidden>
              <center><h3><o id="titulocard">Administración de Tablas</o> <?php $ti=strtolower($this->g[0]['tienda']); echo "[".ucwords($ti)."] Sub-modelo ".$this->g[0]['subM'];  ?></h3></center>
          </div>
          <div class="card-block" style="padding-bottom: 0px; ">
            <div class="alert alert-success" id="creado" hidden>
              <h4><o class="campo"></o> creada de forma exitosa</h4>
            </div>
            <div class="alert alert-success" id="borrado" hidden>
              <h4><o class="campo"></o> Eliminada de forma exitosa</h4>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <label class="labels">Tabla</label>
                    <div class="input-group">
                        <select name="tabla" id="tabla" class="form-control form-control-sm">
                            <option value="" selected="" disabled="">Seleccione..</option>
                            <option value="clasificacion">Clasificaciones</option>
                            <option value="subclasificacion">Sub Clasificaciones</option>
                        </select>
                        <div class="input-group-btn">
                            <button class="btn btn-sm btn-outline-primary" type="button" id="continuar" disabled>Continuar</button>
                        </div>
                        <div class="input-group-btn">
                            <button class="btn btn-sm btn-outline-info" type="button" id="add" disabled>Agregar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3" id="results" hidden>
                <div class="col-sm-12">
                    <div class="dataTable_wrapper">
                      <div class="table-responsive col-sm-12">
                        <table id="tablas" class="display table table-sm table-striped table-bordered table-hover" >
                          <thead class="theadH">
                            <tr>
                              <th colspan="3"><center id="tipotablas"></center></th>
                            </tr>
                            <tr>
                              <th>#</th>
                              <th id="campo"></th>
                              <th>Eliminar</th>
                            </tr>
                          </thead>
                          <tbody id="bodytabla">
                          </tbody>
                        </table>
                      </div>
                    </div>
                </div>
            </div>

            <!-- MODAL DE AGREGAR SUB_FAMILIAS NUEVAS-->
                    <div class="modal fade " id="modalagregar" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div id="t"><h6>Agregar <o class="campo"></o></h6></div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body" >

                                   <div id="cuerpo"></div>
                                   <div class="form-group">
                                    <div class="col-sm-12">
                                      <label class="labels">Nombre de <o class="campo"></o></label>
                                      <input type="text" id="nueva" class="form-control form-control-sm">
                                    </div>
                                   </div>
                                    
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" id="mcancelar">Cancelar</button>
                                  <button type="button" class="btn btn-sm btn-outline-primary" id="mcontinuar">Continuar</button>
                                </div>   
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->

                    <!-- MODAL DE AGREGAR SUB_FAMILIAS NUEVAS-->
                    <div class="modal fade " id="modaldelete" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div id="t"><h6>Confirmar eliminacion</h6></div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body" >

                                   <div class="row">
                                     <div class="col-sm-12">
                                      <input type="hidden" id="idborrar">
                                       <h5>Esta por eliminar este regstro desea continuar?</h5>
                                     </div>
                                   </div>
                                    
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal">Cancelar</button>
                                  <button type="button" class="btn btn-sm btn-outline-primary" id="confirmdelete">Si, Continuar</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
          </div>    
        </div>
      </div>
    </div>
  </div>        
</div>
</body>
</html>
