        <div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header"></h1>
                        <div class="container">
                            <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                      <div class="modal fade opciones" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                          <div class="modal-dialog modal-sm" role="document">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                      </button>
                                      <h4 class="modal-title">Modificar sub-modelo</h4>
                                  </div>
                                  <div class="modal-body">
                                      <h4>Seleccione la opcion que desea administrar.</h4>
                                      <div class="col-sm-12">
                                          <div class="col-sm-6" id="grupos"></div>
                                          <div class="col-sm-6" id="productos"></div>
                                      </div>
                                  </div>   
                              </div><!-- /.modal-content -->
                          </div><!-- /.modal-dialog -->
                      </div><!-- /.modal -->
                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS --> 
                        </div>
                    </div>
                 </div>
            </div>
                    <!-- /.col-lg-12 -->
        </div>
                <!-- /.row -->
                </div>
            <!-- /.container-fluid -->
            </div>
        <!-- /#page-wrapper -->
 		<!-- no borrar -->
 		</div>

 	
 	
 				
 					
 					
 					
 					