<!doctype html>
<html lang="us">
<head>
  <meta charset="utf-8">
  <title>Centro de reportes</title>
  <link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">


  
</head>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
                            
<div id="page-wrapper">
            <div class="">

                <div class="row">
                    <div class="col-lg-12 ">
                        <div  class="card cardH">
                        <div class="card-header" hidden>
                            <center><h3><o id="titulocard">Centro de reportes</h4></center>
                        </div>
                        <div class="card-block" style="padding-bottom: 0px; ">                        
							<center>
							    <div id="load" hidden>
							        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
							    </div>
							</center>
							<div class="row form-group">
								<div class="col-sm-12" style="margin-bottom: -3%">
		                            <div>
		                              	<img class="hidden-sm-down" style="float: right;" src="<?php echo PUBLIC_URL;?>img\ivss.png">
		                              	<img width="25%" height="8%" class="hidden-sm-up" style="float: right;" src="<?php echo PUBLIC_URL;?>img\ivss.png">
		                            </div>
	                        	</div>
								<div class="col-sm-12" style="margin-bottom: -2%">
									<div class="row form-group d-flex justify-content-center">
										<div class="col-xs-12 col-sm-12 col-md-10 col-lg-6">
											<h4 class="text-white" style="background: #337ab7; border-radius: 4px; text-align: center" id="selectedpro"></h4>
										</div>
									</div>
								</div>
							</div>
							

							
						
                            
                            	<div class="col-sm-12">
                            		<div class="alert alert-success" id="produccionOK" hidden>
	                                    <h4 id="datosproduccion"></h4>
	                                </div>
                            	</div>
                            	<div class="col-sm-12">
                            		<div class="alert alert-danger" id="produccionerror" hidden>
	                                    <h4 id="datosproduccion2"></h4>
	                                </div>
                            	</div>
                        <div class="row form-group row ml-3">
							<div class="col-sm-3" id="colsmselect">
								<label class="labels">Almacen</label>
								<select name="idudn" id="idudn" class="form-control form-control-sm resizeselect">
									<option value="" selected disabled>Seleccione..</option>
									<option value="516">Almacen general</option>
									<option value="520">Suministros</option>
									<option value="522">B-15</option>
								</select>
							</div>
							<div class="col-sm-3" id="colsmselect">
								<label class="labels">Tipo de reporte</label>
								<select name="tiporeporte" id="tiporeporte" class="form-control form-control-sm resizeselect">
									<option value="" selected disabled>Seleccione..</option>
									<option value="1">Movimientos de kardex</option>
									<option value="2">Listado de productos</option>
									<option value="3">Listado de Proveedores</option>
									<option value="4">Inventario en almacén</option>
									<option value="5">Valoración de existencias</option>
									<option value="6">Análisis de rotación de existencias</option>
									<option value="7">Lista de posición de inventario por producto</option>
									<option value="8">Compras</option>
									<option value="9">Margen de utilidad por articulo</option>
									<option value="10">Proyección de re-abastecimiento de materiales</option>
									<option value="11">Cuentas por pagar a proveedores</option>
									<option value="12">Impresión del estado de cuenta de proveedores</option>
									<option value="13">Reporte de excepciones</option>
								</select>
							</div>
						</div>

						<div id="seccionKardex" hidden>
                            <fieldset>
                          
                            <div id="" class="form-group row ml-3">
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3 ">
                                    <label class="labels"  for="">Fecha de incio:</label>
                                      <input class="form-control form-control-sm" name="fecha_ini" id="fecha_ini" type="date">
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3">
                                    <label class="labels"  for="">Fecha limite:</label>
                                      <input class="form-control form-control-sm test" name="fecha_fin" id="fecha_fin" type="date" disabled data-toggle="tooltip" data-placement="bottom" title="el valor debe ser posterior o igual a la fecha de inicio">
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3 ">
                                    <label class="labels" for="">Producto:</label>
                                      <select  id="products" name="productos"  class="form-control form-control-sm" disabled>
                                        <option selected disabled value="seleccione">Seleccione..</option>
                                      </select>
                                </div>
                            </div>

                             <div id="" class="form-group row ml-3">
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3 ">
                                    <label class="labels" for="">Tipo:</label>
                                      <select  id="tipoMov" name="tipoMov"  class="form-control form-control-sm" disabled>
                                        <option selected disabled value="seleccione">Seleccione..</option>
                                        <option value="131">Entradas</option>
                                        <option value="132">Salidas</option>
                                        <option value="all">Todos</option>
                                      </select>
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3" id="mot">
                                      <label class="labels" for="">Motivo:</label>
                                      <select id="motivo" name="motivo" class="form-control form-control-sm" disabled>
                                        <option selected disabled value="seleccione">Seleccione..</option>
                                      </select>
                                </div>
                                
                                    
                              </div>
                                    <input type="hidden" name="mercancia_id" id="mercid" >
                                    <input type="hidden" name="idt" id="idt" value="<?php echo $this->model[0]['idU'];?>">
                                    <input type="hidden" name="idemp" id="idemp" value="<?php echo $this->model[0]['empresa_id'];?>">
                                    <input type="hidden" name="unidad" id="unidad">
                                    <input type="hidden" name="status_id" id="status_id" value="126">
                            
                        </fieldset>
                        <div class="container">
                              <div class="row d-flex justify-content-center">
                                <div>
                                  <div class="col">
                                    <input  type="button" class="btn btn-sm btn-outline-primary"  id="consult" value="Consultar">
                                  </div>
                                </div>
                              </div>
                              
                            </div>
                        </div>
                        	<div class="row d-flex justify-content-center mt-3" id="barradefiltro">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2 ">
                                    <label class="labels" style="float: left;">Grupo</label>
                                    <div class="col-xs-1 d-flex offset-11" >
                                      <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="En este campo debe seleccionar el elemento que permitirá especificar a que grupo pertenece el producto."></span>
                                    </div>
                                    <select name="grupo" id="grupo" class="form-control form-control-sm selectag" required>
                                    </select>
                                    <input type="hidden" name="grupo" id="grupoid">
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2 ">
                                    <label class="labels" style="float: left;">Clasificación</label>
                                    <div class="col-xs-1 d-flex offset-11" >
                                      <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="En este campo debe especificar la clasificación del grupo al que pertenece el producto."></span>
                                    </div>
                                    <select name="familia" id="familia2" class="form-control form-control-sm familia selectag" required> 
                                      <option value="">Seleccione..</option>
                                    </select>
                                    <input type="hidden" name="familia" id="familiaid">
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2 ">
                                    <label class="labels" style="float: left;">Sub clasificación</label>
                                    <div class="col-xs-1 d-flex offset-11" >
                                      <span style="cursor: help;" class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="En este campo debe especificar la Sub clasificación de la clasificación del grupo al que pertenece el producto."></span>
                                    </div>
                                    <select name="subfamilia" id="sub_familia" class="form-control form-control-sm selectag"> 
                                      <option value="">Seleccione..</option>
                                    </select>
                                    <input type="hidden" name="subfamilia" id="subfamiliaid">
                                </div>
                                <div class="col-xs-1 ml-3 mt-2">
                                    <div class="row" style="height: 15px">
                                        <label class="labels" style="float: left;">Color</label>
                                    </div>
                                    
                                    <div class="row " style="height: 20px">
                                        <div class="col-xs-6">
                                          <label class="custom-control custom-radio" data-toggle="tooltip" data-placement="top" title="Productos con existencias en cero" style="margin-right: 0px">
                                            <input type="radio" class="custom-control-input colorf" id="c1" name="color" value="1">
                                            <span class="custom-control-indicator" style="background: #FEC4C4; margin-left: 1px;"></span>
                                            <span class="custom-control-description" style="line-height: 1.8;"></span>
                                          </label>
                                          <label class="custom-control custom-radio" style="margin-right: 0px" data-toggle="tooltip" data-placement="top" title="Productos con existencias por debajo del stock minimo">
                                            <input type="radio" class="custom-control-input colorf" id="c2" name="color" value="2">
                                            <span class="custom-control-indicator" style="background: #FEE1C4; margin-left: 1px"></span>
                                            <span class="custom-control-description" style="line-height: 1.8;"></span>
                                          </label>
                                          
                                          <label class="custom-control custom-radio" style="margin-right: 0px" data-toggle="tooltip" data-placement="top" title="Productos con existencias por debajo del punto de reorden">
                                            <input type="radio" class="custom-control-input colorf" id="c3" name="color" value="3">
                                            <span class="custom-control-indicator" style="background: #FFFFA3; margin-left: 1px;"></span>
                                            <span class="custom-control-description" style="line-height: 1.8;"></span>
                                          </label>
                                          <label class="custom-control custom-radio" style="" data-toggle="tooltip" data-placement="top" title="Productos con existencias entre el punto de reorden y el stock maximo">
                                            <input type="radio" class="custom-control-input colorf" id="c4" name="color" value="4">
                                            <span class="custom-control-indicator" style="background: #BBFFBB; margin-left: 1px"></span>
                                            <span class="custom-control-description" style="line-height: 1.8;"></span>
                                          </label>
                                            <input type="hidden" id="inputcolor">;
                                        </div>
                                    </div>
                                    <div class="row" style="height: 20px">
                                        
                                    </div>
                                </div>
                                        
                                <div class="col-sm-1 mt-1" style="padding-left: 0px">
                                    <button type="button" id="filtra2" class="btn btn-sm btn-outline-primary mt-3">Filtrar</button>
                                </div>
                            </div>
                            

										<center>
										    <div id="loading" hidden>
										        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
										    </div>
										</center>
										

					<div class="dataTable_wrapper " id="tablaoculta" hidden>
                             <div class="col-sm-12 table-responsive">
                                <table id="tablakardex" class="table table-sm table-striped table-bordered table-hover" cellspacing="0" width="100%" >
                                    <thead class="theadH">
                                      <tr>
                                          <th>Codigo</th>
                                          <th>Producto</th>
                                          <th>Grupo</th>
                                          <th>Fecha</th>
                                          <th>Tipo</th>
                                          <th>Motivo</th>
                                          <th>Cantidad</th>
                                          <th>Existencia</th>
                                          <!-- <th>Descripcion</th> -->
                                          <th>Usuario</th>
                                          <th>cant</th>
                                      </tr>
                                  </thead>
                                  <tfoot class="theadH">
                                      <tr>

                                          <th colspan="3" style="text-align:left;" >Total Entrada: <o id="entra"></o></th>
                                          <th colspan="3" style="text-align:left;" >Total Salida: <o id="sale"></o></th>
                                          <th colspan="2" ></th>
                                      </tr>
                                  </tfoot>
                                  
                                  
                                  <tbody id="cuerpo"></tbody>
                                  
                              </table>
                              <div align="center">
                                   <input type="button" class="btn btn-sm btn-outline-primary exportar" value="Impresion">
                              </div>
                                       
                                </div>
                            </div>

                    <div id="tablaoculta2" hidden>
											<div class="form-group row">										
												<div class="col-sm-12">
				                                    <h4 style="border-bottom: solid 1px #A5A5A5;"><o class="tituloSeccion"></o></h4>
				                                </div>
			                                </div>
											<div class="dataTable_wrapper ">
					                            <div class="col-sm-12 table-responsive">    
					                              <div class="">                            	
					                                <table id="tablacompra" class="display table table-sm table-striped table-bordered table-hover" >
					                                  <thead class="theadH">
					                                      <tr>
					                                          <th><center>#</center></th>
					                                          <th><center>Codigo</center></th>
					                                          <th><center>Producto</center></th>
					                                          <th><center>Cantidad</center></th>
					                                          <th><center>Total</center></th>
					                                          <th><center>Acciones</center></th>
					                                      </tr>
					                                  </thead>
					                                  <tbody id="cuerpo_r"></tbody>
					                                  
					                              </table>
					                              <div class="container">
					                                <div class="row d-flex justify-content-start ml-3 mx-3 pl-1">
					                                  <div class="col-12" id="costot">
					                                    
					                                  </div>
					                                </div>
					                              </div>
					                            </div>
					                          </div>     
					                        </div>
					                        <div id="botones" hidden>
					                        	<div class="row d-flex justify-content-center" >
												  	<div class="col-xs-12 col-sm-12 col-md-2 col-lg-1" style="padding: 0px;">
												  		<button class="btn btn-sm btn-outline-danger" id="cancelarproceso" >Cancelar</button>
												  	</div>
												  	<div class="col-xs-12 col-sm-12 col-md-2 col-lg-1" style="padding: 0px;">
												  		<button class="btn btn-sm btn-outline-primary" id="procesar">Registrar factura</button>
												  	</div>
												</div>
					                        </div>
					                        	<div class="row d-flex justify-content-center" >
													<span class="parpadea text"  id="enviando" hidden>Procesando, por favor espere</span>
												</div>
					                        
										</div>

	
        		
</div>
    	
</div>
</div>



                       
                            
                        </div>
                        <center><div id="mensaje" hidden><img width="45px" height="45px" src="http://localhost/COCAI/public/img/check1.gif" alt="exito"/></div></center>
                             
                        
                              
                
                
              </div>
        </div>
</div>
</div>
                            
</body>

</div>



<!-- Autocomplete -->

</html>
<!-- <script>
	(function($, window){
  var arrowWidth = 20;


  $.fn.resizeselect = function(settings) {  
    return this.each(function() { 

      $(this).change(function(){
        var $this = $(this);

        // create test element
        var text = $this.find("option:selected").text();
        
        var $test = $("<span>").html(text).css({
        	"font-size": $this.css("font-size"), // ensures same size text
          "visibility": "hidden" 							 // prevents FOUC
        });
        

        // add to body, get width, and get out
        $test.appendTo($this.parent());
        var width = $test.width();
        if (width == 0) {
        	width = 80;
        	$("#colsmselect").removeClass('col-sm-3');
        	$("#colsmselect").removeClass('col-sm-4');
        	$("#colsmselect").addClass('col-sm-2');
        }else if (width < 170 && width >0) {
        	var width = $test.width();
        	$("#colsmselect").removeClass('col-sm-3');
        	$("#colsmselect").removeClass('col-sm-4');
        	$("#colsmselect").addClass('col-sm-2');
        }else if (width >200) {
        	var width = $test.width();
        	$("#colsmselect").removeClass('col-sm-2');
        	$("#colsmselect").removeClass('col-sm-3');
        	$("#colsmselect").addClass('col-sm-4');
        }else{
        	var width = $test.width();
        	$("#colsmselect").removeClass('col-sm-2');
        	$("#colsmselect").removeClass('col-sm-4');
        	$("#colsmselect").addClass('col-sm-3');
        }
        $test.remove();
        alert(width);
        // set select width
        $this.width(width + arrowWidth);

        // run on start
      }).change();

    });
  };

  // run by default
  $("select.resizeselect").resizeselect();                       

})(jQuery, window);
</script> -->
