<!doctype html>
<html lang="us">
<head>
  <meta charset="utf-8">
  <title>jQuery UI Example Page</title>
  <link href="<?php echo PUBLIC_URL; ?>css/jquery-ui.css" rel="stylesheet">

  <style>
    .labels{
      margin-bottom: -1%;
      float: left;
    }

  /* Tooltip */
  .test + .tooltip > .tooltip-inner {
      background-color: #337ab7; 
      color: #FFFFFF; 
      border: none; 
      padding: 1px;
      font-size: 14px;
  }
  /* Tooltip on top */
  .test + .tooltip.top > .tooltip-arrow {
      border-top: 5px solid #337ab7;
  }
  /* Tooltip on bottom */
  .test + .tooltip.bottom > .tooltip-arrow {
      border-bottom: 5px solid #337ab7;
  }
  /* Tooltip on left */
  .test + .tooltip.left > .tooltip-arrow {
      border-left: 5px solid #337ab7;
  }
  /* Tooltip on right */
  .test + .tooltip.right > .tooltip-arrow {
      border-right: 5px solid #337ab7;
  }
  .tdleft{
    text-align: left;
  }
  .tdcenter{
    text-align: center;
  }
  .tdright{
    text-align: right;
  }

  /*autocomplete style for modal*/
.ui-menu .ui-menu-item a {
  font-size: 12px;
}
.ui-autocomplete {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1051 !important;
  float: left;
  display: none;
  min-width: 160px;
  _width: 160px;
  padding: 4px 0;
  margin: 2px 0 0 0;
  list-style: none;
  background-color: #ffffff;
  border-color: #ccc;
  border-color: rgba(0, 0, 0, 0.2);
  border-style: solid;
  border-width: 1px;
  -webkit-border-radius: 2px;
  -moz-border-radius: 2px;
  border-radius: 2px;
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -webkit-background-clip: padding-box;
  -moz-background-clip: padding;
  background-clip: padding-box;
  *border-right-width: 2px;
  *border-bottom-width: 2px;
}
.ui-menu-item > a.ui-corner-all {
    display: block;
    padding: 3px 15px;
    clear: both;
    font-weight: normal;
    line-height: 18px;
    color: #555555;
    white-space: nowrap;
    text-decoration: none;
}
.ui-state-hover, .ui-state-active {
      color: #ffffff;
      text-decoration: none;
      background-color: #0088cc;
      border-radius: 0px;
      -webkit-border-radius: 0px;
      -moz-border-radius: 0px;
      background-image: none;
}
#modalIns{
    width: 500px;
}
  </style>


  
</head>
<center>
    <div id="gifcargando">
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>
<div id="body" hidden>
                            
<div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12 ">
                        

                        <div style="margin-top: 2%" class="card cardH">
                        <div class="card-header">
                            <center><h3><o id="titulocard">Recetario</o> <?php $ti=strtolower($this->model[0]['udn']); echo "[".ucwords($ti)."]"; ?></h3></center>
                        </div>
                        <div class="card-block">
                          

                          <!-- Modal -->
                              <div class="modal fade" id="modalrec" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" ><b>Crear receta</b></h5>
                                    </div>
                                    <div class="modal-body">
                                    <div id="cuerpo"></div>                             
                                    </div>
                                <div class="container">
                                  <div class="row justify-content-center" id="bots">
                                 
                                  </div>
                                </div>
                                    <div class="modal-footer">
                                    </div>
                                  </div>
                                </div>
                              </div>
                        
                        <?php if (isset($this->_error)) {
                            echo $this->_error;
                        } ?>
                        <?php if ($this->model[0]['modelo'] == null): ?>
                            <div>
                              <img width="8%" height="8%" style="float: right;" src="<?php $model=strtolower($this->model[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $this->model[0]['udn']; ?>.png" class="img-responsive" alt="">
                            </div>
                        <?php endif ?>
                        
                        
                        <div class="well">
                        <input type="hidden" name="idudn" id="idudn" value="<?php echo $this->model[0]['idU']; ?>">
                        <?php if (is_null($this->model[0]['empresa_id'])): ?>
                            <fieldset id="selectmodelos">
                            
                          
                            <div id="datos1" class="form-group col-sm-11">
                              <div class="row">
                                <div class="col-sm-3 col-sm-offset-1">
                                    <label class="labels"  for="">Modelo:</label>
                                      <select id="modelo_id" name="modelo_id"  class="form-control">
                                      </select>
                                      
                                </div>
                                <div class="col-1 ">
                                  <label class=""  for=""></label>
                                  <input type="button" style="margin-top: 5%" class="btn btn-sm btn-outline-primary" id="consult" name="consult" value="Consultar" disabled>
                                </div>

                                  


                              </div>     
                            </div>
                            
                            
                            
                          </fieldset>
                        <?php else: ?>
                          <script>
                            $(document).ready(function() {
                                verproductos(<?php echo $this->model[0]['idm']; ?>);                                
                            });
                          </script>
                        <?php endif ?>
                        
                                               
                        </div>
                        <center>
    <div id="load" hidden>
        <img width="120px" height="120px" class="img" src="<?php echo PUBLIC_URL; ?>img/cargando2.gif">
    </div>
</center>

                        <div style="margin-bottom: 1px; margin-top: 2%" class="card" id="tablaoculta" hidden>
                        <h4 style="background: #eee; padding: 1%; text-align: center; margin-top: 0%" id="titulo"><b>Productos de venta</b></h4>
                        <?php if ($this->model[0]['modelo'] != null): ?>
                            <div>
                              <img width="10%" height="10%" style="float: right;" src="<?php $model=strtolower($this->model[0]['modelo']); echo PUBLIC_URL;?>img\<?php echo $model; ?>.png" class="img-responsive" alt="">
                            </div>
                        <?php endif ?>
                          <div class="card-block mt-3">
                        

                          <div class="dataTable_wrapper " >
                             <div class="col-sm-12 table-responsive">
                             
                                <table id="tablaproduct" class="table table-sm table-striped table-bordered table-hover" >
                                  <thead class="theadH">
                                      <tr>
                                          <th><center>Codigo</center></th>
                                          <th><center>Nombre</center></th>
                                          <th><center>costo</center></th>
                                          <th><center>precio unit.</center></th>
                                          <th><center>receta</center></th>
                                      </tr>
                                  </thead>
                                  <tbody id="cuerpo"></tbody>
                                  
                              </table>
                                       
                                </div>
                                
                            </div>
                            </div>

                        </div>
                        <center><div id="mensaje"></div></center>
                             
                        <div class="card" id="recetasysubs" hidden>

                          

                          <ul class="nav nav-tabs justify-content-start">
                            <li class="nav-item">
                            <a id="dh" class="nav-link active" style="cursor: hand; cursor: pointer;"><b style="font-size: 12px;"></b>Receta</a></li>
                            
                            <!--<li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
                            <li><a data-toggle="tab" href="#menu3">Menu 3</a></li>-->
                          </ul>

                              

                        <div id="hidetab">
                        <h4 style="background: #eee; padding: 1%; text-align: center; margin-top: 0%" id="titulo2"></h4>
                          <div class="panel-body">
                          

                          <div class="dataTable_wrapper " >
                             <div class="col-sm-12 table-responsive">
                             
                                <table id="tablarecetario" class="display table table-sm table-striped table-bordered table-hover" >
                                  <thead class="theadH">
                                      <tr>
                                          <th><center>Codigo</center></th>
                                          <th><center>Ingrediente</center></th>
                                          <th><center>Cantidad</center></th>
                                          <th><center>U/M</center></th>
                                          <th><center>Precio Unitario</center></th>
                                          <th><center>Acciones</center></th>

                                      </tr>
                                  </thead>
                                  <tbody id="cuerpo_r"></tbody>
                                  
                              </table>
                              <div class="container">
                              <div class="row justify-content-center">
                                  <div class="col-1">

                                    <button class="btn btn-sm btn-outline-primary filtro" value="1" id="btnagregar" data-toggle="modal" data-target="#modaling">agregar ingrediente</button>
                                  </div>                                  
                                </div>
                              </div>
                              
                            </div>
                              
                                       
                                </div>
                                
                            </div>
                            </div>
                            </div>



                            <!--<div id="subreceta" class="tab-pane fade">
                              <h3>Sub recetas</h3>
                              <p>tabla con las subrecetas</p>
                            </div>
                            <div id="menu2" class="tab-pane fade">
                              <h3>Menu 2</h3>
                              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
                            </div>
                            <div id="menu3" class="tab-pane fade">
                              <h3>Menu 3</h3>
                              <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                            </div>-->


                        </div>


                        <!-- Modal informacion de conversion de existencia-->
                            <div class="modal fade " id="modaldelete" role="dialog">
                              <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h5 class="modal-title" ><b id="t">Eliminar ingrediente</b></h5>
                                  </div>
                                  <div class="modal-body" id="cuerpodelete">                                    
                                  </div>
                                  <div class="modal-footer" id="botones">
                                    
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                         <!-- fin de la modal-->
               

                         <!-- MODAL DEL LA FUNCION AGREGAR DE LOS PRODUCTOS -->
                <div class="modal fade" id="modaling" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <div class="modal-title" id="enunciado"></div>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                
                            </div>
                            <div class="modal-body">
                            
                                <input type="hidden" name="idrece" id="idrece" >
                                <input type="hidden" name="mercancia_id" id="mercid" >
                                <input type="hidden" name="idproductosel" id="idproduct" >


                                
                                
                                <!-- modal agregar el ingrediente -->
                          <!-- <div class="form-group col-sm-12">
                                    <div class="col-sm-3">
                                        <label class="labels" for="">filtrar:</label>
                                          <div>
                                            <input id="filtro" class="form-control test filtro" placeholder="buscar.." data-toggle="tooltip" data-placement="top" title="Escriba el nombre, la marca o el codigo del producto para filtrar!" required="">
                                          </div>
                                    </div>
                                </div><br>
                                <br>
                                <br> -->

                                
                              <div style="margin-top: 2%" class="card">  
                              <div class="card-block">

                                <div class="dataTable_wrapper " >
                                       <div class="col-sm-12 table-responsive">
                                       
                                          <table id="tablafiltraje" class="display table table-sm table-striped table-bordered table-hover" >
                                            <thead class="theadH">
                                                <tr>
                                                    <th>Codigo</th>
                                                    <th>Ingrediente</th>
                                                    <th>Precio Unitario</th>
                                                    <th>Agregar</th>

                                                </tr>
                                            </thead>
                                            <tbody id="cuerpo_i"></tbody>
                                            
                                        </table>
                                        
                                                 
                                          </div>
                                          
                                  </div>

                               </div>
                              </div>

                              

                             

                              
                                

                                
                            
                        </div>
                        
                    </div>
                </div>
                          



                  </div>
                              <!-- Modal cantidad x ingrediente-->
                              <div class="modal fade mcant" id="mcant" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" ><b>Agregar ingrediente</b></h5>
                                    </div>
                                    <div class="modal-body">
                                    <div id="cuerpoagregar"></div>
                                        <div class="form-group">
                                          <label class="form-control-label">Cantidad:</label>
                                          <input id="canti" class="form-control " placeholder="cantidad"  title="cantidad por ingrediente" >
                                        </div>
                                        <div class="form-group">
                                          <label class="form-control-label">Unidad de medida:</label>
                                          <select id="unidadmed" name="unidadmed"  class="form-control">
                                          </select>
                                        </div>
                                        
                                    </div>
                                    <div class="modal-footer justify-content-center" id="bot">
                                      
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <!-- fin modal -->

                </div>
              </div>
        </div>
</div>
</div>
                            
</body>

</div>



<!-- Autocomplete -->

</html>
