</div> <!-- #wrapper -->
	
	<footer id="footer">
		<ul class="nav pull-right">
			<li>
				
			</li>
		</ul>
	</footer>
	<label hidden id="base_url"><?php echo BASE_URL; ?></label>
	<label hidden id="public_url"><?php echo PUBLIC_URL; ?></label>
	<input type="hidden" id="valormenu">
<script src="<?php echo PUBLIC_URL; ?>js/jquery-1.12.1.min.js"></script>

	<!-- / START - page related files and scripts [optional] -->
    <?php  if (isset($_view_params['js']) && count($_view_params['js'])): ?>
	<?php  	for ($i = 0; $i < count($_view_params['js']); $i++):  ?>
		<script src="<?php echo $_view_params['js'][$i]; ?>"></script>
	<?php  	endfor; ?>
	<?php  endif;?>
    <!-- / END - page related files and scripts [optional] -->
    
    <!-- Bootstrap Core JavaScript -->

    
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/opciones.js"></script>
    <script src="<?php echo PUBLIC_URL; ?>js/tether.min.js"></script>
    <script src="<?php echo PUBLIC_URL; ?>js/bootstrap.min.js"></script>
    <script src="<?php echo PUBLIC_URL; ?>js/jquery.cookie.js"> </script>
    <script src="<?php echo PUBLIC_URL; ?>js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
    <script src="<?php echo PUBLIC_URL; ?>js/front.js"></script>
    <script src="<?php echo PUBLIC_URL; ?>js/jquery.nicescroll.min.js"></script>
    <script src="<?php echo PUBLIC_URL; ?>js/jquery.validate.min.js"></script>


    



	    <!-- you can replace it by local Font Awesome-->


	
	<script>
	   var BASE_URL = $('#base_url').text();
	   var PUBLIC_URL = $('#public_url').text();
	   //alert(PUBLIC_URL);
	</script>
	<script type="text/javascript"> 
		$(document).ready(function(){

				var texto = $('#titulocard').text();
			$('#valormenu').val(texto);
			var escritura = $('#valormenu').val();
			$('#area').empty();
			$('#area').html(escritura);
			$('[data-toggle="tooltip"]').tooltip();   
		    //$('.nicescroll-cursors').removeAttr('style');
			$('#gifcargando').fadeOut(600);
			setTimeout(function() {$('#body').fadeIn(700);$('#body').prop("hidden",false)}, 600);
		   /* $("a.subM").click(function(event){ event.preventDefault(); linkLocation = this.href; $('#body').fadeOut(500, redirectPage); }); function redirectPage() { window.location = linkLocation; } 
		    $(".atras").click(function(event){ event.preventDefault();  $('#body').fadeOut(500); });*/ 
		});
	</script>



</body>
</html>
	 <!-- /#wrapper -->

    <!-- jQuery -->
    


</div>
   
</body>

</html>

<!-- end footer.phtml -->