<!-- header.phtml -->
<script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/notificaciones.js"></script>
<?php $bussines= Session::empresa('idUsuario');
  if (!empty($bussines)) {
    echo '<input type="hidden" id="valor" value="e">';
  }else{
    echo '<input type="hidden" id="valor" value="t">';
  }
?>
<script type="text/javascript">
            window.onload = function() {
              var valor = $('#valor').val();
                    setInterval('verificarN("'+valor+'")',3000);
            }
        </script>
    <div id="wrap" >
    <?php #$menu= Session::modelo('idUsuario'); print_r($menu); ?>
     <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img style="margin-left:7%;" src="<?php echo PUBLIC_URL;?>img\epoc-logo.jpg" class="img-responsive" alt="EPOC">
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right" >
               
                <li class="dropdown" >
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      
                        <i class="glyphicon glyphicon-user
 fa-fw"></i><?php $usuario = Session::modelo('idUsuario'); echo  utf8_decode('Sr(a). '.$usuario[0]['name'].' '.$usuario[0]['apellido'].' ' );?> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo BASE_URL;?>login/close"><i class="fa fa-sign-out fa-fw"></i>Cerrar Sesión</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu" style="margin-top:8%;">
                    <?php $menu= Session::modelo('idUsuario');
                          
                            $indi=0; $in=0;
                            for($l=0; $l < count($menu); $l++) {
                              $dato[$l] = $menu[$l]['modelo'];
                              $id[$l]=$menu[$l]['idUd'];
                            }
                            #print_r($dato); exit();
                            $result=array_unique($dato);
                            $idresult=array_unique($id);
                            if(is_array($result) and is_array($idresult)) {
                               foreach($result as $key => $val) {
                                 $privilegios[$indi] = is_array($val) ? $val[$key] : $val;
                                 $indi=$indi+1;
                               }
                               foreach($idresult as $key => $val) {
                                 $id[$in] = is_array($val) ? $val[$key] : $val;
                                 $in=$in+1;
                               }
                            } #print_r($privilegios);
                        echo '<li>
                                            <a style="text-align:left" class="dropdown-toggle" data-toggle="dropdown" href="#" >
                                                <i class="fa fa-bell"></i> Notificaciones <span class="fa arrow"></span>
                                                <o id="notifications"><o>
                                            </a>
                                                <ul class="nav nav-second-level" role="menu" id="news">
                                                </ul>';
                                                                                        
                                        echo '</li>';    
                        for ($i=0; $i < count($privilegios); $i++) {
                        
                          if (!empty($privilegios[$i])) {


                             echo  '<li>
                                      <a style="text-align:left" href="#"><i class="fa fa-university"></i> '.$privilegios[$i].'<span class="fa arrow"></span></a>';
                           for ($j=0; $j < count($menu); $j++) { 
                                if ($privilegios[$i] == $menu[$j]['modelo']) { 
                                  echo  '<ul class="nav nav-second-level"> <li>
                                          <a style="text-align:left" href="#"><i class="fa fa-home"></i> '.$menu[$j]['tienda'].'<span class="fa arrow"></span></a>';
                                  echo '<ul class="nav nav-second-level">
                                          <li>
                                              <a href="#" style="margin-left:15px; text-align:left">Inventario
                                              <i class="fa fa-list"></i><span class="fa arrow"></span></a>
                                              <ul class="nav nav-second-level">
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/evaluar/'.$id[$j].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Stock de la ud.</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$j].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Remision de mercancia</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$j].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Kardex</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$j].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Merma</a>
                                                </li>
                                              </ul>  
                                          </li>
                                          <li>
                                            <a href="#" style="margin-left:15px; text-align:left">Receta
                                              <i class="fa fa-cutlery"></i><span class="fa arrow"></span></a>
                                              <ul class="nav nav-second-level">
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$i].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Produccion</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$i].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Recetario</a>
                                                </li>
                                              </ul>
                                          </li>
                                           <li>
                                            <a href="#" style="margin-left:15px; text-align:left">Administracion
                                              <i class="fa fa-sitemap"></i><span class="fa arrow"></span></a>
                                              <ul class="nav nav-second-level">
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$i].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Proveedor</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$i].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Reportes</a>
                                                </li>
                                              </ul>
                                          </li>
                                        </ul>  ';
                                  echo '</li></li></ul>';
                            }

                            } 
                          }else{
                            for ($p=0; $p < count($menu); $p++) { 
                              if ($menu[$p]['modelo'] == null) {
                                echo  '<li>
                                      <a style="text-align:left" href="#"><i class="fa fa-university"></i> '.$menu[$p]['tienda'].'<span class="fa arrow"></span></a>';
                                  echo '<ul class="nav nav-second-level">
                                          <li>
                                              <a href="#" style="margin-left:15px; text-align:left">Inventario
                                              <i class="fa fa-list"></i><span class="fa arrow"></span></a>
                                              <ul class="nav nav-second-level">
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/evaluar/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Stock de la ud.</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Remision de mercancia</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Kardex</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Merma</a>
                                                </li>
                                              </ul>  
                                          </li>
                                          <li>
                                            <a href="#" style="margin-left:15px; text-align:left">Receta
                                              <i class="fa fa-cutlery"></i><span class="fa arrow"></span></a>
                                              <ul class="nav nav-second-level">
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Produccion</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Recetario</a>
                                                </li>
                                              </ul>
                                          </li>
                                           <li>
                                            <a href="#" style="margin-left:15px; text-align:left">Administracion
                                              <i class="fa fa-sitemap"></i><span class="fa arrow"></span></a>
                                              <ul class="nav nav-second-level">
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Proveedor</a>
                                                </li>
                                                <li style="margin-left:25px; text-align:left">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'" class="subM"><i style="font-size: 6px; vertical-align: middle;" class="fa fa-asterisk"></i>Reportes</a>
                                                </li>
                                              </ul>
                                          </li>
                                        </ul>  ';
                                  echo '</li>';
                              }
                            }
                            
                          }           
                        }
                        
                        echo '<li>
                                  <a style="text-align:left" href="'.PUBLIC_URL.'guia/Instructivo_para_el_uso_del_aplicativo_admin_productos_ventas.pdf" target="_blank" class="subM"><span class="glyphicon glyphicon-info-sign"></span> Ayuda</a>
                              </li>
                              <li>
                                  <a style="text-align:left" href="'.BASE_URL.'login/close"><i class="fa fa-sign-out fa-fw"></i>Cerrar Sesión</a>
                              </li>';
                      ?>
                      
                  </ul>
              </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
          </div>
          
      </nav>
       <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                      <div class="modal fade opciones" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                          <div class="modal-dialog modal-sm" role="document">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                      </button>
                                      <h5 class="modal-title">Seleccione la opcion que desea administrar.</h5>
                                  </div>
                                  <div class="modal-body">
                                      <div class="col-sm-12">
                                          <div class="col-sm-6" id="grupos"></div>
                                          <div class="col-sm-6" id="productos"></div>
                                      </div> <br>
                                      <br>
                                      <br>
                                  </div>   
                              </div><!-- /.modal-content -->
                          </div><!-- /.modal-dialog -->
                      </div><!-- /.modal -->
                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                
<!-- end header.phtml --> 
              