<!-- header.phtml -->
<script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/notificaciones.js"></script>
<?php $bussines= Session::empresa('idUsuario');
  if (!empty($bussines)) {
    echo '<input type="hidden" id="valor" value="e">';
  }else{
    echo '<input type="hidden" id="valor" value="t">';
  }
?>
<style>

  .notif:link   
  }
  {   
   text-decoration:none;   
  }  
  .notif:hover{
    background-color: #eee;
  } 
</style>
        <script type="text/javascript">
            jQuery(document).ready(function($) {
              var valor = $('#valor').val();
                    setInterval('verificarN("'+valor+'")',3000);
            });
        </script>

    <?php #$menu= Session::modelo('idUsuario'); print_r($menu); ?>
<nav style="font-size: 11px" class="side-navbar">
      <div class="side-navbar-wrapper">
        <div class="sidenav-header d-flex align-items-center justify-content-center">
          <div class="sidenav-header-inner text-center"><img src="<?php echo PUBLIC_URL; ?>aimg/avatar-1.jpg" alt="" class="img-fluid rounded-circle">
            <h2 class="h5 text-uppercase"><?php $usuario = Session::modelo('idUsuario'); echo  utf8_decode($usuario[0]['name'].' '.$usuario[0]['apellido'].' ' );?></h2><span class="text-uppercase"><?php $usuario = Session::modelo('idUsuario'); echo  utf8_decode($usuario[0]['perfil']);?></span>
          </div>
          <div class="sidenav-header-logo"><a href="<?php echo BASE_URL.'index/index/'; ?>" class="brand-small text-center"> <strong>C</strong><strong class="text-primary">W</strong></a></div>
        </div>
        <div class="main-menu">
          <ul id="side-main-menu" class="side-menu list-unstyled">
          <?php $menu= Session::modelo('idUsuario');
                          
                            $indi=0; $in=0;
                            for($l=0; $l < count($menu); $l++) {
                              $dato[$l] = $menu[$l]['modelo'];
                              $id[$l]=$menu[$l]['idUd'];
                            }
                            #print_r($dato); exit();
                            $result=array_unique($dato);
                            $idresult=array_unique($id);
                            if(is_array($result) and is_array($idresult)) {
                               foreach($result as $key => $val) {
                                 $privilegios[$indi] = is_array($val) ? $val[$key] : $val;
                                 $indi=$indi+1;
                               }
                               foreach($idresult as $key => $val) {
                                 $id[$in] = is_array($val) ? $val[$key] : $val;
                                 $in=$in+1;
                               }
                            }
                            
                            for ($i=0; $i < count($privilegios); $i++) {
                        
                          if (!empty($privilegios[$i])) {


                             echo  '<li>
                                      <a style="" href="#modelo'.$i.'" data-toggle="collapse" aria-expanded="false"><i class="fa fa-university"></i> '.$privilegios[$i].'<div class="arrow pull-right"><i class="fa fa-angle-down"></i></div></a>
                                      <ul class="collapse side-menu list-unstyled" id="modelo'.$i.'">';
                           for ($j=0; $j < count($menu); $j++) { 
                                if ($privilegios[$i] == $menu[$j]['modelo']) { 
                                  echo  '<li>
                                          <a style="" href="#tienda'.$j.'" data-toggle="collapse" aria-expanded="false"><i class="fa fa-home"></i> '.$menu[$j]['tienda'].'<div class="arrow pull-right"><i class="fa fa-angle-down"></i></div></a>';
                                  echo '<ul class="side-menu collapse list-unstyled" id="tienda'.$j.'">
                                          <li>
                                              <a href="#inv'.$j.'" data-toggle="collapse" aria-expanded="false" style="margin-left:5px; ">Inventario
                                              <i class="fa fa-list"></i><div class="arrow pull-right"><i class="fa fa-angle-down"></i></div></a>
                                              <ul class="collapse list-unstyled" id="inv'.$j.'">
                                                <li ">
                                                  <a href="'.BASE_URL.'inventario/evaluar/'.$id[$j].'" class="subM" style="margin-left:12px; "></i>Consulta de inventario</a>
                                                </li>
                                                <li ">
                                                  <a href="'.BASE_URL.'inventario/remisionM/'.$id[$j].'" class="subM" style="margin-left:12px; "></i>Remision de mercancia</a>
                                                </li>
                                                <li ">
                                                  <a href="'.BASE_URL.'inventario/reposicionM/'.$id[$j].'" class="subM" style="margin-left:12px; "></i>Reposicion de mercancia</a>
                                                </li>
                                                <li ">
                                                  <a href="'.BASE_URL.'inventario/indexk/'.$id[$j].'" class="subM" style="margin-left:12px; "></i>Movimientos de kardex</a>
                                                </li>
                                                <li ">
                                                  <a href="'.BASE_URL.'inventario/inicio/'.$id[$j].'" class="subM" style="margin-left:12px; "></i>Merma</a>
                                                </li>
                                                <li ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$id[$j].'"*/ class="subM" style="margin-left:12px; "></i>Inventario inicial</a>
                                                </li>
                                                <li ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$id[$j].'"*/ class="subM" style="margin-left:12px; "></i>Inventario final</a>
                                                </li>
                                              </ul>  
                                          </li>
                                          <li>
                                            <a href="'.BASE_URL.'receta/indexr/'.$id[$j].'" style="margin-left:5px; ">Receta
                                              <i class="fa fa-cutlery"></i></span></a>   
                                          </li>
                                          <li>
                                            <a /*href="'.BASE_URL.'inventario/inicio/'.$id[$i].'"*/ style="margin-left:5px; ">Generar produccion
                                              <i class="fa fa-cogs"></i></span></a>   
                                          </li>
                                          <li>
                                            <a href="'.BASE_URL.'explosion/index/'.$id[$j].'" style="margin-left:5px; ">Explosion de ingredientes
                                              <i class="fa fa-bomb"></i></span></a>   
                                          </li>
                                           <li>
                                            <a href="#admint'.$j.'" style="margin-left:5px; " data-toggle="collapse" aria-expanded="false">Administracion
                                              <i class="fa fa-briefcase"></i><div class="arrow pull-right"><i class="fa fa-angle-down"></i></div></a>
                                              <ul class="collapse list-unstyled" id="admint'.$j.'">
                                                <li ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$id[$i].'"*/ class="subM" style="margin-left:12px; "></i>Proveedor</a>
                                                </li>
                                                <li ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$id[$i].'"*/ class="subM" style="margin-left:12px; "></i>Carga factura de compra</a>
                                                </li>
                                                <li ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$id[$i].'"*/ class="subM" style="margin-left:12px; "></i>Ranking de venta</a>
                                                </li>
                                                <li ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$id[$i].'"*/ class="subM" style="margin-left:12px; "></i>Reportes</a>
                                                </li>
                                              </ul>
                                          </li>';
                                  echo '</ul>  ';
                                  echo '</li>';
                            }

                            } 
                            echo '</ul></li>';
                          }else{
                            for ($p=0; $p < count($menu); $p++) { 
                              if ($menu[$p]['modelo'] == null) {
                                echo  '<li>
                                      <a style="" href="#empresa'.$p.'" data-toggle="collapse" aria-expanded="false"><i class="fa fa-university"></i> '.$menu[$p]['tienda'].'<div class="arrow pull-right"><i class="fa fa-angle-down"></i></div></a>';
                                  echo '<ul class="collapse list-unstyled" id="empresa'.$p.'">
                                          <li>
                                              <a href="#tiendae'.$p.'" style="margin-left:5px; " data-toggle="collapse" aria-expanded="false">Inventario
                                              <i class="fa fa-list"></i><div class="arrow pull-right"><i class="fa fa-angle-down"></i></div></a>
                                              <ul class="collapse list-unstyled" id="tiendae'.$p.'">
                                                <li ">
                                                  <a style="margin-left:12px; " href="'.BASE_URL.'inventario/evaluar/'.$menu[$p]['idUd'].'" class="subM"></i>Consulta de inventario</a>
                                                </li>
                                                <li ">
                                                  <a href="'.BASE_URL.'inventario/reposicionM/'.$menu[$p]['idUd'].'" class="subM" style="margin-left:12px; "></i>Reposicion de mercancia</a>
                                                </li>
                                                <li ">
                                                  <a style="margin-left:12px; " href="'.BASE_URL.'inventario/asignacionProducto/'.$menu[$p]['idUd'].'" class="subM"></i>Asignacion de productos</a>
                                                </li>
                                                <!--<li ">
                                                  <a style="margin-left:12px; " href="'.BASE_URL.'inventario/remisionM/'.$menu[$p]['idUd'].'" class="subM"></i>Remision de mercancia</a>
                                                </li>-->
                                                <li ">
                                                  <a style="margin-left:12px; " href="'.BASE_URL.'inventario/indexk/'.$menu[$p]['idUd'].'" class="subM"></i>Movimientos de kardex</a>
                                                </li>
                                                <li ">
                                                  <a style="margin-left:12px; " /*href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'"*/ class="subM"></i>Merma</a>
                                                </li>
                                                <li ">
                                                  <a style="margin-left:12px; " /*href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'"*/ class="subM"></i>Inventario final</a>
                                                </li>
                                              </ul>  
                                          </li>
                                          <li>
                                            <a href="'.BASE_URL.'receta/indexr/'.$menu[$p]['idUd'].'" style="margin-left:5px; ">Receta
                                              <i class="fa fa-cutlery"></i></span></a>   
                                          </li>
                                          <li>
                                            <a /*href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'"*/ style="margin-left:5px; ">Generar produccion
                                              <i class="fa fa-cogs"></i></span></a>   
                                          </li>
                                          <li>
                                            <a href="'.BASE_URL.'explosion/index/'.$menu[$p]['idUd'].'" style="margin-left:5px; ">Generar explosion
                                              <i class="fa fa-bomb"></i></span></a>   
                                          </li>
                                           <li>
                                            <a href="#adm'.$j.'" style="margin-left:5px; " data-toggle="collapse" aria-expanded="false">Administracion
                                              <i class="fa fa-briefcase"></i><div class="arrow pull-right"><i class="fa fa-angle-down"></i></div></a>
                                              <ul class="collapse list-unstyled" id="adm'.$j.'">
                                                <li style="margin-left:12px; ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'"*/ class="subM"></i>Proveedor</a>
                                                </li>
                                                <li style="margin-left:12px; ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'"*/ class="subM"></i>Carga factura de compra</a>
                                                </li>
                                                <li style="margin-left:12px; ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'"*/ class="subM"></i>Ranking de venta</a>
                                                </li>
                                                <li style="margin-left:12px; ">
                                                  <a /*href="'.BASE_URL.'inventario/inicio/'.$menu[$p]['idUd'].'"*/ class="subM"></i>Reportes</a>
                                                </li>
                                              </ul>
                                          </li>';
                                  echo '</ul>  ';
                                  echo '</li>';
                              }
                            }
                            
                          }           
                        }
                        
                        echo '<li>
                                  <a style="" href="'.PUBLIC_URL.'guia/Instructivo_para_el_uso_del_aplicativo_admin_productos_ventas.pdf" target="_blank" class="subM"><i class="fa fa-info-circle"></i> Ayuda</a>
                              </li>';
                              if (Session::get('header') == 1) {
                                          echo '<li>
                                            <form id="corporativa" class="form-horizontal" role="form"  action=""  method="post"> 

                                            <button type="submit" fomr="corporativa" formmethod="post" formaction="http://www.hdjgr.com.ve/epoc-web/support/login/signIn/"  class="btn btn-primary " style="width:100%; border-radius:0px; text-align:left;" name="password" id="corp"  value="'.Session::get('clave').'" ><i class="fa fa-sign-in" aria-hidden="true"></i> Area corporativa</a>
                                            </button>
                                          </form>
                                        </li>';
                              }else{
                                echo '<li>
                                  <a style="" href="'.BASE_URL.'login/close"><i class="fa fa-sign-out fa-fw"></i>Cerrar Sesión</a>
                                </li>';
                              }
                              
                      ?>             
            
    </nav>

     <div class="page home-page">
      <!-- navbar-->
      <header class="header">
        <nav class="navbar">
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn" style="height: 30px"><i style="font-size: 1.5em" class="icon-bars"> </i></a><a href="<?php echo BASE_URL.'index/index/'; ?>" class="navbar-brand">
                  <div class="text-default hidden-sm-down"><i class="material-icons" style="font-size: 16px; vertical-align: top">home</i> COCAI <strong class="text-primary"> WEB</strong></div></a></div>
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                <li class="nav-item dropdown"> 
                  <a id="not" rel="nofollow" data-target="#" href="#"  aria-haspopup="true" aria-expanded="false" class="nav-link">
                    <i class="fa fa-bell-slash"></i>
                      <span id="circulo" style="border-radius: 10px; font-size: 11px; visibility: hidden;" class="badge badge-danger">
                        <o id="notifications"></o>
                      </span>
                  </a>
                  <ul class="dropdown-menu" role="menu" id="news" style="height: 200px; width: 355px; overflow-y: auto">
                  </ul>
                </li>
                <!--<li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-envelope"></i><span class="badge badge-info">10</span></a>
                  <ul aria-labelledby="notifications" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-profile"> <img src="img/avatar-1.jpg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Jason Doe</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-profile"> <img src="img/avatar-2.jpg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Frank Williams</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-profile"> <img src="img/avatar-3.jpg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Ashley Wood</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-envelope"></i>Read all messages    </strong></a></li>
                  </ul>
                </li>-->
                <li class="nav-item"><a href="<?php echo BASE_URL;?>login/close"" class="nav-link logout">Cerrar sesion<i class="fa fa-sign-out"></i></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <?php if (isset($this->model[0]['udn'])) {
        ?><div class="breadcrumb-holder">
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><?php $ti=strtolower($this->model[0]['udn']); echo strtoupper($ti);?></li>
            <li class="breadcrumb-item active" id="area"></li>
          </ul>
        </div>
      </div>
      <?php  } ?>
      <?php if (isset($this->mercancia[0]['tienda'])) {
        ?><div class="breadcrumb-holder">
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><?php $ti=strtolower($this->mercancia[0]['tienda']); echo strtoupper($ti);?></li>
            <li class="breadcrumb-item active" id="area"></li>
          </ul>
        </div>
      </div>
      <?php  } ?>
      <?php if (isset($this->g[0]['tienda'])) {
        ?><div class="breadcrumb-holder">
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><?php $ti=strtolower($this->g[0]['tienda']); echo strtoupper($ti);?></li>
            <li class="breadcrumb-item active" id="area"></li>
          </ul>
        </div>
      </div>
      <?php  } ?>
      <?php if (isset($this->datos[0]['tiendaen'])) {
        ?><div class="breadcrumb-holder">
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><?php $ti=strtolower($this->datos[0]['tiendaen']); echo strtoupper($ti);?></li>
            <li class="breadcrumb-item active" id="area"></li>
          </ul>
        </div>
      </div>
      <?php  } ?>
          
      </nav>


       <!-- MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                      <div class="modal fade opciones" id="new" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                          <div class="modal-dialog modal-sm" role="document">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                      </button>
                                      <h5 class="modal-title">Seleccione la opcion que desea administrar.</h5>
                                  </div>
                                  <div class="modal-body">
                                      <div class="col-sm-12">
                                          <div class="col-sm-6" id="grupos"></div>
                                          <div class="col-sm-6" id="productos"></div>
                                      </div> <br>
                                      <br>
                                      <br>
                                  </div>   
                              </div><!-- /.modal-content -->
                          </div><!-- /.modal-dialog -->
                      </div><!-- /.modal -->
                      <!-- FIN DE LA MODAL DEL LA FUNCION MODIFICAR DE LOS SUB-MODELOS -->
                
<!-- end header.phtml --> 
              