<link rel="shortcut icon" href="<?php echo PUBLIC_URL; ?>img/favicon.ico" type="image/x-icon"/>
<link rel="icon" href="<?php echo PUBLIC_URL; ?>img/favicon.ico" type="image/x-icon">
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <background-color: black;>
    <meta name="description" content="">
    <meta name="author" content="">

    <title>COCAI</title>
    <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_URL; ?>datatable/css/bootstrap4.min.css"/>
    <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/bootstrap.min.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/style.blue.css" id="theme-stylesheet">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/grasp_mobile_progress_circle-1.0.0.min.css">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.ico">
    <!-- Font Awesome CDN-->
    <!-- you can replace it by local Font Awesome-->
    <script src="https://use.fontawesome.com/99347ac47f.js"></script>
    <!-- Font Icons CSS-->



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

       

        <!-- Page Content -->

    
   